LICENSE.txt
README.md

As opposed to Transfer by Artie to be consistent with industry

Renaming to Artie Transfer

---

README.md

Current README makes it seem like the steps are sequential.
Appending `or` at the end to be more obvious

Adding clarification

---

README.md
clients/snowflake/snowflake.go
examples/mongodb/connect/connect-distributed.properties
lib/cdc/mongo/debezium.go
lib/cdc/mongo/debezium_test.go
lib/cdc/mongo/event.go
lib/cdc/postgres/event.go
lib/debezium/schema.go
processes/kafka/process_test.go

Following this PR: https://github.com/artie-labs/transfer/pull/27
Which addresses https://github.com/artie-labs/transfer/issues/28
Work prior to merge:

MongoDB to support schemas

---

README.md
lib/telemetry/README.md

Addresses https://github.com/artie-labs/transfer/issues/35

Migrate documentation to gitbooks

---

clients/bigquery/merge.go
clients/snowflake/merge.go
lib/dwh/dml/merge.go
lib/dwh/dml/merge_test.go

The purpose of this PR is similar to https://github.com/artie-labs/transfer/pull/43, where this PR is consolidating the boilerplate for `Merge`. 
After this, we will then add the ability to have soft-delete.

Refactoring DWH Merge

---

lib/typing/ext/parse_test.go
processes/kafka/consumer.go

Addresses https://github.com/artie-labs/transfer/issues/47
Working as expected. Post merge, will add this to our documentation.

Adding ingestion lag

---

clients/snowflake/errors.go
clients/snowflake/errors_test.go
clients/snowflake/snowflake.go

Previous PR that was addressing it: https://github.com/artie-labs/transfer/pull/56, this setting didn't work.
Will remove the configuration option and re-establish the connection within Transfer.

[Snowflake] Reestablish idle sessions

---

processes/consumer/pubsub.go

Within Pub/Sub, even though a subscription lives within a Topic...a subscription requires a globally unique name.
Thus, the previous name `transfer` is insufficient. Instead, we'll name the subscription as: `transfer_{{TOPIC_NAME}}`

[Pub/Sub] Using unique subscription names

---

README.md

Including the docs badge and centering

Updating the README 

---

lib/cdc/util/relational_event.go
lib/cdc/util/relational_event_test.go

As per title.
So we can import this.

Make the payload object public

---

clients/bigquery/merge.go
clients/snowflake/snowflake.go
lib/dwh/ddl/ddl.go
lib/dwh/ddl/ddl_bq_test.go
lib/dwh/ddl/ddl_sflk_test.go

Doing this to clean up our DDL package and make it more streamlined. 
This is a pre-req for us to refactor our BigQuery strategy to increase throughput.

[Refactor] Creating alterTableArgs for our DDL package

---

main.go
models/flush/flush.go
models/flush/flush_suite_test.go
models/flush/flush_test.go
models/memory.go
models/memory_test.go
models/models_suite_test.go
processes/consumer/process_test.go

1) Avoid global variables
2) This PR is a pre-req for us to refactor flush optimization.

Fold databaseData into context

---

.github/workflows/gha-go-test.yml
Makefile
clients/bigquery/ddl.go
clients/bigquery/merge.go
clients/snowflake/ddl.go
clients/snowflake/ddl_test.go
clients/snowflake/snowflake.go
clients/snowflake/snowflake_test.go
clients/snowflake/staging.go
clients/snowflake/staging_test.go
lib/dwh/ddl/ddl_bq_test.go
lib/dwh/ddl/ddl_create_table_test.go
lib/dwh/ddl/ddl_sflk_test.go
lib/dwh/ddl/ddl_temp_test.go
lib/dwh/types/table_config.go
lib/dwh/types/table_config_test.go
lib/dwh/types/types.go
lib/dwh/types/types_test.go
lib/typing/columns.go
lib/typing/diff.go
lib/typing/diff_test.go

As per title.
And also add `go test -race ./...` into our GHA so we can block regression in the future.

Fix potential race condition

---

clients/bigquery/merge.go
clients/snowflake/ddl_test.go
clients/snowflake/snowflake.go
clients/snowflake/staging.go
lib/dwh/ddl/ddl_bq_test.go
lib/dwh/ddl/ddl_create_table_test.go
lib/dwh/types/table_config.go

As per title. Patching 2 minor ones that got flagged during `make race`

Patch another potential data race cond

---

clients/snowflake/ddl_test.go
lib/dwh/ddl/ddl.go
lib/dwh/types/table_config.go
lib/dwh/types/table_config_test.go

Adding more visibility to `ShouldDeleteColumn`'s function

[DDL] Adding logging to ShouldDeleteColumn f(x)

---

lib/cdc/mongo/debezium.go
lib/cdc/mongo/debezium_test.go
lib/cdc/mysql/debezium_test.go
lib/cdc/postgres/debezium.go
lib/cdc/util/relational_event.go
lib/debezium/keys.go
lib/debezium/keys_test.go
lib/typing/columns/columns.go
lib/typing/columns/columns_test.go
models/event/event.go

Follow up from this PR: https://github.com/artie-labs/transfer/pull/150
In this PR, we are adding tests and improving from that and escape primary key(s) from the partition key.

Better handle on escaping columns

---

README.md

Fixes https://github.com/artie-labs/transfer/issues/160

Fixing typo from README.

---

lib/optimization/event.go
models/event/event.go
models/memory.go
models/memory_flush_test.go
processes/consumer/flush.go

This PR is missing a return https://github.com/artie-labs/transfer/pull/196, so we're adding it in.
Also, adding a padding to avoid any unwanted merge skips.

Merge Cooldown patch - actually skip

---

README.md

Update Artie Logo

---

Makefile
lib/config/config.go
lib/config/config_test.go
lib/typing/columns/columns.go
lib/typing/columns/diff_test.go
lib/typing/typing.go
processes/consumer/kafka.go

Addressing more staticchecks and reducing code smell, also adding a new command in `Makefile` so we can do `make static`

Addressing Staticcheck

---

clients/snowflake/staging.go
clients/snowflake/util.go
clients/snowflake/util_test.go
lib/cdc/util/parse.go
lib/cdc/util/parse_test.go
lib/stringutil/strings.go
lib/telemetry/metrics/null_provider.go
lib/typing/columns/default.go
lib/typing/columns/default_test.go
models/event/events_suite_test.go

No functionality changes, just cleaning up some tests and improving overall code quality

Minor clean up

---

.github/workflows/gha-go-test.yml
lib/config/constants/constants.go
lib/config/context.go
lib/destination/utils/context.go
lib/destination/utils/context_test.go
lib/logger/context.go
lib/telemetry/metrics/context.go
models/memory.go

Addressing the staticcheck errors and then turning this rule on.

Fix staticcheck errors + turning it on

---

clients/snowflake/snowflake.go
lib/config/config.go
lib/config/config_test.go

* Adding the ability to pass in application name into Snowflake

[Snowflake] Passing in application

---

clients/snowflake/staging_test.go
clients/utils/utils.go

Default is not inherently a reserved keyword, so we don't need to escape it normally, but there's a weird edge case in Snowflake that requires us to skip it in the where clause.
Added a TODO to remove this once we are escaping everything by default.

[Snowflake] Backfill columns where name = 'default'

---

models/event/event.go

Debezium is now using `map` as their default [hstore.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-hstore-handling-mode)
When an `hstore` value is TOASTED where handling mode is `map`. The value will look like: `{__debezium_unavailable_value: __debezium_unavailable_value}`

Handling TOASTED `hstore` values

---

go.mod
go.sum
lib/cdc/util/geometry.go
lib/cdc/util/geometry_test.go
lib/cdc/util/parse.go
lib/debezium/schema.go
lib/debezium/types.go

In addition to supporting `Point`, we should be able to support `Geometry`.

[PostGIS] Supporting Geometry

---

lib/array/strings.go
lib/debezium/schema_test.go
lib/kafkalib/partition/settings.go
lib/kafkalib/topic.go
lib/kafkalib/topic_test.go
lib/logger/log.go
lib/numbers/numbers.go
lib/numbers/numbers_test.go
lib/sql/escape.go
lib/typing/decimal/decimal.go
main.go

Also:
- kill `log.Fatalf`
- remove unused method `kafkalib.ToCacheKey`

Use slices.Contains() and max()

---

lib/config/config.go
lib/config/config_test.go

As per title, adding the YAML annotations

[config] Add yaml annotation to typing.Settings.

---

clients/bigquery/merge.go
clients/redshift/staging.go
clients/s3/s3.go
clients/snowflake/staging.go
clients/utils/utils.go
lib/config/config.go
lib/config/config_test.go
models/event/event.go
processes/consumer/process.go

Standardizing everyone to use the new format. When publishing this, we'll publish a separate version.

Deprecating old typing settings to standardize

---

lib/db/errors.go
lib/db/errors_test.go

Depends on https://github.com/artie-labs/transfer/pull/330

Match wrapped retryable errors using `errors.Is`

---

lib/cdc/util/geometry.go
lib/cdc/util/parse.go
lib/cdc/util/parse_test.go
lib/debezium/schema.go
lib/debezium/types.go

1. Switching from `wkb` to `ewkb` which suppots SRID.
2. Supporting Geography

[Postgis] Support Geography

---

lib/kafkalib/topic.go
lib/kafkalib/topic_test.go

So we can gain additional insights into `topicConfig`

Adding `skippedOperations` to `TopicConfig.String()`

---

lib/artie/message.go
processes/consumer/kafka.go
processes/consumer/pubsub.go

We currently don't have it, so let's add it.

[Telemetry] Add Mode to Row & Ingestion Lag

---

clients/shared/merge.go

Fast follow from: https://github.com/artie-labs/transfer/pull/343#discussion_r1492932178

[MERGE] Specify max retry attempts

---

lib/cdc/util/parse.go
lib/cdc/util/parse_test.go
lib/jsonutil/jsonutil.go

It already worked, adding tests and removing the TODO.

Debezium Parse Field - Address Arrays

---

clients/bigquery/bigquery.go
clients/redshift/redshift.go
clients/s3/s3.go
clients/snowflake/snowflake.go
clients/snowflake/snowflake_test.go
lib/destination/ddl/ddl_alter_delete_test.go
lib/destination/ddl/ddl_bq_test.go
lib/optimization/table_data.go
lib/optimization/table_data_test.go
lib/typing/decimal/base.go
lib/typing/decimal/decimal.go

Cleaning up non MSSQL related changes so the diff for https://github.com/artie-labs/transfer/pull/355 will be smaller
1. Standing up `FqNameOpts` so we can add more variables w/o having to go through significant refactors
2. Standing up `decimal.toKind(...)` to reduce boilerplate

Code clean up

---

lib/destination/dml/merge.go

Addressing a TODO about being consistent with uppercasing.

[MSSQL] Merge to be consistent about casing

---

clients/bigquery/cast_test.go
clients/redshift/cast_test.go
clients/s3/s3.go
lib/cdc/event.go
lib/cdc/mongo/debezium.go
lib/cdc/mongo/event.go
lib/cdc/mysql/debezium.go
lib/cdc/mysql/debezium_test.go
lib/cdc/postgres/debezium_test.go
lib/cdc/util/geometry_test.go
lib/cdc/util/relational_event.go
lib/cdc/util/relational_event_test.go
lib/config/config_test.go
lib/debezium/schema_test.go
lib/debezium/types.go
lib/debezium/types_bench_test.go
lib/debezium/types_test.go
lib/jsonutil/jsonutil_test.go
lib/maputil/map_test.go
lib/optimization/event_insert_test.go
lib/size/size.go
lib/size/size_bench_test.go
lib/size/size_test.go
lib/stringutil/strings_test.go
lib/typing/values/string_test.go
models/event/event_save_test.go

Follow up PR to: https://github.com/artie-labs/transfer/pull/366

Replacing more interface{} with any - Part 2

---

.github/workflows/gha-go-test.yml
Dockerfile

[gha] Use prebuilt binary for `staticcheck`

---

README.md
clients/shared/merge.go
lib/logger/log.go
lib/optimization/table_data.go
main.go
models/event/event_save_test.go
processes/consumer/flush_suite_test.go
processes/consumer/kafka.go
processes/consumer/process.go
processes/consumer/process_test.go

* Updating README
* Inlining MERGE
* Adding `cleanUpHandlers` function to ensure errors get logged to Sentry
* Removing and moving functions that are related to tests into test suites.

Minor improvements

---

lib/sql/escape.go

Fixes `tautological condition: non-nil != nil`

Remove nil check

---

lib/destination/dml/merge.go
lib/destination/dml/merge_mssql_test.go
lib/destination/dml/merge_test.go
lib/optimization/table_data.go
lib/typing/columns/wrapper.go

1. Adding tests to Microsoft SQL Server
2. Renaming some variables here and there

Minor Transfer clean up

---

processes/consumer/kafka.go

[Tombstones] Switch Info to Debug

---

clients/mssql/values.go
lib/typing/values/string.go
lib/typing/values/string_test.go

This PR adds the ability to cast a `boolean` value into a `bit` if the column in the destination is an `integer`.
I also rewrote the tests to cover every case and make it more clear what is being tested.

[Typing] Convert bool to bit if the column kind is an integer

---

clients/snowflake/snowflake_test.go
clients/snowflake/staging.go
clients/snowflake/staging_test.go

* Improving the comments for preparing temporary tables
* Adding tests
* Renaming a function

Improve clarity around Snowflake temporary tables

---

lib/config/config.go
lib/config/config_test.go
lib/numbers/numbers.go
lib/numbers/numbers_test.go
lib/typing/decimal/base.go

Main changes here are to clean up the verbosity of config validate

Cleaning up config validation

---

clients/bigquery/bigquery.go
clients/mssql/staging.go
clients/redshift/staging.go
clients/shared/append.go
clients/shared/merge.go
clients/snowflake/staging.go
lib/destination/ddl/ddl.go
lib/destination/ddl/ddl_alter_delete_test.go
lib/destination/ddl/ddl_bq_test.go
lib/destination/ddl/ddl_create_table_test.go
lib/destination/ddl/ddl_sflk_test.go
lib/destination/ddl/ddl_temp_test.go

1. Adding a debug log to dropping temporary tables
2. Changing `AlterTable` to a receiver method

[DDL] Minor refactor of the ddl pkg

---

clients/shared/merge.go

So when an error inevitably happens, we are aware of it.

Add more error wrapping on MERGE.

---

clients/bigquery/bigquery.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/shared/table_config.go
clients/shared/table_config_test.go
clients/snowflake/snowflake.go
lib/typing/bigquery.go
lib/typing/bigquery_test.go
lib/typing/mssql.go
lib/typing/redshift.go
lib/typing/redshift_test.go
lib/typing/snowflake.go
lib/typing/snowflake_test.go
lib/typing/typing.go

* Rewriting certain tests
* Made `GetTableConfig` into a receiver method

Improving TableConfig code

---

clients/bigquery/bigquery.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/snowflake/snowflake.go
lib/destination/dwh.go

Implements dedupe for Snowflake.

Add dedupe scaffolding

---

clients/bigquery/bigquery.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/s3/s3.go
clients/snowflake/snowflake.go
clients/snowflake/snowflake_test.go
lib/destination/ddl/ddl_alter_delete_test.go
lib/destination/ddl/ddl_bq_test.go
lib/optimization/table_data.go
lib/optimization/table_data_test.go
lib/optimization/tableid.go

This pulls `ToFqName` off of `TableData` and onto a new `TableIdentifier` struct.

Add a `TableIdentifier` struct

---

clients/snowflake/staging.go
clients/snowflake/staging_test.go
lib/typing/values/string.go

Similar to Redshift, Snowflake has a similar LOB limit on the VARIANT column.
https://community.snowflake.com/s/article/Max-LOB-size-exceeded#:~:text=When%20ingesting%20XML%20or%20JSON,of%20parsed%20column%20is%2017894470.

[Snowflake] Max LOB guardrail

---

lib/cdc/util/relational_event.go
lib/debezium/keys.go
lib/debezium/keys_test.go

We previously were not parsing primary keys.

Parse Primary Keys.

---

clients/bigquery/bigquery_test.go
clients/mssql/store_test.go
clients/redshift/redshift_test.go
clients/s3/s3_test.go
clients/snowflake/snowflake_test.go
lib/optimization/table_data_test.go

Merges test cases into data warehouse specific `TestFullyQualifiedName` tests. Once merged it will simplify https://github.com/artie-labs/transfer/pull/450.

[tests] Split up `TestNewTableData_TableName` test

---

clients/bigquery/bigquery.go
clients/bigquery/bigquery_test.go
clients/mssql/store.go
clients/mssql/store_test.go
clients/redshift/redshift.go
clients/redshift/redshift_test.go
clients/s3/s3_test.go
clients/snowflake/snowflake_test.go
lib/optimization/table_data.go
lib/optimization/table_data_test.go

Renamed a few things with VSCode.

Rename `TableData.RawName` to `Name`

---

lib/jsonutil/jsonutil.go
lib/jsonutil/jsonutil_test.go

[Types] Fix Empty String edgecase

---

clients/bigquery/bigquery.go
clients/bigquery/bigquery_test.go
clients/bigquery/merge.go
clients/mssql/store.go
clients/mssql/store_test.go
clients/redshift/redshift.go
clients/redshift/redshift_test.go
clients/redshift/writes.go
clients/s3/s3.go
clients/shared/append.go
clients/shared/merge.go
clients/snowflake/ddl_test.go
clients/snowflake/snowflake.go
clients/snowflake/snowflake_test.go
lib/destination/ddl/ddl_alter_delete_test.go
lib/destination/ddl/ddl_bq_test.go
lib/optimization/table_data.go
processes/consumer/flush.go

[Table Data] Add a Getter for TopicConfig

---

clients/bigquery/bigquery.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/snowflake/snowflake.go

I think I must have merged https://github.com/artie-labs/transfer/pull/462 without pulling in the changes from https://github.com/artie-labs/transfer/pull/460 first.

Add missing calls to `TableData.TopicConfig`

---

clients/bigquery/cast.go

[BigQuery] Guardrail for empty JSON string.

---

lib/kafkalib/partition/settings.go

Forgot to add YAML annotations from #505.

Adding yaml annotations to partitionFields

---

lib/destination/dml/merge_mssql_test.go

Must have broken when https://github.com/artie-labs/transfer/pull/501 was merged into master.

[mssql] Fix test

---

lib/destination/ddl/ddl_temp_test.go
lib/destination/dml/merge_parts_test.go
lib/destination/dml/merge_test.go
lib/typing/columns/columns_test.go
lib/typing/columns/wrapper_test.go

Will make the diff smaller when the time comes for https://github.com/artie-labs/transfer/pull/510/.

[snowflake] Use `uppercaseEscNames: true` for tests

---

lib/destination/ddl/ddl_temp_test.go
lib/destination/dml/merge_test.go
lib/sql/escape.go
lib/sql/escape_test.go
lib/typing/columns/columns_test.go
lib/typing/columns/wrapper_test.go

With the caveat that `UppercaseEscapedNames` is set to true.

[snowflake] Escape all columns that do not start with "__artie"

---

clients/bigquery/tableid.go
clients/mssql/tableid.go
clients/redshift/tableid.go
clients/snowflake/tableid.go
lib/sql/dialect.go
lib/sql/dialect_test.go
lib/sql/escape.go

The eventual goal is that each store will have a `.Dialect()` method on it, so this is the first step towards that.

[sql] Add `Dialect` structs

---

lib/destination/ddl/ddl_alter_delete_test.go
lib/destination/ddl/ddl_create_table_test.go
lib/destination/ddl/ddl_suite_test.go
lib/destination/dml/merge_test.go
lib/destination/dml/merge_valid_test.go
lib/typing/columns/columns_test.go

Continuation of https://github.com/artie-labs/transfer/pull/527

[snowflake] Use `UppercaseEscNames: true` for tests (redux)

---

clients/bigquery/bigquery.go
clients/bigquery/merge.go
clients/bigquery/merge_test.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/shared/merge.go
clients/shared/table_config_test.go
clients/shared/utils.go
clients/snowflake/snowflake.go
clients/snowflake/staging_test.go
clients/snowflake/writes.go
lib/destination/dwh.go

So that we don't have to pass `Config` to `shared.Merge` and `BackfillColumn`.

Add `AdditionalDateFormats` to `DataWarehouse`

---

lib/kafkalib/partition/settings.go

We are importing these structs from our dashboard. We need the JSON annotations or it will not get serialized correctly

Adding JSON annotations back

---

clients/shared/table_config_test.go
lib/mocks/generate.go
processes/consumer/process_test.go

Removing more mocks

---

processes/consumer/kafka.go

Adding jitter sleep when establishing new Kafka connections

---

go.mod
processes/consumer/kafka.go

MSK uses SHA 512 not plain auth

[Kafka] Enable SHA512 SCRAM

---

lib/kafkalib/consumer.go
processes/consumer/kafka.go

This PR: https://github.com/artie-labs/transfer/pull/611 is causing a deadlock in our Kafka consumer logic

Kafka Revert reload

---

clients/bigquery/dialect/dialect.go
clients/bigquery/dialect/dialect_test.go
clients/mssql/dialect/dialect.go
clients/redshift/dialect/dialect.go
clients/redshift/dialect/dialect_test.go
clients/snowflake/dialect/dialect.go
clients/snowflake/dialect/dialect_test.go
lib/sql/columns.go
lib/typing/columns/columns.go

No changes just moved these two functions.

[sql] Move `QuoteColumns` and `BuildColumnsUpdateFragment` to `sql`

---

clients/bigquery/dialect/dialect.go
clients/bigquery/dialect/dialect_test.go
clients/mssql/dialect/dialect.go
clients/mssql/dialect/dialect_test.go
clients/redshift/dialect/dialect.go
clients/redshift/dialect/dialect_test.go
clients/snowflake/dialect/dialect.go
clients/snowflake/dialect/dialect_test.go
lib/sql/columns.go
lib/sql/dialect.go

Factor out the `CASE` statement and rename to `BuildIsNotToastValueExpression`.

[sql] Clean up `BuildProcessToastColExpression`

---

clients/snowflake/dialect/dialect.go
clients/snowflake/writes.go

Added tests in https://github.com/artie-labs/transfer/pull/666 so it should be safe to change now.

[snowflake] Use `BuildColumnComparisons` for additional equality strings

---

clients/shared/append.go
lib/destination/types/types.go

Instead of always excluding it, this PR adds a flag for callers to determine whether we should exclude this column or not

[Append] Exclude Deleted Column

---

lib/config/constants/constants.go

Make `TableAlias` a type definition

---

lib/debezium/schema.go
lib/debezium/schema_test.go
lib/debezium/types.go
lib/debezium/types_test.go

Adding support for `NanoTime` and `NanoTimestamp` for SQL Server

Adding Additional Data Types for SQL Server

---

clients/mssql/store_test.go
clients/mssql/tableid.go
clients/mssql/tableid_test.go

Quote Microsoft SQL Server schema.

---

lib/array/strings.go
lib/array/strings_test.go
lib/config/config.go
lib/kafkalib/topic.go
models/event/event.go

We have two of the same function.

Replace `array.Empty` with `stringutil.Empty`

---

Makefile
lib/typing/mongo/bson_bench_test.go

So we are able to see the performance difference between what we have and this PR: https://github.com/artie-labs/transfer/pull/701

Adding a benchmark file for JSONEToMap

---

lib/artie/message.go
processes/consumer/process.go

This will give us similar information without creating additional custom metrics

Removing certain Datadog tags

---

clients/bigquery/dialect/dialect.go

https://github.com/artie-labs/transfer/pull/726#discussion_r1643191933

[BigQueyr] Add a comment to dedupe

---

clients/bigquery/storagewrite.go

With https://github.com/artie-labs/transfer/pull/750 I don't think this case is possible anymore.

[bigquery] Log if we get an `int` for a `typing.Integer` column

---

lib/config/config.go
processes/consumer/kafka.go

Following PR from https://github.com/artie-labs/reader/pull/434

[Kafka] Provide the option to disable TLS

---

clients/snowflake/dialect/dialect_test.go

This test was using a subquery which snowflake doesn't do, so it was unrealistic and hard to read

Clean up test

---

clients/mssql/dialect/dialect_test.go

Same as https://github.com/artie-labs/transfer/pull/792; MS SQL doesn't use subqueries either

Remove subquery from MS SQL dialect test

---

clients/bigquery/storagewrite.go
clients/bigquery/storagewrite_test.go

We have not seen these in our logs, so let's remove it.

Removing TODOs

---

lib/typing/columns/diff_test.go
models/event/event_save_test.go
models/event/event_test.go
processes/consumer/flush_test.go

Followup to https://github.com/artie-labs/transfer/pull/796 - more test coverage

Add OnlySetDeleteColumnMarker to all tests that use DeleteColumnMarker

---

clients/shared/table_config.go
clients/snowflake/ddl_test.go
clients/snowflake/snowflake_test.go
clients/snowflake/staging_test.go
lib/destination/ddl/ddl_alter_delete_test.go
lib/destination/ddl/ddl_bq_test.go
lib/destination/ddl/ddl_create_table_test.go
lib/destination/ddl/ddl_sflk_test.go
lib/destination/ddl/ddl_temp_test.go
lib/destination/types/types.go
lib/destination/types/types_test.go
lib/optimization/table_data.go

Renaming `tableConfig` -> `tableConfigCache`

---

clients/bigquery/dialect/dialect_test.go
clients/mssql/dialect/dialect.go
clients/mssql/dialect/dialect_test.go
clients/mssql/values.go
clients/mssql/values_test.go
clients/redshift/cast.go
clients/redshift/cast_test.go
clients/redshift/dialect/dialect.go
clients/redshift/dialect/dialect_test.go
clients/redshift/redshift_bench_test.go
clients/snowflake/dialect/dialect.go
clients/snowflake/dialect/dialect_test.go
clients/snowflake/staging.go
clients/snowflake/staging_test.go
lib/optimization/event_update_test.go
lib/typing/typing.go

Refactor `OptionalStringPrecision` to be int32

---

clients/mssql/dialect/dialect.go
clients/mssql/dialect/dialect_test.go

Refactoring how we handle inserts and updates with soft deletion, to make it easier to add the new soft-delete behavior.
When soft delete is enabled, now we'll issue an `INSERT` statement + an `UPDATE` statement. When soft delete isn't enabled, we'll continue using the same `MERGE` statement as before.
This PR shouldn't change any behavior, it's just setting up for doing an alternative to https://github.com/artie-labs/transfer/pull/802.

Use separate insert & update statements instead of merge for MS SQL when soft delete is enabled

---

clients/bigquery/bigquery.go
clients/mssql/store.go
clients/redshift/queries.go
clients/redshift/redshift.go
clients/shared/table_config.go
clients/snowflake/snowflake.go

Taking some of the improvements made here: https://github.com/artie-labs/transfer/pull/700 and applying it here.
Don't want to merge #700 just yet, since it'll take additional follow ups to fully implement MSSQL default values.

Cleaning up Table Config

---

lib/cdc/event.go
lib/cdc/mongo/debezium.go
lib/cdc/mongo/debezium_test.go
lib/cdc/util/optional_schema.go
lib/cdc/util/relational_event.go
lib/cdc/util/relational_event_test.go
lib/debezium/schema.go
lib/debezium/types.go

Moving this closer to Debezium, no functional changes.

[Debezium] Move FieldLabelKind

---

lib/debezium/converters/time.go
lib/debezium/converters/time_test.go
lib/debezium/types.go
lib/debezium/types_test.go

1. Starting to stand up a `converters` pkg
2. Starting to pull logic out of the main `ParseValue` function, into smaller functions that are easier to unit test

[Debezium] Minor refactor around converters

---

clients/snowflake/snowflake.go
lib/config/config.go
lib/config/snowflake.go
lib/crypto/rsa.go

We currently only support username and passwords.
We're having more customers ask for a key based authentication now. This PR adds the ability to authenticate via private keys.

[Snowflake] Support authentication via private key

---

lib/debezium/converters/time.go
lib/debezium/converters/time_test.go
lib/debezium/types.go
lib/typing/ext/parse.go
lib/typing/ext/parse_test.go
lib/typing/ext/time.go
lib/typing/ext/variables.go

All the other time data types are already handled, it was just `TimeWithTimezone`

[Debezium] Native Time with timezone parsing

---

lib/debezium/converters/converters.go
lib/debezium/converters/geometry.go
lib/debezium/converters/geometry_test.go
lib/debezium/converters/time.go
lib/debezium/converters/time_test.go
lib/debezium/schema.go
lib/debezium/types.go

Creating parity with Reader, starting with 3 different types support.

[Debezium] Starting the valueConverter scaffold

---

lib/debezium/converters/basic.go
lib/debezium/converters/basic_test.go
lib/debezium/converters/geometry.go
lib/debezium/converters/geometry_test.go
lib/debezium/schema.go
lib/debezium/types.go
lib/jsonutil/jsonutil.go
lib/jsonutil/jsonutil_test.go

Moving Geography and JSON to follow the converters pattern

[Debezium] Adding Geography + JSON converters

---

clients/bigquery/bigquery.go
clients/bigquery/storagewrite.go
clients/shared/default_value.go
clients/shared/default_value_test.go
lib/crypto/rsa.go
lib/parquetutil/parse_values.go

Use more of the `typing.AssertType` function

[Typing] Use more assertions

---

clients/mssql/dialect/dialect.go
clients/mssql/queries.go
clients/mssql/store.go
clients/redshift/dialect/dialect.go
clients/redshift/redshift.go
clients/shared/sweep.go
clients/snowflake/dialect/dialect.go
clients/snowflake/snowflake.go

So we can reference this in different repos

Moving Sweep queries to Dialect

---

.github/workflows/gha-go-test.yml
Makefile
lib/destination/types/types_test.go
lib/telemetry/metrics/datadog/datadog_test.go
lib/telemetry/metrics/stats.go
lib/typing/columns/diff_test.go
lib/typing/mongo/bson_test.go

Fixing errors and adding `make vet`

Enabling go vet

---

lib/debezium/types_test.go

No functionality changes, just rewriting the tests

Rewriting tests

---

lib/cdc/util/optional_schema.go

Was addressed by https://github.com/artie-labs/reader/pull/473

Remove warning from optional schema

---

clients/s3/s3.go
clients/s3/s3_test.go
lib/config/config.go

Once this is merged, I'll release a new version and point dashboard at it so I can make the final updates there too.

Rename S3 `OptionalPrefix` to `FolderName` to match dashboard

---

.github/CODEOWNERS
lib/debezium/converters/time.go
lib/debezium/converters/time_test.go
lib/debezium/schema.go
lib/debezium/types.go
lib/debezium/types_test.go

Moving from the previous way of converting micro and nano seconds to the new converter style

[Debezium] Adding Nano and Micro Time converters

---

lib/debezium/schema_test.go

Refactor schema tests

---

lib/debezium/schema.go
lib/debezium/schema_test.go

[Debezium] Supporting more types

---

lib/debezium/types.go
lib/debezium/types_test.go

This PR is preparing this codepath for us to convert `KafkaDecimalType` and `KafkaVariableNumericType` into native converters.

[Debezium] Parse bytes in preprocessing layer

---

lib/debezium/converters/basic.go
lib/debezium/converters/basic_test.go
lib/debezium/schema.go
lib/debezium/schema_test.go
lib/debezium/types_test.go

Adding more coverage of all Debezium converters

[Debezium] Adding Year converter

---

lib/debezium/converters/basic.go
lib/debezium/converters/basic_test.go
lib/debezium/schema.go
lib/debezium/schema_test.go

Refactoring Year to be an Int64 Passthrough, and then adding support for MicroDuration as well.

[Debezium] Int64 Passthrough

---

lib/debezium/types.go
lib/typing/parse.go
lib/typing/parse_test.go

Warnings were added in #869, we have not seen any of these logs since we deployed.

[Typing] Simplify Parse Value

---

lib/debezium/converters/bytes.go
lib/debezium/converters/bytes_test.go
lib/debezium/converters/decimal.go
lib/debezium/converters/decimal_test.go
lib/debezium/types.go
lib/debezium/types_bench_test.go
lib/debezium/types_test.go

Moving files around and minor refactor to prepare for moving Decimal and VaraibleDecimal converter refactor

[Debezium] Prepping for Decimal refactor

---

lib/debezium/converters/decimal.go
lib/debezium/schema.go
lib/debezium/types.go
lib/debezium/types_bench_test.go
lib/debezium/types_test.go

First pass at standing up the Decimal converter

[Debezium] Standing up Decimal converters - Part one

---

lib/debezium/converters/basic.go
lib/debezium/converters/basic_test.go
lib/debezium/schema.go
lib/debezium/schema_test.go
lib/debezium/types.go
lib/debezium/types_test.go

Implementing the following:
* Bit (parsing as `[]byte` and returning b64 encoded string)
* Interval and XML string passthroughs

[Debezium] Implementing bits + other string types.

---

clients/s3/s3.go

Minor refactor for retrieving cols

Cleaning up S3

---

lib/optimization/table_data.go

So it's easier to spot in our logs search

Converting to warn.

---

lib/typing/mongo/bson_test.go

Refactor existing MongoDB tests + adding additional test cases for nested objects.

Improving our MongoDB tests

---

clients/snowflake/writes.go
lib/config/snowflake.go

Implementing this from: https://github.com/snowflakedb/gosnowflake/issues/738

[Snowflake] Fix idle auth error

---

lib/maputil/ordered_map.go
lib/maputil/ordered_map_test.go

So we can start to use ordered maps and case insensitive maps inside of Transfer.

Adding Ordered Map

---

lib/debezium/converters/time.go
lib/debezium/converters/time_test.go

[Debezium] Support ns precision

---

lib/config/config.go
lib/config/config_test.go
lib/kafkalib/topic.go
processes/consumer/process.go

Slight refactor of tests, string formatting and adding `primaryKeysOverride` to TopicConfig.

Adding `PrimaryKeysOverride` to TopicConfig + clean up

---

lib/cdc/mongo/debezium.go

I suspect this comment is no longer correct. Let's confirm that by adding a warning and if we don't see anything in our logs, then let's remove it!

[MongoDB] Adding warning before removing

---

.github/workflows/gha-go-test.yml
.github/workflows/go-checks.yml

Preempt https://github.com/actions/runner-images/issues/10636

github: pin Ubuntu version to `24.04`

---

README.md
clients/databricks/dialect/dialect.go
clients/databricks/dialect/dialect_test.go
clients/databricks/dialect/typing.go
clients/databricks/dialect/typing_test.go
clients/databricks/store.go
lib/config/constants/constants.go

1. Adding TOAST support
2. Add dedupe capabilities
3. Updating data type mapping to use `STRING` instead of `VARIANT`

[Databricks] Improve Dialect

---

processes/consumer/flush.go

Increasing the floor and bumping up the num attempts

Tweaking retries

---

clients/bigquery/bigquery.go
clients/databricks/store.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/snowflake/snowflake.go
lib/destination/dwh.go
lib/destination/utils/load.go
main.go

Adding `SweepTemporaryTables` to the destination interface

---

clients/databricks/dialect/dialect.go
clients/databricks/dialect/dialect_test.go

[Databricks] Adding tests to merge.

---

lib/debezium/converters/time.go
lib/debezium/converters/time_test.go
lib/debezium/schema_test.go

This PR is modifying another spot where we are calling `NewExtendedTimeDetails` and specifying the layout.

More refactor around NewExtendedTimeDetails

---

processes/consumer/kafka.go

So we can track down errors easier

Adding topic name to log fields

---

lib/optimization/table_data.go
lib/optimization/table_data_test.go
lib/typing/ext/time.go

Addresses TODO from: https://github.com/artie-labs/transfer/pull/979 + adding tests.

[ExtendedTime] Addressing TODO

---

clients/mssql/values.go
clients/mssql/values_test.go
lib/typing/values/string.go
lib/typing/values/string_test.go

I realized that after #990, I missed two potential spots to parse Date

Date - Fast follow

---

lib/cdc/mongo/debezium.go

Can remove this TODO as we have not seen this in Sentry.

Remove TODO.

---

clients/shared/table_config.go

I split building columns out of the main function so we can begin simplifying this function

Simplifying building columns from rows

---

clients/bigquery/merge.go
clients/bigquery/partition.go
clients/bigquery/partition_test.go
lib/optimization/table_data.go
lib/optimization/table_data_test.go

1. It doesn't need to be a function on `TableData`
2. It can be a private function since it's exclusively used by BigQuery
3. Rewrote tests

Refactor Distinct Dates

---

clients/mssql/dialect/ddl.go
clients/mssql/dialect/dialect_test.go

Same rationale as https://github.com/artie-labs/transfer/pull/1056

[MSSQL] Remove `buildAlterColumnQuery`

---

lib/debezium/schema.go
lib/debezium/types_test.go

`ItemsMetadata` is optional, we should annotate it as such.

[Debezium] ItemsMetadata is optional

---

clients/snowflake/dialect/dialect.go
clients/snowflake/dialect/dialect_test.go
lib/sql/tests/columns_test.go

Same rationale as https://github.com/artie-labs/transfer/pull/1077

[Snowflake] Better handling of TOAST columns

---

lib/cdc/util/relational_event.go

Making this more consistent with Debezium

[Debezium] Updating `Source` label

---

processes/consumer/configs.go

Additional log statement to let us know when we commit Kafka offset

Log Kafka offset

---

lib/typing/converters/string_converter.go
lib/typing/converters/string_converter_test.go
lib/typing/values/string.go

Migrating the last converter over

---

lib/typing/converters/string_converter.go
lib/typing/converters/string_converter_test.go
lib/typing/converters/util.go

Refactoring our Boolean string converter to handle different permutations of 0, 1, "true", "false"

Improving our Boolean string converter

---

clients/snowflake/staging.go
clients/snowflake/staging_test.go

We need to add a prefix of `%` to the table name

[Snowflake] Fix `BuildRemoveFilesFromStage`

---

clients/bigquery/converters/converters.go
clients/bigquery/converters/converters_test.go

Widen `Int64Converter`

---

clients/shared/append.go
clients/shared/merge.go
lib/typing/columns/diff.go
lib/typing/columns/diff_test.go

This is also part of the refactor to support multi-step merge.
We'll need to call `columns.Diff` for merging into the intermediary staging table.

Refactor `columns.Diff` into `columns.DiffAndFilter`

---

clients/snowflake/dialect/tableid.go
clients/snowflake/snowflake.go
clients/snowflake/snowflake_test.go
lib/destination/types/types.go

Follows #1118
The intent of this PR is to reduce the main PR https://github.com/artie-labs/transfer/pull/1108 into PRs that are easier to review.
This specific PR implements drop table for Snowflake.

[Snowflake] Implement drop table

---

lib/destination/ddl/expiry.go
lib/destination/ddl/expiry_test.go

This will reduce Sentry noise.

Patching `ShouldDeleteFromName` for MSM

---

clients/bigquery/bigquery.go
clients/databricks/store.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/shared/append.go
clients/shared/default_value.go
clients/shared/merge.go
clients/shared/multi_step_merge.go
clients/shared/sweep.go
clients/shared/table.go
clients/shared/table_config.go
clients/shared/table_config_test.go
clients/snowflake/snowflake.go
lib/destination/ddl/ddl.go
lib/destination/ddl/ddl_temp_test.go
lib/destination/destination.go
lib/destination/utils/load.go
lib/mocks/generate.go
main.go
processes/consumer/flush_suite_test.go
processes/consumer/flush_test.go

Renaming it so that we can align closer to source and destination. We also have plans to support non-DWH destinations.

Renaming DWH -> Destination

---

clients/shared/table_config.go

If the column comments are being for other purposes, let's not try to overwrite the comment with our backfill strategy.
Marking it as backfilled will allow us to not mutate the column comments.

[Default values] Handle column comments better

---

clients/redshift/staging.go
clients/s3/s3.go
lib/awslib/s3.go

Renaming this directory so that we can put more S3 dependencies within this package without creating more.

Rename awslib -> s3lib.

---

clients/iceberg/dialect/data_types.go
clients/iceberg/dialect/data_types_test.go
lib/typing/decimal/details.go

This series of PRs is aimed to support Apache Iceberg as a destination. The main PR can be found here: https://github.com/artie-labs/transfer/pull/1133
This particular PR is filling out Artie and Iceberg type converters + tests.

Supporting Iceberg - Part 2

---

clients/iceberg/dialect/dialect.go
clients/iceberg/store.go
lib/apachelivy/client.go
lib/config/constants/constants.go
lib/config/destination_types.go
lib/config/types.go
lib/destination/utils/load.go

This PR adds a basic scaffold that implements `Baseline` and additional implementations around our dialect.

Supporting Iceberg - Part 5

---

clients/redshift/staging.go
lib/csvwriter/gzip.go
lib/csvwriter/gzip_test.go

Adding a library around creating GZIP CSV files so that we can reuse this for Iceberg.

Adding a GZIP CSV writer

---

clients/iceberg/dialect/data_types.go
clients/iceberg/dialect/data_types_test.go
clients/iceberg/dialect/dialect_test.go
clients/iceberg/store.go
clients/iceberg/table.go
lib/apachelivy/client.go
lib/apachelivy/schema.go
lib/apachelivy/schema_test.go
lib/apachelivy/types.go

1. Adding support for Describe table
2. Carrying changes over from the dialect to reduce the diff

Supporting Iceberg - Part 6

---

clients/iceberg/dialect/dialect.go
clients/iceberg/staging.go
clients/iceberg/store.go
clients/iceberg/table.go
lib/apachelivy/types.go
lib/config/constants/constants.go

This PR is adding basic support for the `Append` method

Supporting Iceberg Part 7 - Supporting `Append`

---

clients/bigquery/dialect/dialect.go
clients/databricks/dialect/dialect.go
clients/mssql/dialect/dialect.go
clients/snowflake/dialect/dialect.go

Reducing Dialect boilerplate

---

clients/redshift/dialect/dialect.go
clients/redshift/dialect/dialect_test.go
clients/redshift/staging.go

This is the first PR that moves the existing copy logic into a function so we can unit test it.
Once this is merged, I'll improve the way we handle null values.

[Redshift] Moving COPY into `Dialect`

---

README.md
clients/iceberg/dialect/dialect.go
clients/iceberg/dialect/dialect_test.go
clients/iceberg/store.go
clients/snowflake/dialect/dialect.go

As per title -- this is the last part in having a functional Iceberg destination!

[Iceberg] Implementing DEDUPE

---

clients/databricks/dialect/dialect.go
clients/databricks/dialect/dialect_test.go
clients/databricks/store.go

[Databricks] Move COPY INTO as a Dialect function

---

clients/databricks/dialect/dialect.go
clients/databricks/dialect/dialect_test.go
clients/databricks/store.go

Use Artie null value constant and avoid having to worry about escaping

[Databricks] Improve null values handling

---

clients/databricks/dialect/dialect.go
clients/databricks/dialect/dialect_test.go
clients/databricks/file.go
clients/databricks/file_test.go
clients/databricks/store.go

Using the same gzip writer that was added from: https://github.com/artie-labs/transfer/pull/1144

Databricks to use GZIP

---

clients/redshift/redshift.go
lib/environ/environment.go
lib/environ/environment_test.go

Adding an `environ` package and addressing TODO

---

Makefile
integration_tests/snowflake/main.go

This PR adds a manual integration test to test Snowflake APPEND

[Snowflake] Adding a manual integration test

---

clients/shared/default_value_test.go

Rewriting default value tests to be block-based for consistency and readability.

Refactor Default Value Tests

---

clients/snowflake/snowflake_test.go
clients/snowflake/staging.go
clients/snowflake/staging_test.go

As per title, and fixing tests.

[Snowflake] Use `ExecContext` more

---

clients/snowflake/snowflake_test.go

Rewriting some Snowflake tests to test the entire statements

[Snowflake] Rewrite some tests

---

clients/snowflake/dialect/dialect.go
clients/snowflake/dialect/dialect_test.go
clients/snowflake/staging.go

So we can unit test and reuse it more.

[Snowflake] Move COPY into the dialect pkg

---

clients/bigquery/merge_test.go
clients/mssql/staging.go
lib/sql/tests/columns_test.go
lib/typing/columns/diff_test.go

* Using `ExecContext` for MSSQL
* Rewrite more tests to follow be block style.

Use `ExecContext` more and rewrite more tests

---

.goreleaser.yaml
build/build.go
lib/logger/log.go
main.go

Reverts artie-labs/transfer#1220
Doesn't do what I wanted it to do.

Revert "Export build version"

---

lib/parquetutil/parse_values.go
lib/parquetutil/parse_values_test.go
lib/typing/converters/primitives/converter.go
lib/typing/converters/primitives/converter_test.go

Addressing TODO from the Parquet PR and adding some tests.

Clean up around Parquet

---

Makefile
clients/mssql/store.go

Adding MSSQL Integration Tests + Implement DropTable

Adding MSSQL Integration Tests

---

clients/mssql/dialect/dialect.go
clients/mssql/dialect/merge_test.go

Making merge operations more modular for MSSQL

[MSSQL] Pull merge operations into subfunctions

---

processes/consumer/flush_suite_test.go
processes/consumer/flush_test.go

Doing this to reduce the diff for https://github.com/artie-labs/transfer/pull/1236

Refactoring flush test

---

clients/databricks/store.go
clients/mssql/store.go
clients/redshift/redshift.go
clients/shared/sweep.go
clients/snowflake/snowflake.go
lib/db/db.go
lib/destination/destination.go

As per title, this allows us to cancel queries with context

[Sweep] Use QueryContext instead of Query

---

clients/redshift/staging.go
lib/db/db.go

Using the [pg_last_copy_count()](https://docs.aws.amazon.com/redshift/latest/dg/PG_LAST_COPY_COUNT.html) to assert how many rows were written to Redshift

[Redshift] Assert Staging Table's RowsAffected

---

clients/mssql/staging.go

Same logic as the previous PR, this will add an extra guardrail for append and staging tables.

[MSSQL] Assert rows affected in `PrepareTemporaryTable`

---

clients/snowflake/dialect/ddl.go
clients/snowflake/dialect/dialect.go
clients/snowflake/snowflake.go
clients/snowflake/snowflake_suite_test.go
clients/snowflake/staging.go
lib/config/destination_types.go
lib/csvwriter/gzip.go
lib/csvwriter/gzip_test.go
lib/destination/ddl/ddl_suite_test.go
lib/destination/utils/load.go
lib/kafkalib/topic_test.go

This PR adds the ability for folks to opt to use Snowflake's external stage as opposed to internal table stages.

[Snowflake] Use External Stage

---

clients/iceberg/store.go
lib/awslib/s3tablesapi.go
lib/awslib/types.go
lib/config/destination_types.go

1. Adding the ability to specify additional session configs
2. Extending `S3TablesAPI` to retrieve table bucket and table metadata

Extending S3Tables functionality

---

clients/iceberg/staging.go
clients/iceberg/store.go
clients/iceberg/table.go
go.mod
lib/awslib/s3tablesapi.go

Final tweaks to get Iceberg to run in K8s

Final Tweaks for Iceberg

---

clients/iceberg/store.go
lib/apachelivy/client.go
lib/apachelivy/types.go
lib/config/destination_types.go

Setting the default session timeout to be 5 min so that Livy server's GC can kick in and clean up orphaned sessions

[S3Tables] Adding additional touches

---

clients/iceberg/dialect/dialect.go
clients/iceberg/store.go

* Sweep temporary tables
* Lowercase identifier columns

[Iceberg] Implementing Sweep Temporary Tables + Standardize Identifiers

---

clients/redshift/cast.go
clients/redshift/cast_test.go
lib/debezium/converters/basic.go
lib/debezium/converters/basic_test.go
lib/debezium/converters/date.go
lib/debezium/converters/date_test.go
lib/debezium/schema.go
lib/debezium/types_test.go

Array Elements may be nested, so we should be parsing them accordingly.

[Debezium] Better Array Handling

---

lib/kafkalib/topic.go
lib/kafkalib/topic_test.go
models/event/event.go
models/event/event_test.go

By specifying column inclusion, this instructs Transfer to only include columns specified as columns to include.

Adding Column Inclusion

---

lib/config/constants/constants.go
models/event/event.go
models/event/event_test.go

As the title suggests, we shouldn't be discarding the internal columns that make Transfer functional

Column Inclusion to not disregard internal columns

---

Makefile
integration_tests/destination_merge/main.go
integration_tests/shared/framework.go
lib/debezium/converters/basic_test.go

Our integration test is now checking `JSON` and `JSON[]` for the MERGE operation. Once this is in, I'll add the same for APPEND.

Merge Integration test to test `JSON` and `JSON[]`

---

lib/debezium/schema.go
lib/debezium/types.go
lib/debezium/types_test.go

INT8 is something that Oracle can produce

[Debezium] Supporting INT8

---

clients/shared/default_value.go

Ability to disable column default value backfill based on env var

Disable column default value backfills

---

lib/apachelivy/client.go
lib/apachelivy/types.go

Adding this here so that we can then embed this into our dashboard and have a periodic job that will clean up sessions in a terminal state

[Livy] List + Delete Sessions

---

Makefile
integration_tests/destination_merge/main.go
integration_tests/shared/checker.go
integration_tests/shared/framework.go

Considering the following edge cases for structs:
1. Strings in Structs
2. Booleans in Structs
3. Numbers in Structs

Adding structs to our integration tests

---

lib/typing/converters/string_converter.go
lib/typing/converters/string_converter_test.go
lib/typing/ext/parse_test.go
lib/typing/ext/variables.go

* Account for STRING floats
* Account for an additional timestamp format

Widen Converters

---

lib/cdc/util/relational_event.go

Creating a function where we can skip processing default values where it's a formula and not an actual value.

Skip processing invalid default values

---

Makefile
clients/iceberg/dialect/dialect.go
clients/iceberg/dialect/dialect_test.go
integration_tests/destination_append/main.go
integration_tests/destination_merge/main.go
integration_tests/shared/baseline.go
integration_tests/shared/checker.go
integration_tests/shared/destination.go
integration_tests/shared/framework.go
lib/apachelivy/client.go
lib/apachelivy/schema.go
lib/apachelivy/schema_test.go
lib/apachelivy/types.go
lib/apachelivy/util.go

1. Adding Iceberg to our append integration tests
2. Integration test revealed that we are trimming the first row from our delta file
3. Adding `omitempty` to our Livy session JSON annotations
4. Adding a `shouldRetry` wrapper function to move away from `retry.AlwaysRetry`

Iceberg Improvements

---

lib/apachelivy/client.go
lib/apachelivy/session.go

1. Moving all the session logic into `session.go`
2. I then added logic to force check the session if the attempt is greater than zero.
For [2], we used to have a guardrail where if the session was last checked within the last 5 min, it would skip this check. Now we will force a session check if the attempt is greater than zero.

[Livy] Solving for 500s

---

clients/snowflake/snowflake.go
clients/snowflake/staging.go
lib/awslib/s3.go

Migrating Snowflake to use the new S3 client and then removing the old function.

Snowflake External Stage to Use S3 Client

---

.github/workflows/parquet-checks.yml

Adding Parquet to our GHA checks

Adding Parquet to GHA checks

---

clients/databricks/dialect/dialect.go
clients/databricks/dialect/dialect_test.go
clients/databricks/store.go

Let's be explicit about the columns we are trying to load data into and not rely on positions, since the position may change and it's brittle.

Fixing Databricks

---

clients/iceberg/store.go
clients/shared/append.go
clients/shared/merge.go
clients/shared/multi_step_merge.go
lib/optimization/table_data.go
lib/optimization/table_data_test.go
lib/typing/columns/diff.go
lib/typing/columns/diff_test.go

This way, we don't have to pass around a bunch of variables and we can just generate the list of columns we want to keep and pass it to `DiffAndFilter`

Standing up `BuildColumnsToKeep`

---

clients/bigquery/dialect/typing.go
clients/bigquery/dialect/typing_test.go
clients/databricks/dialect/typing.go
clients/databricks/dialect/typing_test.go
clients/iceberg/dialect/data_types.go
clients/iceberg/dialect/data_types_test.go
clients/iceberg/table.go
clients/mssql/dialect/typing.go
clients/mssql/dialect/typing_test.go
clients/redshift/dialect/typing.go
clients/redshift/dialect/typing_test.go
clients/shared/table_config.go
clients/snowflake/dialect/typing.go
clients/snowflake/dialect/typing_test.go
integration_tests/shared/destination_types.go
integration_tests/shared/destination_types_mssql.go
lib/sql/dialect.go

We no longer rely on string precision, so we can simplify the signature!

Simplify Dialect Signature

---

clients/shared/multi_step_merge.go
clients/snowflake/writes.go
lib/optimization/table_data_test.go

This PR cleans up some of our MSM implementation

Minor refactor around MSM

---

clients/bigquery/dialect/dialect.go
clients/databricks/dialect/dialect.go
clients/iceberg/dialect/dialect.go
clients/mssql/dialect/dialect.go
clients/redshift/dialect/dialect.go
clients/shared/multi_step_merge.go
lib/sql/dialect.go

This PR is adding the scaffold so that we can build MSM support into Redshift

Update Dialect Signature

---

lib/heartbeats.go
lib/heartbeats_test.go
lib/maputil/map.go
lib/mocks/generate.go

Adding a centralized util for heartbeat. We will start to apply this to merge and append so that we can monitor for deadlocks!

Heartbeat detection + minor clean up

---

lib/cdc/event.go
lib/cdc/mongo/debezium.go
lib/cdc/util/relational_event.go
lib/config/constants/constants.go
lib/kafkalib/topic.go
lib/optimization/table_data.go
lib/optimization/table_data_test.go
lib/typing/columns/diff_test.go
models/event/event.go

Support including extra column for source metadata

---

clients/shared/merge.go

This will start to kick in after 30 mins and log every 2 mins in duration.

Adding heartbeats logging

---

clients/iceberg/table.go
clients/shared/table.go
clients/snowflake/ddl_test.go
lib/cdc/event.go
lib/cdc/mongo/debezium.go
lib/cdc/mongo/event.go
lib/cdc/util/relational_event.go
lib/config/constants/constants.go
lib/destination/types/table_config.go
lib/destination/types/table_config_test.go
models/event/event.go
processes/consumer/process.go

Adding a type for Operation so it's more consistent across our codebase, instead of trying to match on string literals

Adding Operation Type

---

clients/bigquery/storagewrite.go
clients/databricks/store.go
clients/mssql/values.go
clients/shared/table_config.go
lib/array/strings.go
lib/batch/batch.go
lib/cdc/mongo/debezium.go
lib/cdc/util/relational_event.go
lib/debezium/converters/basic.go
lib/debezium/converters/bytes.go
lib/debezium/converters/date.go
lib/debezium/converters/decimal.go
lib/debezium/converters/geometry.go
lib/debezium/converters/time.go
lib/debezium/keys.go
lib/debezium/schema.go
lib/destination/types/table_config.go
lib/destination/types/types.go
lib/kafkalib/topic.go
lib/maputil/ordered_map.go
lib/typing/assert.go
lib/typing/columns/columns.go
lib/typing/columns/diff.go
lib/typing/parse.go
models/event/event.go
processes/consumer/configs.go
processes/consumer/process.go

Renaming the rest of the files

Renaming everything from `isOk` to `ok`

---

models/event/event.go
models/event/event_save_test.go
models/event/event_test.go
processes/consumer/process.go

Making this private so that we have a centralized place for setting these values.

Making attributes on the event private

---

clients/iceberg/store.go
lib/apachelivy/client.go
lib/config/destination_types.go

https://trello.com/c/6KafAzHq/1783-livy-session-resource-fix

[Livy] Add session name to Apache Livy client and Iceberg config

---

lib/apachelivy/session.go
lib/apachelivy/types.go

Task: https://trello.com/c/6KafAzHq/1783-livy-session-resource-fix
- Add session name to `CreateSessionRequest` and `GetSessionResponse`
- Implement `FindOrCreateSession()`
Todo:
- Replace usages of `newSession()` with `FindOrCreateSession()`
#Why Changes are Needed
Design doc: https://docs.google.com/document/d/1uzlVkFF1QHvwAcJn6jgoktGr00cNnaca_4FW5Co69Ns/edit?usp=sharing

[Livy] Implement session sharing

---

clients/postgres/dialect/dialect.go
clients/postgres/dialect/tableid.go
clients/postgres/postgres.go
lib/config/constants/constants.go
lib/config/destination_types.go
lib/config/destinations.go
lib/config/types.go
lib/destination/utils/load.go
lib/sql/dialect.go

This PR is adding the scaffold for Postgres as a destination. Once this is merged in, we can then incrementally implement these methods.

[Postgres] Adding the scaffold

---

.github/workflows/integration-tests.yaml
Makefile
clients/postgres/dialect/dialect.go
clients/postgres/postgres.go
clients/shared/table.go
integration_tests/postgres/checks/dialect.go
integration_tests/postgres/docker-compose.yaml
integration_tests/postgres/main.go

1. Adding Postgres integration test
2. Implementing some methods on the dialect

Adding PG Integration Tests

---

clients/postgres/dialect/dialect.go
integration_tests/postgres/checks/dialect.go
integration_tests/postgres/main.go

Implementing and testing the following methods on the Postgres dialect:
1. Create table
2. Drop table
3. Truncate table

[postgres] More dialect methods being implemented

---

clients/postgres/dialect/dialect.go
clients/postgres/dialect/dialect_test.go
lib/typing/typing.go

There may be more, but this is to get started.

[postgres] Implementing `KindForDataType`

---

clients/postgres/dialect/dialect.go
clients/postgres/postgres.go
integration_tests/postgres/checks/dialect.go

Implementing sweep temporary tables and adding a CI check.

[postgres] Implement sweeping temporary tables

---

README.md
clients/postgres/dialect/dialect.go
clients/postgres/dialect/merge_test.go
clients/postgres/postgres.go
clients/shared/default_value.go
clients/shared/table_config.go
integration_tests/postgres/checks/dialect.go
integration_tests/postgres/checks/merge.go
integration_tests/postgres/main.go
lib/sql/dialect.go

Implementing the various dialects and adding integration tests.

[postgres] Working prototype

---

clients/shared/merge.go
lib/destination/types/table_config.go
lib/destination/types/table_config_test.go

Removing unnecessary bloat from the critical path, I've outlined my reasoning for deleting the code with comments in the specific codepaths

Simplifying Transfer

---

clients/postgres/staging.go
lib/config/destination_types.go
lib/config/destinations.go

Widen data types and also make it so that we can use this locally

[postgres] Widen data type support + SSL

---

clients/postgres/dialect/dialect.go
clients/postgres/dialect/dialect_test.go

Just create all int columns as bigint

[Postgres] Fix int typing

---

lib/kafkalib/topic.go

Splitting Layout and Suffix out into separate functions so we can reuse

Refactoring PartitionFrequency

---

e2e_tests/postgres/test.go

Not changing the functionality, just changing the coding style to be more idiomatic and easier to read

Refactoring Integration Tests

---

clients/iceberg/store.go
clients/s3/s3.go
clients/s3/s3_test.go
clients/shared/merge.go
lib/cdc/event.go
lib/optimization/table_data.go
models/event/event.go

Doing some clean up on `TableData` so that we can prepare for a more efficient storage backend

Renaming `LatestCDCTs` => `LatestTimestamp` + making it private
