artie-labs/transfer

- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
Within Transfer, we have 2 table structures.
One is created as we consume events. This is used so that we can overlay DDL support on top of consuming CDC messages (this is called `tableData`).
The other one comes from DWH, where we can query and find out what the current table structure looks like (this is called `tableConfig`)
Whenever `tableData` and `tableConfig` disagree, we will try to rectify this by updating DWH.
Scenarios:
1) Adding a new column (supported)
2) Deleting a column (supported with the 2 phase check)
3) Modifying a column type (this is considered a breaking change and **NOT** supported)
When we invoke `MERGE`, we have a safety check to not merge columns where the type is `Invalid`. This is fine, but we're passing `tableData` as a column to `MERGE`. Normally, this is …
> [DDL] Edge case around typing

- README.md
- examples/postgres/connect/connect-distributed.properties
- lib/array/strings.go
- lib/cdc/event.go
- lib/cdc/postgres/debezium.go
- lib/cdc/postgres/debezium_test.go
- lib/cdc/postgres/event.go
- lib/debezium/types.go
- lib/debezium/types_test.go
- processes/kafka/consumer.go
With this PR, we are now requiring schemas to be turned on. The decision to turn this on has been a few factors.
1) When Debezium runs (and if others in this case) - it is reasonable to expect that they have their own interim data types.
2) Without schema support and understanding of interim data types, we will be passing the library complexity down to our users.
The issue here arose when I was testing the `TIMESTAMP WITHOUT TIME ZONE` data type in Postgres. Researching more, as you can see from the [Debezium documentation](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-temporal-types)
Steps required prior to merge:
> [Schema support for Postgres] Supporting TS w/o TZ for Postgres

- clients/snowflake/merge.go
- clients/snowflake/merge_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- lib/optimization/event.go
- lib/typing/diff.go
- lib/typing/diff_test.go
- models/memory.go
- models/memory_test.go
There's a type casing problem between downstreams apps and JSON.
Imagine the following scenario:
1) `name`
2) `NAME`
3) `NAmE`
4) `NamE`
JSON will treat these as **four** distinct values.
DWH will normalize this (Snowflake will UPPERCASE and BigQuery will LOWERCASE) into `name`, thus 1 value.
Fix here is to remove redundant lowercasing AND be more cognizant around case sensitive operations.
> [Bug] Fix typecasing problem.

- clients/bigquery/merge.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
We were not swapping `tableConfig.Columns()[strings.ToLower(inMemCol)]` with `tableData.InMemoryColumns` if exists.
The data from `tableConfig` is considered SOT.
> Bug around column typing

- README.md
- clients/bigquery/merge.go
- clients/snowflake/snowflake.go
- examples/postgres/config.yaml
- lib/cdc/event.go
- lib/cdc/format/format.go
- lib/cdc/format/format_test.go
- lib/cdc/mongo/debezium.go
- lib/cdc/postgres/debezium.go
- lib/config/constants/constants.go
- lib/optimization/event.go
- lib/optimization/event_test.go
- lib/typing/typing.go
In this PR, we will be doing the following:
1) Remove `wal2json` as a limitation for PostgreSQL replication slot plug-in. We've tested `pgoutput` and `decoderbufs` in addition to `wal2json`. All of which are supported.
2) Adding additional test coverage around BQ merge
> Clean up and remove wal2json limitation

- .gitignore
- .goreleaser.yaml
- Makefile
- README.md
- goreleaser.dockefile
- goreleaser.dockerfile
Integrating with `.goreleaser` so we can have a streamline way to release builds.
> Adding .goreleaser

- lib/cdc/mongo/debezium_test.go
- lib/cdc/postgres/debezium.go
- lib/cdc/postgres/debezium_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/typing/typing.go
We were previously only relying on the `JSON` library for parsing Kafka messages to determine typing. As you can see from https://github.com/golang/go/issues/56719
[RFC 8259](https://www.rfc-editor.org/rfc/rfc8259#section-3):
> A JSON value MUST be an object, array, number, or string, or one of the following three literal names:
> * false
> * null
> * true
> There is only number, but not int or float in JSON.
Previous PR added schema support within the message and this PR builds on top of this for PostgreSQL by being able to detect if the specified field is an integer. 
If so, it will typecast within `GetData(...)` and ensure that Transfer's typing library correctly labels the said value as an integer.
> [Enhancement] Improving typing for PostgreSQL

- clients/bigquery/merge.go
- clients/snowflake/merge.go
- clients/snowflake/snowflake.go
- lib/array/strings.go
- lib/config/config_test.go
- lib/dwh/dml/merge.go
- lib/dwh/dml/merge_test.go
- lib/kafkalib/topic.go
- lib/typing/diff.go
- lib/typing/diff_test.go
- models/flush/flush.go
Right now, Transfer's handling of DML is that it will delete the rows in the destination if the rows have been deleted in the source.
This PR adds an ability to soft delete the row by adding a column: `__artie_delete` (bool).
* If someone turns on soft deletion (off by default), it will add the column above.
* If the row is deleted and soft deletion is turned on, it will set `__artie_delete = true`
> [Enhancement] Adding the ability to toggle soft deletion

- clients/snowflake/merge.go
- clients/snowflake/merge_test.go
Opening this pull request to fix some issues I run into while setting up sync between PostgreSQL 12.11 and Snowflake.
Apologies if the tests look weird, I'm not familiar with Golang, so I just followed the pattern I saw in the existing test file.
Basically I saw 2 scenarios when the generated SQL code contained syntax errors:
1. When a text column in the database table contains HTML code that contains escaped javascript code (ie. data got in the DB during penetration testing for XSS attacks)
2. When a JSON column in the database table contains a string value that contains a `"` symbol
> Fix HTML code in string column and double quote in JSON data

- clients/bigquery/merge.go
- clients/snowflake/merge.go
- lib/stringutil/strings.go
Follows up from https://github.com/artie-labs/transfer/pull/49, to fix BQ.
Also pulled this into a separate utility function
> Escape strings correctly for BQ

- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/postgres/debezium.go
- lib/cdc/postgres/debezium_test.go
- models/event.go
- models/event_test.go
Previously, we were fetching the table name from within the message payload itself. Now, we are fetching it directly from the config file.
We are doing this so that we can support Kafka tombstones (the message will be null, so we will not be able to derive the name from there).
This should be a relatively minor change - however, the in-memory database will now store the table with the table name derived from the destination vs. src.
Scenario #1 - My source table is called `orders` and the table in Snowflake is called `PREFIX_orders`. Our in-memory DB will be saving data against `PREFIX_orders`.
Scenario #2 - Both table names are the same, no changes.
> Swap where we source table name from

- clients/snowflake/snowflake.go
- lib/cdc/mongo/debezium.go
- lib/cdc/postgres/debezium.go
- models/memory.go
- models/memory_test.go
- processes/kafka/process_test.go
In this PR, we are adding support for Kafka tombstones.
This allows users to leverage Kafka tombstone + compaction to optimize performance even further.
Motivation and considerations linked [here](https://docs.google.com/document/d/1ApCs6EewoIlUUHkJGDAJLOs7f13AyB2AhuAAk020FJM/edit?usp=sharing)
> Handling Kafka Tombstones

- clients/snowflake/snowflake.go
This defaults to `false` and after about a period of inactivity (about 4 hours), Snowflake will request you to restart your client.
Docs: https://docs.snowflake.com/en/sql-reference/parameters#client-session-keep-alive
You can enable it at the Snowflake session level as per [blog post](https://community.streamsets.com/share-your-best-practices-6/snowflake-file-uploader-is-failing-with-authentication-token-has-expired-the-user-must-authenticate-again-error-when-pipeline-is-idle-for-long-time-1226), but that requires additional configuration from our customers.
Instead, we will re-issue a new request upon an inactive session.
> [Snowflake] Turning on session keep alive

- lib/stringutil/strings.go
- lib/stringutil/strings_test.go
- lib/telemetry/metrics/datadog.go
This is needed because to send metrics within Kubernetes, we need to inject `status.HostIP` as an env var.
Transfer currently expects the address to be set within `config.yaml` which is being inserted as a `configMap` which is pod agnostic.
This PR allows us to override the Telemetry address by passing both variables: `TELEMETRY_HOST` & `TELEMETRY_PORT`.
> [Telemetry] Allowing env vars to override config

- lib/stringutil/strings.go
- lib/stringutil/strings_test.go
- models/memory.go
As mentioned in the comments, certain destinations do not handle spacing well (or at all).
Snowflake handles it, if we escape it correctly. However, BigQuery does not accept any spaces within column names.
In order to provide an easy-to-use interface, we will escape all spaces within a column name by adding `__` (double underscores).
This way, columns that have been escaped do not get mistaken with genuine columns that have underscore e.g. `column_a` vs `column a`. This also provides a way for customers downstream to replace double underscores with space.
Depending on feedback, we can also provide this as a configurable option.
> [Bug] Fix spacing

- clients/snowflake/snowflake.go
- models/memory.go
As a follow up to https://github.com/artie-labs/transfer/pull/31, right now if the source has the following object:
```json
{
"Item Name": "Foo",
"Item name": "Foo"
}
```
Transfer will treat these as distinct columns and try to update the destination. However, the destination will error out since it normalizes all columns and ignores casing.
As a result, we'll now normalize the columns we receive so we don't get errors around duplicate columns.
> [Bug] Fix casing

- clients/snowflake/snowflake.go
- lib/config/config.go
When reading from host (e.g. `account_identifier.provider.region.snowflakecomputing.com`, we need to erase the region) since it will get appended.
> [Snowflake] Fixing DSN for custom host

- clients/snowflake/merge.go
- clients/snowflake/merge_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
With the previous PR: https://github.com/artie-labs/transfer/pull/57, we made it so that we would re-establish a session upon a failed execute.
However, other queries can fail. So we are now wrapping the whole merge function and will re-establish a connection upon any idle errors as a result of execution or query.
> [Snowflake] Fixing all inactive sessions

- lib/cdc/postgres/debezium.go
- lib/debezium/types.go
- lib/debezium/types_test.go
Debezium has different modes for handling time precisions, 
[Source](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-temporal-types)
* Adaptive (default)
* Adaptive microseconds (PostgreSQL only)
* Connect
We already supported adaptive, this PR will enable us to support the other two types to make it easier.
Database Type | Value | Notes |
-- | -- | --
DATE | INT32 | io.debezium.time.Date<br />Represents the number of days since the epoch.
TIME(1), TIME(2), TIME(3) | INT32 | io.debezium.time.Time<br />Represents the number of milliseconds past midnight, and does not include timezone information.
TIME(4), TIME(5), TIME(6) | INT64 | io.debezium.time.MicroTime<br />Represents the number of microseconds past midnight, and does not include timezone …
> Supporting additional Debezium time precision

- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
As per title.
Instead of parsing and returning MongoDB's Timestamp type as: `{"$timestamp": {"t": <t>, "i": <i>}}`
We are now parsing the Timestamp and returning the actual datetime string.
> [MongoDB] Native support for bson.Timestamp

- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
- clients/snowflake/merge.go
- clients/snowflake/merge_test.go
- lib/dwh/dml/merge.go
- lib/dwh/dml/merge_test.go
BigQuery cannot compare equality of two objects without having some typecasting to a STRING.
Transfer only does equality comparisons with primary keys which should not be JSON structs with the exception to MongoDB which may use `objectID`.
> BigQuery <> MongoDB equality fix

- README.md
- examples/pubsub_postgres/README.md
- lib/telemetry/README.md
2 changes.
1. `docs.artie.so/configurations` -> `docs/artie.so`
2.  Minor edits to use the new anchor links
> Updating links within documentation

- clients/bigquery/merge.go
- clients/snowflake/merge.go
- clients/snowflake/snowflake_test.go
- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/postgres/debezium_test.go
- lib/cdc/postgres/postgres_suite_test.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_test.go
- lib/typing/typing.go
- lib/typing/typing_bench_test.go
- lib/typing/typing_test.go
- models/event.go
- models/event_test.go
- models/memory.go
- models/memory_test.go
In this PR, we are modifying our typing library to be treat strings with more sophistication.
Today, our library will attempt to cast and support various date time string formats for a given value. if it correctly parses, we were previously casting it as a `extendedTime` object and storing that within our in-memory database.
However, there's an edge case where if the column type in the source database is a `STRING` type, but the actual value parses to a date time...we were **previously** incorrectly storing that as date time.
1. We now introduced an `optionalSchema` where we are inferring this directly from the Debezium Kafka message.
2. If the suspected column exists in the `optionalSchema`, we will not attempt to parse it.
3. Also applied the fix from …
> Adding optional schemas to our typing library + fixes array parsing bug

- clients/bigquery/merge.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- lib/optimization/event.go
- lib/typing/typing_bench_test.go
- models/memory.go
We were previously using a manual counter to see how many rows were in the in-memory database. However, this is unnecessary and error prone. Instead, let's do a `LEN()` on the in-memory database to figure out the length.
I tested this against a map of 15k rows and observed 0.9ns for each `LEN()` call
> Minor improvement - removing manual row counter

- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
BigQuery's MERGE does not like `NULL` as a value for the column string.
It ends up throwing an error, so we are now passing `''` instead.
> [BigQuery] NULL String typing fix for CTEs

- lib/config/config.go
- lib/config/config_test.go
Moving the BigQuery and Snowflake type definition out of the config struct and changing this to be a pointer.
We will be using this improvement to overlay shared destinations on-top of specific Transfer configs.
> [Config] BigQuery and Snowflake typing

- lib/cdc/postgres/debezium.go
- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/ext/variables.go
- lib/typing/typing_test.go
Debezium handles `Timestamp`, `Date` and `Time` all differently depending on your setup.
More specifically, `TIMESTAMP WITH TIMEZONE` is casted as a `STRING`. `TIMESTAMP WITHOUT TIMEZONE` whereas Debezium casts the latter as a DBZ datetype.
**What's the problem?**
Transfer supports 10 different time layouts and if any of them work, we were previously returning the first layout.
Well, if you have ms and/or ns precision, it will still "work" as in, getting casted to a more generic layout. However, we then lose precision.
We now have a stricter parsing rule where:
1) We take the original timestamp string
2) Take a layout that works, parse the `time.Time` we got from (1) and diff the strings
(2) would have not worked in the past because we lost ms precision. If the two outcomes both work, we …
> [Enhancement] Improve time ms precision for timestamp w/ time zone types

- go.mod
- lib/db/mock/db.go
- lib/jitter/sleep.go
- processes/consumer/kafka.go
- processes/consumer/pubsub.go
This is an optimization to make our flushes more efficient.
It is indeterministic on if the flush process will start before the `processMessage` function iterates.
Right now, `processMessage` will send a signal to `flush` and the flush process will ack it and acquire a lock.
However, it's not guaranteed and thus we may signal additional flushes and slow down throughput by flushing too prematurely.
Solution here is to add a low sleep jitter to allow the flush process to pick up the signal and acquire the lock, which prevents the `processMessage` process from saving more events into our in-memory database.
> [Enhancement] Adding jitter sleep after signaling flush

- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
As indicated by the comments in `parse.go`, the motivation of this is to expand zero-precision loss for parsing:
* datetime
* date
* time
values that can be in a wide variety of different layouts. 
This PR enhances from this: https://github.com/artie-labs/transfer/pull/84, where we provided this guarantee on a datetime object. Where we changed the function from: `give me a layout that works` to also consider if we should give that layout (since going from `YYYY-MM-DD HH-MM-SS:ms` to `YYYY-MM-DD` would a huge precision loss, but still pass the "give me a layout that works" check.)
However, there are many different ways to express `date` (YYYY-MM-DD, MM-DD-YYYY) and similarly with time (include ns, ms, etc).
This PR will test every single layout and early exit upon any exact matches.
If it …
> Adding zero-precision loss for parsing time.Time

- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
- clients/snowflake/merge.go
- clients/snowflake/merge_test.go
- clients/snowflake/snowflake_test.go
- lib/optimization/event.go
- lib/optimization/event_test.go
- models/flush/flush_test.go
- models/memory.go
- models/memory_test.go
- processes/consumer/process_test.go
As per title.
This is a pre-requisite for https://github.com/artie-labs/transfer/pull/89 since this PR is currently calculating the whole `tableData` object each time, which incurs ~5-50ms overhead per row which is unacceptable.
For context - the current row performance is about 0.5ms to 1ms to process.
This PR creates a sole entry point for folks to do any sort of mutation within our in-memory pool.
> Refactor TableData to hide `rowData`

- Makefile
- lib/config/config.go
- lib/config/config_test.go
- lib/optimization/event.go
- lib/optimization/event_bench_test.go
- lib/optimization/event_insert_test.go
- lib/optimization/event_test.go
- lib/size/size.go
- lib/size/size_bench_test.go
- lib/size/size_test.go
- main.go
- models/memory.go
- processes/consumer/process_test.go
Addresses https://github.com/artie-labs/transfer/issues/68
This is necessary because Snowflake and BigQuery both have their limits on how big (in kb) a request can be. Snowflake's API docs specify 1 MB [src](https://docs.snowflake.com/en/user-guide/query-size-limits)...but the actual limit is significantly higher.
Through this PR, I've tested 25 mb payloads without any issue. However, this does happen...especially for tables with TOAST columns. The current workaround is to just reduce the number of items from the `bufferRow` but that's not robust.
This PR will allow users to specify an additional merge rule, and our merge rules will now look like:
1. Flush interval time (default 10s)
2. Pool rows (default to 15k) - number of rows.
3. Pool size (default to 25 mb) - size of the in-memory …
> Flush rules to be cognizant of in-memory database size

- lib/config/config.go
- lib/config/config_test.go
- processes/consumer/kafka.go
Normally, you only need to specify one broker within the cluster to get access to the rest (also known as "bootstrap servers").
Problem is that during a maintenance window, a particular broker may be taken down or become unresponsive for a brief moment in time.
AWS recommends this:
>  3. Ensure clients are configured to use multiple broker connection strings. Having multiple brokers in a client’s connection string allows for failover if a specific broker supporting client I/O begins to be patched. For information about how to get a connection string with multiple brokers, see Getting the Bootstrap Brokers for an Amazon MSK Cluster [1].
Which is the impetus for this PR. We are also following the same [standard Kafka for accepting](https://kafka.apache.org/documentation/#producerconfigs_boot …
> [Enhancement] Parity with Kafka bootstrap.servers

- clients/bigquery/merge.go
- clients/snowflake/merge.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- lib/debezium/keys.go
- lib/optimization/event.go
- lib/optimization/event_test.go
- lib/typing/columns.go
- models/event/event.go
- models/event/event_save_test.go
- models/event/event_save_toast_test.go
- models/event/events_suite_test.go
- models/flush/flush_test.go
- processes/consumer/kafka.go
- processes/consumer/process.go
- processes/consumer/process_test.go
- processes/consumer/pubsub.go
TOAST stands for "The Oversized-Attribute Storage Technique" in PostgreSQL. It's a system that PostgreSQL uses to store large data values efficiently. PostgreSQL and Oracle have a hard limit of 8KB (this is the default page size, it can be increased up to 32KB at compile time) on the size of a single row of data. 
PostgreSQL and Oracle have an optimization for CDC such that if the column value did not get changed, it will simply emit a stub placeholder. Debezium returns that as “[__debezium_unavailable](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-toasted-values)”. One could change the replica identity, however that results in additional compute resources from the database.
Previously, Artie Transfer would just ignore this column as such:
For …
> Handling all edge cases with TOAST

- lib/typing/typing.go
- lib/typing/typing_test.go
- models/event/event.go
As per title.
Right now, we'll end up deferring the `nil` value as part of the `optionalSchema`.
However, we should actually be early escaping `NULL` value. By not doing so, coupled with the PR #100, we are flushing too often.
> [Typing Library] Early exit for nil value

- clients/bigquery/merge.go
- clients/snowflake/merge.go
- clients/snowflake/merge_test.go
- clients/snowflake/snowflake.go
- lib/array/strings.go
- lib/array/strings_test.go
- lib/dwh/dml/merge.go
- lib/dwh/dml/merge_test.go
- lib/typing/bigquery.go
- lib/typing/bigquery_test.go
Postgres JSON and JSONB are TOASTable column.
However, it will currently fail on 2 things.
1) It will try to cast `__debezium_unavailable_value` to JSON.
2) Try to compare a JSON / VARIANT column against a STRING.
This PR will correctly cast both.
JSON version of unavailable value
```json
{"key": "__debezium_unavailable_value"}
```
> Escaping TOASTed JSON columns

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
- clients/bigquery/merge.go
- lib/array/strings.go
- lib/array/strings_test.go
- lib/dwh/ddl/ddl.go
- lib/dwh/dml/merge.go
In this PR, we are making 3 improvements.
1) Removing `tablePrefix` as a clean up task
2) Modularizing BigQuery MERGE
3) Fixing the way we insert arrays, arrays of nested objects, arrays of nested arrays, etc.
> BigQuery - Better handle on Arrays

- clients/bigquery/merge.go
- clients/snowflake/cleanup.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- clients/snowflake/sweep.go
- clients/snowflake/sweep_test.go
- lib/config/config.go
- lib/config/config_test.go
- lib/config/constants/constants.go
- lib/db/db.go
- lib/dwh/ddl/ddl.go
- lib/dwh/ddl/ddl_temp_test.go
- lib/dwh/ddl/ddl_test.go
- lib/dwh/utils/load.go
- lib/kafkalib/topic.go
- lib/kafkalib/topic_test.go
- lib/typing/bigquery.go
- lib/typing/bigquery_test.go
Snowflake TEMP tables are session based and do not have a TTL setting. 
This creates a concurrency problem since the Snowflake SQL driver (which is based on Go's sql/driver) and leverages connection pooling.
Whenever a new connection is spawned, it may not have reference to the temporary table. This effectively caps our parallelism at 1. 
I have fixed it here: https://github.com/artie-labs/transfer/commit/e2ed85c766038b0cff0be66cfca854a10be576e1 and filed a bug with Snowflake here: https://github.com/snowflakedb/gosnowflake/issues/805.
However, this has been around since inception and is unlikely to get fixed. Also, Snowflake tables do not have a concept of table expiration (unlike [BigQuery](https://cloud.google.com/bigquery/docs/managing-tables#updating_a_tables_expiration_time))
This …
> Don't use Snowflake temporary tables

- clients/snowflake/cast.go
Sometimes, if a column that has been quoted by the CSV writer (which Snowflake will attempt to escape from) contains a `\` value.
It'll mess with the sequence for Snowflake since we're not escaping it correctly with `\\`.
> Snowflake Escape special characters

- lib/stringutil/strings.go
- lib/stringutil/strings_test.go
Since `stringutil.Wrap` takes the optionality of a quote, we should be selective about escaping. Previously, regardless of quotes - we were escaping.
Expected results:
| quote | value before | value after |
| ---- | --- | ---- |
| yes | bill o'reilly | `'bill o\'reilly'` |
| no | bill o'reilly | `bill o'reilly` |
> Escaping strings correctly

- lib/typing/snowflake.go
Snowflake's `TIMESTAMP_NTZ` (of which datetime is an alias for) - is buggy when it comes to JOINs and working with other datasets that uses TIME ZONE (where TZ = UTC).
As mentioned in the comments, Snowflake will try to parse this column out into the session's local TZ and then parse it back into UTC which messes with the actual values.
> Snowflake to use TIMESTAMP with TIME ZONE instead of TIMESTAMP_NTZ

- clients/snowflake/cast.go
- clients/snowflake/cast_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- clients/snowflake/sweep_test.go
- lib/dwh/ddl/ddl.go
- lib/dwh/ddl/ddl_temp_test.go
- models/event/event.go
- models/event/event_save_test.go
With the Snowflake Stage method, we were not distinguishing the two because Snowflake's default for TSV/CSV uploader has `EMPTY_FIELD_AS_NULL=true`.
[Docs](https://docs.snowflake.com/en/user-guide/data-unload-considerations)
To get explicit empty strings, we needed to modify 2 settings:
* `EMPTY_FIELD_AS_NULL = FALSE`
* Set `NULL_IF = \\N` (which is default, but setting it just in case).
> [Snowflake] Distinguishing NULL and empty strings

- lib/typing/bigquery.go
This is a f/u to the Snowflake PR: https://github.com/artie-labs/transfer/pull/111.
TL;DR - We should not be using DATETIME because it makes it difficult to join with other timestamp columns, and DATETIME (without timezone) is not absolute.
This will be included in the `2.x` releases, if anyone is upgrading from `1.x`, use this script to migrate the columns:
```sql
-- 1. Add a new column with TIMESTAMP_TZ data type
ALTER TABLE customers.customers_test2 ADD COLUMN timestamp_1_test_new TIMESTAMP;
-- 2. Update the new column with the converted data
UPDATE customers.customers_test2 SET timestamp_1_test_new = TIMESTAMP(timestamp_1_test, "UTC") WHERE timestamp_1_test is not null;
-- 3. Drop the old column
ALTER TABLE customers.customers_test2 DROP COLUMN timestamp_1_test;
-- 4. Rename the new …
```
> [BigQuery] Migrate to use TIMESTAMPS instead of DATETIME

- lib/db/mock/db.go
- main.go
- models/event/event.go
- models/event/event_save_test.go
- models/flush/flush.go
- models/flush/flush_test.go
- models/memory.go
- models/memory_test.go
- processes/consumer/flush.go
- processes/consumer/flush_suite_test.go
- processes/consumer/flush_test.go
- processes/consumer/kafka.go
- processes/consumer/process.go
- processes/consumer/process_test.go
- processes/consumer/pubsub.go
- processes/pool/writes.go
Fixes https://github.com/artie-labs/transfer/issues/97
This is our latest iteration to make `tableFlushTime` truly the same time it takes to flush the table.
As you can recall from the PR linked from the issue, it was `CUM_SUM(tableFlush)`, we got it down to `MAX(tableFlush)`.
These are the main modifications:
Previously, we were flushing the whole database. This is because our lock was at the database level. We did not differentiate between:
1) Time-based trigger flush
2) Individual table triggered flush
Now, only (1) is flushing the whole database.
(2) will only trigger the flush for the specified table.
This is to avoid front-runners triggering redundant flushes for slower tables.
We still have a lock on the db, but it's meant for admin purposes. The actual lock is now at the table …
> Implementing per table flush

- processes/consumer/configs.go
- processes/consumer/kafka.go
- processes/consumer/process.go
- processes/consumer/process_test.go
- processes/consumer/pubsub.go
Currently, we'll spin up a new go-routine per topic specified within `tableConfig`.
However, if they happen to all run at the same time, we'll run into a concurrent r/w panic for the map, as each topic is trying to find the correct format setting and store it within `tcFmtMap`.
It doesn't happen often, but likelihood increases as there are more topics.
We're coming up with a wrapper object that provides basic `sync.Mutex` safety around reading and writing. 
Previous stacktrace:
```
fatal error: concurrent map writes
goroutine 78 [running]:
github.com/artie-labs/transfer/processes/consumer.StartConsumer.func1({0xc00027dbc0, 0x5d})
/Users/robintang/code/go/src/github.com/artie-labs/transfer/processes/consumer/kafka.go:91 +0x1f0
created by …
```
> Alleviate periodic panics during initialization

- clients/bigquery/bigquery_suite_test.go
- clients/bigquery/ddl.go
- clients/bigquery/errors.go
- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
- clients/snowflake/ddl.go
- clients/snowflake/snowflake.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mysql/debezium_test.go
- lib/cdc/util/parse.go
- lib/cdc/util/parse_test.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_test.go
- lib/cdc/util/util_suite_test.go
- lib/config/constants/constants.go
- lib/dwh/ddl/ddl.go
- lib/optimization/event.go
- lib/ptr/ptr.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
- lib/typing/columns/default.go
- lib/typing/columns/default_test.go
- models/event/event.go
- models/event/event_test.go
- processes/consumer/process_test.go
In SQL, any operation related to setting a column default value is considered a DDL operation. This means that it will not be visible to the CDC stream.
In order to support this, we'll need to inspect the metadata envelope from Debezium upon a CDC event and see if a column has default values (or not).
If the column indeed has a default value, we will backfill previously values.
_Example: Table `foo` has a column named `bar` and has default value of `false`_
```
UPDATE foo SET bar = FALSE where bar IS NULL;
```
^ This is the simplistic view, however - Transfer is stateless...so how do we not backfill upon every initialization?
We will do so by leveraging column comments (Snowflake) and/or column description (BigQuery).
Upon a successful backfill, we will annotate the column as such:
> Supporting default values

- clients/bigquery/bigquery_suite_test.go
- clients/bigquery/ddl.go
- clients/bigquery/errors.go
- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
- clients/snowflake/ddl.go
- clients/snowflake/snowflake.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mysql/debezium_test.go
- lib/cdc/util/parse.go
- lib/cdc/util/parse_test.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_test.go
- lib/cdc/util/util_suite_test.go
- lib/config/constants/constants.go
- lib/dwh/ddl/ddl.go
- lib/optimization/event.go
- lib/ptr/ptr.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
- lib/typing/columns/default.go
- lib/typing/columns/default_test.go
- models/event/event.go
- models/event/event_test.go
- processes/consumer/process_test.go
In SQL, any operation related to setting a column default value is considered a DDL operation. This means that it will not be visible to the CDC stream.
In order to support this, we'll need to inspect the metadata envelope from Debezium upon a CDC event and see if a column has default values (or not).
If the column indeed has a default value, we will backfill previously values.
_Example: Table `foo` has a column named `bar` and has default value of `false`_
```
UPDATE foo SET bar = FALSE where bar IS NULL;
```
^ This is the simplistic view, however - Transfer is stateless...so how do we not backfill upon every initialization?
We will do so by leveraging column comments (Snowflake) and/or column description (BigQuery).
Upon a successful backfill, we will annotate the column as such:
> Support default values

- clients/bigquery/merge_test.go
- clients/snowflake/staging_test.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
This is to patch our most recent PR: https://github.com/artie-labs/transfer/pull/127 which triggers a backfill for any column that has a default value.
However, if the whole pool only contains `DELETE` events, we will not trigger the backfill SQL since we do not have the column metadata from our typing library since `after` is `NULL`.
> Skip backfilling invalid columns

- lib/dwh/ddl/ddl.go
- lib/dwh/ddl/ddl_create_table_test.go
- lib/dwh/ddl/ddl_sflk_test.go
This way, we'll see all the temporary staging tables created.
Also, any DDL statements done to the target table such as `ADD COLUMN` and `DROP COLUMN`
> More logging within our DDL library

- clients/bigquery/merge.go
- clients/redshift/redshift.go
- clients/snowflake/staging.go
- lib/dwh/ddl/ddl.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
This bug was introduced from the default value PR (https://github.com/artie-labs/transfer/pull/127), which tries to trigger:
1. A backfill (unsuccessfully)
2. Update the `tableConfig` incorrectly.
> Don't backfill or update table column if it's invalid

- lib/optimization/event.go
- lib/optimization/event_test.go
- lib/optimization/event_update_test.go
Right now, we are filtering out any columns that are entirely labelled as `typing.Invalid` for 2 primary reasons.
1. We are not able to infer the data type from the value which limits our ability to create the column downstream
2. We have an optimization to skip updating that column altogether.
However, what if the column exists in the destination and either the batch consists of updates coming from:
* `UPDATE TABLE set col = NULL;` or 
* `UPDATE TABLE set col = NULL where id = 1;` on a low traffic table?
If any of these edge cases arise, we'll then skip this column update on the destination. This PR aims to fix that entirely and only skip column creation if column type = `typing.Invalid`.
> Fix NULL edgecase

- clients/bigquery/bigquery.go
- lib/config/config.go
- lib/config/config_test.go
If we don't allow location to be specified, it will default to the US, as per our library: https://github.com/viant/bigquery/blob/8f5b6fd4770f9a2206f1096bf4db9d1a28f8e2f0/dsn.go#L155-L157
This PR adds the ability to specify an optional location.
> BigQuery DSN to specify location

- clients/bigquery/merge.go
- clients/redshift/merge.go
- clients/snowflake/staging.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_decimal_test.go
- lib/cdc/util/relational_event_test.go
- lib/config/constants/constants.go
- lib/dwh/ddl/ddl_alter_delete_test.go
- lib/dwh/dml/merge.go
- lib/kafkalib/topic.go
- lib/typing/columns/diff.go
- lib/typing/columns/diff_test.go
- lib/typing/ext/variables.go
Right now, there is not a canonical way to know when this row was transferred to your destination unless you have a particular ts field. 
Having a consistent timestamp field may be useful if you are setting up `dbt` incremental digest or wanting to query the destination and see Artie's progress (on top of using our telemetry package).
In this PR, we are adding the ability to include `__artie_updated_at` to your destination tables by having this as a configuration option within `tableData`.
> Add the ability to include __artie_updated_at

- lib/cdc/mongo/debezium.go
- lib/cdc/util/relational_event.go
We are lowercasing and sanitizing the output here: https://github.com/artie-labs/transfer/blob/35fe6193f81bb664d7920da5204786c835b5664d/models/event/event.go#L144-L154
We needed to do the same when we got a field from Debezium's envelope.
What ended up happening is that we ended up adding more columns. As a result, when the `diff` ran, it ran against 2 (one was added by this codepath, the other by `event.go` Save)
As a result, we kept 2 `createdAt` columns and caused column duplication error.
> We need to lowercase when adding columns in our Debezium envelope

- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
- clients/snowflake/staging_test.go
- clients/utils/utils.go
`.ToLower(...)` is redundant here and also impacts our ability to actually support UPPERCASING table / col name if this is happening.
> Remove .ToLower() within backfills

- lib/cdc/mongo/debezium.go
- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
- processes/consumer/process.go
MongoDB allows the value of `NaN` which is not accepted by JSON or JSON extended.
This PR will swap `NaN` values to `NULL` and not touch `"NaN"` or any values that have the `NaN` prefix.
> Gracefully dealing with MongoDB NaN errors

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
- clients/bigquery/merge.go
- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/merge.go
- clients/redshift/staging.go
- clients/snowflake/cast.go
- clients/snowflake/cast_test.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- clients/utils/utils.go
- lib/array/strings.go
- lib/array/strings_test.go
- lib/cdc/mongo/debezium.go
- lib/cdc/postgres/debezium_test.go
- lib/cdc/util/relational_event_test.go
- lib/config/config.go
- lib/typing/columns/default.go
- lib/typing/columns/default_test.go
- lib/typing/ext/ext_suite_test.go
- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/typing.go
- lib/typing/typing_bench_test.go
- lib/typing/typing_suite_test.go
- lib/typing/typing_test.go
- models/event/event.go
1. Folks using MongoDB straight and not an application schema layer such as Mongoose can have inconsistent data. 
We are seeing incoming data of `Datetime` and `Date` type being mixed within a flush cycle for the same column. 
Our existing casting library will look at `extTime` which is row specific and try to parse it accordingly. This then leads to a mixed type within our flush cycle.
2. We are returning `[]string{}` within our BigQuery array f(x) instead of `nil` and being skipped. BigQuery does not like empty strings, it prefers to be skipped.
3. Folks that have additional date formats that are not supported within https://github.com/artie-labs/transfer/blob/master/lib/typing/ext/variables.go can now specify additional formats for Artie Transfer to use via …
> Handling inconsistent source data and weird edge cases

- clients/bigquery/merge.go
- lib/array/strings.go
- lib/array/strings_test.go
- lib/dwh/dml/merge.go
- lib/kafkalib/partition/settings.go
- lib/kafkalib/partition/settings_test.go
- lib/kafkalib/topic.go
- lib/optimization/event.go
- lib/optimization/event_test.go
BigQuery bills you by bytes processed, every time we merge, it will do a full table scan. This then increases bytes processed and incurs additional costs.
When you have lots of data, it's encouraged to use partitions and this PR makes it so that we can support timed partitioned tables when it comes to merging.
We will support daily partitioning for now and will support more in the future. This PR serves to support the minimum recommended partitioning strategy and scaffold to support future ones such as hourly, weekly, monthly and yearly.
`bigQueryPartitionSettings` will include:
* `partitionType` (time)
* `partitionField` (ts)
* `partitionBy` (daily)
> Supporting BigQuery time partition tables

- lib/kafkalib/partition/settings.go
As per title. This way, we can marshal and unmarshal this data type in JSON and with YAML.
> Adding JSON encoding to BigQuery Partitions.

- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
When Snowflake session expires, we are currently emitting an error, re-establish the connection and then wait for another merge cycle to kick in.
The problem is that if there's a session expiration every 4 hours, then we'll just be in a loop of session expiring and resetting.
This makes it so that as soon as this happens, we'll re-issue another merge command right away.
> [Snowflake] Don't wait to merge when auth expires

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
- lib/typing/ext/time.go
BigQuery is strict on timestamps and does not like bad timestamps such as when the year is `0`.
Today, it's causing a head of line blocking. Let's change this so that marks the value as NULL as opposed to blocking the pipeline.
> [BigQuery] Mark bad timestamps as NULL value in BigQuery

- lib/typing/redshift.go
Redshift TEXT columns default to `256 bytes` which is far too small for JSON or b64-encoded values.
We are increasing this to 2 kb for now. If we needed to increase this further, we can consider adding a setting.
URL: https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html
> Updating Redshift TEXT columns

- lib/typing/redshift.go
Redshift TEXT columns default to `256 bytes` which is far too small for JSON or b64-encoded values.
URL: https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html
We will be automatically changing the VARCHAR type to be `VARCHAR(max)`. 
Why?
1. This guarantees that our automatically created columns will not error out based on DDL length.
2. Folks can modify the columns that were created by Transfer to be more efficient.
Such workflow would look something like this:
```sql
ALTER TABLE my_table ADD COLUMN my_column_new VARCHAR(100);
UPDATE my_table SET my_column_new = my_column;
ALTER TABLE my_table DROP COLUMN my_column;
ALTER TABLE my_table RENAME COLUMN my_column_new TO my_column;
```
> [Redshift Typing bug]

- lib/destination/ddl/errors.go
- lib/destination/ddl/errors_test.go
Making it so that we don't hard fail if the column doesn't exist, following the same pattern as BigQuery and Snowflake.
> [Redshift] Adding DDL idempotency

- clients/redshift/cast.go
- clients/redshift/redshift.go
- clients/utils/table_config.go
- go.mod
- lib/optimization/event.go
- lib/optimization/event_update_test.go
- lib/typing/redshift.go
- lib/typing/redshift_test.go
```sql
ALTER TABLE mytable ADD COLUMN TEMP_SUPER SUPER;
UPDATE mytable set TEMP_SUPER = json_parse(DETAIL);
ALTER TABLE mytable DROP COLUMN DETAIL;
ALTER TABLE mytable RENAME COLUMN TEMP_SUPER to DETAIL;
```
> [Redshift] SUPER data type for JSON and parsing NUMERIC edge case

- lib/typing/typing.go
- lib/typing/typing_test.go
Today, we are only considering strings that look like `{"foo": "bar"}` as valid JSON and not strings that look like `["foo", "bar"]`.
However, this is wrong because the latter is valid JSON. By considering this as a string, we are hitting the DDL limit on Redshift of 64k chars.
As a reminder, our typing library looks at data type first and only does special casting for STRING values, which means - if the data type for `[]string{"foo", "bar"}` came in, we would consider this a slice.
> [Typing library] Improving JSON typing

- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
In the previous PRs, we made JSON data types into a SUPER data type. We now need to escape the TOAST columns correctly.
> [Redshift] Modify escaping TOAST columns for SUPER data types

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/redshift.go
- clients/redshift/redshift_suite_test.go
- clients/redshift/staging.go
- lib/config/config.go
- lib/config/constants/constants.go
- lib/destination/ddl/ddl_suite_test.go
This PR enables customers to turn on column value replacement whenever the column value exceeds Redshift's limits.
Currently, this is implemented such that:
* String values cannot exceed 65k chars
* STRUCT / SUPER values cannot exceed 1 mb
In the case where STRING values exceed, we'll return `__artie_exceeded_value`
For STRUCT / SUPER values, we'll return `{"key":"__artie_exceeded_value"}`
To enable this, update your Redshift configuration and include this:
```yaml
redshift:
skipLgCols: true
```
> [Redshift] Replace columns that have exceeded Redshift limits

- lib/artie/message.go
- processes/consumer/flush.go
- processes/consumer/kafka.go
- processes/consumer/process.go
- processes/consumer/process_test.go
- processes/consumer/pubsub.go
We were previously only emitting the metadata available before processing a message to calculate the ingestion lag, which meant that we had `topic` and `partition`.
This makes it such that we cannot join metrics across all of the metrics we are currently tracking. 
This does mean that ingestion lag includes processing time. This will likely increase the overall ingestion lag by a slight margin, however - it should be negligible because when the process locks to merge, we are no longer ingesting.
As a result, the subsequent action of reading from the Kafka topic after merge will incur the merge latency, which makes this negligible.
> [Telemetry] Adding tableName to the Kafka topic ingestion lag

- lib/cdc/mongo/debezium_test.go
- lib/cdc/mongo/postgres_suite_test.go
- lib/cdc/postgres/debezium_test.go
- lib/cdc/postgres/postgres_suite_test.go
- lib/cdc/util/optional_schema.go
- lib/cdc/util/optional_schema_test.go
- lib/cdc/util/parse.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_test.go
- lib/config/config.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/debezium/types.go
- lib/debezium/types_bench_test.go
- lib/debezium/types_test.go
- lib/maputil/map_test.go
- lib/typing/decimal/decimal.go
- lib/typing/typing.go
Today, we are reliant on our Typing library inferring the right column to create downstream via inference on the first not null data type.
This works well, however it creates a constraint that the column will only be created if Artie Transfer has seen at least one `not null` value. 
For sources that have schemas such as Postgres and MySQL, we can actually inspect the message header from Debezium and know the exact type. From there, we can map it to our Typing library and create the columns irregardless of whether the value actually is set. 
This will be an opt-in flag that customers can enable.
> Improving Optional Schema

- lib/debezium/schema.go
- lib/debezium/schema_test.go
* We are currently storing all bytes data as TEXT and allowing customers to coerce it out at the DWH level. 
* This PR formally recognizes that in the optional schema such that we are not storing it as `typing.Invalid`
> [Optional Schema] Recognizing bytea

- clients/bigquery/batch.go
- clients/bigquery/batch_test.go
- clients/bigquery/bigquery.go
- lib/config/bigquery.go
- lib/config/config.go
Addresses: https://github.com/artie-labs/transfer/issues/183
See linked issue for the reason why we are doing this.
We are adding a new optional parameter called `bigQuery.batchSize` (int) which defaults to 1k if not passed in.
This is used to iterate over the in-memory database to incrementally call the Streaming API to insert data with the size specified by `batchSize`. Once this is done, it will then invoke a MERGE.
This now allows us to have a larger in-memory database pool
> Working past the 10 mb limit of BigQuery

- clients/redshift/merge.go
We found out last Friday that there was a potential for duplicate rows to arise from loading a temporary table [src](https://saturncloud.io/blog/how-to-prevent-duplicate-data-in-amazon-redshift/#causes-of-duplicate-data-in-amazon-redshift).
This was happening extremely infrequently and happened during a particular timeframe when Redshift was having issues. This change adds an extra guardrail around the temporary table to ensure there are 0 duplicate rows.
> [Redshift] Adding a guardrail around load errors

- clients/redshift/cast.go
Redshift has a VARCHAR column that allows up to 2^16. However, it's choking on values that are ~ 65,300 in bytes.
As a result, we are lowering this to 65k as opposed to `65535`
> [Redshift] Reducing Max VARCHAR length

- Makefile
- clients/redshift/cast.go
- clients/redshift/redshift_bench_test.go
The previous PR: https://github.com/artie-labs/transfer/pull/191 was inspecting char length based on `len(valString)` which is not 1:1 with the actual number of bytes.
Instead, we are now casting it into a byte array and inspecting the length.
The new method is slightly slower, but it's still pretty fast.
```
robins-macbook-pro:transfer robintang$ make bench_redshift
go test ./clients/redshift -bench=Bench -benchtime=20s
goos: darwin
goarch: amd64
pkg: github.com/artie-labs/transfer/clients/redshift
cpu: VirtualApple @ 2.50GHz
BenchmarkOldMethod-12    	280654028	        87.39 ns/op
BenchmarkNewMethod-12    	202929502	       120.2 ns/op
PASS
ok  	github.com/artie-labs/transfer/clients/redshift	70.343s
```
> [Redshift] Improvement around DDL inspection

- lib/ptr/ptr.go
- models/memory.go
- models/memory_flush_test.go
- models/memory_test.go
- processes/consumer/flush.go
- processes/pool/writes.go
Right now, there are 3 levers to trigger a merge which are:
a) Time
b) Rows
c) Bytes
How this is implemented is that there is a separate Go-routine following the CPU clock cycle to implement (a). As a result, if we were flushing based on (b) and (c), we may bump into a pre-mature flush based on time.
Imagine the following scenarios:
(a) t = 30s
(b) rows = 25k
(c) bytes = 25mb
* On t = 28, We just flushed based on (b)
* Now t = 30, we haven't accumulated much changes but now we triggered a flush based on (a) anyway
Now, we're adding a concept of merging cooldown for the process that is running (a).
In the same example as above,
* On t = 28, We just flushed based on (b), last merged timestamp is set to t28
* Now t = 30, the time between last merge and now (t = 2) is less than duration, so …
> Merging cooldown

- clients/redshift/staging.go
Previously we were writing to a local CSV file and then uploading it to S3. Once there, we then invoke `COPY INTO` for Redshift to load the CSV file into a table.
However, if the diffs are pretty large - this can take a couple of minutes to upload the diffs to S3 and then for Redshift to ingest. 
Instead, we can write this in `csv.gz` format and then upload the compressed file and have Redshift automatically decompress within COPY INTO.
Loading 2M rows into Redshift
```
No GZIP (current) — 337s
W/ GZIP — 286s
```
> Adding GZIP

- clients/redshift/cast.go
- clients/redshift/redshift_bench_test.go
We are trying to address DDL overflow with the past 2 PRs. However, we are not calculating the overflow correctly since we were using `[]byte` and not just counting the number of characters.
In addition to using the wrong metric to count, we were also counting pre-string manipulation. We are currently unnecessarily changing `\` to `\\`,
> [Redshift] Use string length not byte to calculate DDL overflow

- clients/redshift/redshift.go
- clients/utils/table_config.go
We are fetching existing table metadata with Redshift by querying `information_schema`. However, if a table name is capitalized, we are not escaping this correctly.
As a result - we are adding an extra guardrail to lower both key and values for name and schema to avoid this issue.
> Adding table guardrail for Redshift

- lib/db/db.go
- lib/db/errors.go
- lib/db/errors_test.go
Today, when Transfer is paired with SSH tunnels and there is a remote connection reset (SSH Tunnel and database) - we are emitting a merge error to Datadog (which then pages) and then it will retry.
By adding this SQL wrapper around the SQL engine, we will address the false alarm and also not have to restart the merge process (it will automatically retry from the same merge position on which it encountered the error)
> Implementing automatic retries 

- clients/redshift/merge.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_parts_test.go
- lib/kafkalib/topic.go
- models/event/event.go
- models/event/event_save_test.go
Today, if you wanted to skip table deletes, you'd need to configure this in Debezium. However, Debezium's setting for this is database-wide. Adding this into Transfer creates three benefits:
1. Can toggle this on/off without having to resync
2. Expand this to diff. data sources that DBZ doesn't cover
3. Allow us to move away from database specific to be at the table granularity
> Adding table level skip deletes

- models/event/event.go
- models/event/event_save_test.go
- models/event/event_test.go
- processes/consumer/process.go
- processes/consumer/process_test.go
This is an improvement from https://github.com/artie-labs/transfer/pull/205 where we are skipping the message during `processMessage` as opposed to skipping it during `.Save()`.
The benefit of this is that our `process.message.count` will have an additional tag of `skipped=Yes` if `skipDelete = true` and the operation is `delete`.
> Improving skipDelete

- clients/bigquery/errors.go
- lib/config/config.go
- lib/numbers/numbers.go
- lib/numbers/numbers_test.go
- lib/typing/bigquery.go
- lib/typing/bigquery_test.go
- lib/typing/decimal/decimal.go
- lib/typing/decimal/decimal_test.go
Fixes https://github.com/artie-labs/transfer/issues/170
1. Adding `BetweenEqArgs` to be more explicit about setting `start`, `end` and ` number`
2. Adding support for BIGNUMERIC in BigQuery
3. Adding the proper support for NUMERIC in BigQuery by following the equation from the issue
> [BigQuery] Better support of NUMERIC and BIGNUMERIC

- clients/bigquery/bigquery.go
- clients/redshift/merge.go
- clients/redshift/queries.go
- clients/redshift/queries_test.go
- clients/redshift/redshift.go
Artie is not running describe table correctly for Redshift tables that require escaping. We are querying `information_schema.columns` which does not require escaping table names.
> [Redshift] Describe tables that require escaping bug

- lib/debezium/types.go
- lib/debezium/types_test.go
We were previously not parsing negative numbers correctly from Debezium's DECIMAL type as we were ignoring the sign.
This PR adds the ability for us to parse negative numbers correctly.
> Correctly parsing negative numbers from Decimal

- lib/kafkalib/topic.go
- lib/typing/redshift.go
- lib/typing/redshift_test.go
We were not correctly parsing the describe table contents from Redshift. This PR fixes that.
> [Redshift] Correctly parse character varying

- clients/redshift/cast.go
- clients/redshift/cast_test.go
We are doing some light sanitization when the string contains values for an array, that coupled with our wrongly placed `replaceExceededValues` function is causing DDL overflow in Redshift.
We should be calling `replaceExceededValues(...)` post manipulation and at the end of the f(x).
> Fix Redshift DDL overflow

- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
We were already escaping `NaN`, but we were not escaping `Infinity` and `-Infinity`
This PR adds that capability
> [MongoDB] Escaping infinity and negative infinity correctly

- lib/typing/typing.go
- lib/typing/typing_test.go
In our Typing library's `IsJSON(...)` function, we are trimming whitespace after the length check. This means that we can run into a potential panic situation where the value is empty and then we try to fetch the first and last character of an empty string.
We should be trimming space before the length check and fail early
> Fixing a potential panic in our Typing library

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/redshift_suite_test.go
Say we are syncing from MongoDB and the column can be both JSON and STRING.
In Redshift, we are casting this column as `VARCHAR(MAX)` since `SUPER` doesn't like certain non-ASCII characters. 
Transfer's inference library will use Redshift as the source of truth and cast all these values down into STRING.
However the JSON object that is being casted as a string looks like `map[foo] = bar` as opposed to `{"foo": "bar"}`
> [Redshift] Edge case with schema inference

- clients/snowflake/cast.go
- clients/snowflake/cast_test.go
- clients/snowflake/staging.go
This is the Snowflake follow up for this https://github.com/artie-labs/transfer/pull/223
If the Snowflake column is detected to be a `STRING`, we should `JSON.stringify(...)` the value.
> [Snowflake] Edge case with schema inference

- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_test.go
Addresses https://github.com/artie-labs/transfer/issues/227
The problem here is that `stringutil.Random(...)` could return capital letters, but our DROP TABLE statement is lowercasing it for Snowflake and Redshift.
This leads to temporary tables not being deleted in BigQuery, also BigQuery does not require us to escape table names, below SQL statement works.
```sql
DROP TABLE foo.bar_artie_AAA;
```
> [BigQuery bug] Fix dropping temporary tables

- lib/artie/message.go
- lib/telemetry/metrics/base/provider.go
- lib/telemetry/metrics/datadog/datadog.go
- lib/telemetry/metrics/null_provider.go
- processes/consumer/kafka.go
Today, we are emitting ingestion lag by diffing the timestamp within the Kafka or Pub/Sub message against the current timestamp. 
However, that is the ingestion age, not how long it will take to get to queue 0, where the time to `queue 0` is an output from:
1. Rate of change of the row lag: 
* How many rows are we processing
* How many rows are we adding
2. How large is the backlog (row lag)
Visually, it'll look something like this:
Today, the ingestion age will just tell you how old is the message you are processing. With this PR, we will soon have the ability to **display time to queue 0** within our Analytics Portal.
1. We are calculating high watermark by diffing the current message offset along with the Kafka partition's high watermark
2. We are sending 50% of this data to Datadog …
> Emitting Kafka row lag

- lib/sql/escape.go
- lib/sql/escape_test.go
We were previously not escaping columns that either contained symbols or were numbers. This PR will now escape both of these scenarios.
| Column Name | Before | After |
| -------------- | ------- | ---- |
| receivedAt:__ | Not escaped | Escaped |
| 1234 | Not escaped | Escaped |
> Additional scenarios to escape column

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
- clients/bigquery/merge.go
- lib/config/constants/constants.go
- lib/size/size_test.go
- lib/typing/columns/default.go
- lib/typing/columns/default_test.go
We were not correctly backfilling the default values for JSON columns for Snowflake and Redshift. 
1. Changed `castColVal` for BigQuery to be private (was not used elsewhere)
2. Fixed default value parsing for Snowflake and Redshift (the default values for JSON arrives in a STRING format).
> Fix JSON Default Values

- clients/bigquery/merge.go
- clients/redshift/merge.go
- clients/redshift/queries.go
- clients/snowflake/snowflake.go
- clients/snowflake/staging.go
- clients/utils/table_config.go
- lib/config/constants/redshift.go
- lib/destination/ddl/ddl_bq_test.go
- lib/optimization/event.go
- lib/optimization/event_test.go
- lib/optimization/event_update_test.go
- lib/typing/redshift.go
- lib/typing/redshift_test.go
- lib/typing/typing.go
- lib/typing/typing_kind_test.go
Debezium does not expose the character precision within the actual message. For example, we don't know if the column is `VARCHAR(123) vs VARCHAR(333)`.
As such, we have been creating all string based columns as `VARCHAR(MAX)` to preserve precision. However this comes with a tradeoff of over-provisioning space. 
For Snowflake and other data warehouses, it doesn't matter - the actual space used will be the actual length of the value. However, Redshift allocates space based on the column precision.
The workaround for this has been to go into the actual table in DWH and update it yourself:
```sql
ALTER TABLE public.customers_test2 ALTER COLUMN first_name TYPE VARCHAR(123);
```
When this is done, Transfer will not try to mutate the column back to `VARCHAR(MAX)` and will just continue to …
> [Redshift] Ability to infer VARCHAR length

- lib/optimization/event_test.go
- lib/size/size.go
- lib/size/size_bench_test.go
- lib/size/size_test.go
Previously, we were encoding the values to be string and then calculating the number of bytes to approximate how large each row is.
For super wide tables, it was pretty slow and could take up to 20ms each time it was invoked.
Now, we are iterating over the row and then calculating each row by first inspecting the primitive type and if it's indeed a string, just count the number of bytes as opposed to serializing it out again.
```
BEFORE
cpu: VirtualApple @ 2.50GHz
BenchmarkGetApproxSize_TallTable-12    	    1604	   7524981 ns/op
BenchmarkGetApproxSize_WideTable-12    	     214	  54952219 ns/op
BenchmarkTableData_ApproxSize_TallTable-12    	 7741323	      1654 ns/op
BenchmarkTableData_ApproxSize_WideTable-12    	 1000000	     11223 ns/op
-----
AFTER
BenchmarkGetApproxSize_TallTable-12 …
```
> Optimizing the way we calculate our in-memory pool size

- lib/size/size.go
- lib/size/size_test.go
Follow up to PR #238, adding 2 more types; `nil` and `[]interface{}`
> Adding types for size.go

- clients/bigquery/merge.go
- clients/redshift/merge.go
- clients/snowflake/errors.go
- clients/snowflake/errors_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/staging.go
- clients/utils/table_config.go
- lib/destination/types/table_config.go
- lib/destination/types/table_config_test.go
1. Adding more test cases for Snowflake Auth Expiry
2. Standing up `AuditColumnsToDelete(colsToDelete []columns.Column)` to reduce boilerplate on MERGE and also add test coverage
> Minor cleanup merge

- clients/bigquery/bigquery.go
- clients/bigquery/merge.go
- clients/redshift/merge.go
- clients/redshift/redshift.go
- clients/snowflake/ddl_test.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- clients/utils/utils.go
- lib/cdc/mysql/debezium_test.go
- lib/cdc/util/relational_event_test.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/types/table_config.go
- lib/destination/types/table_config_test.go
- lib/optimization/event.go
- lib/optimization/event_test.go
- lib/optimization/event_update_test.go
- lib/parquetutil/generate_schema.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
- lib/typing/columns/default.go
- lib/typing/columns/diff.go
- lib/typing/columns/diff_test.go
- models/event/event_save_test.go
* Adding `col.RawDefaultValue()` which will just return the variable without any manipulation (used for logging)
* Adding `col.RawName()` which will also just return the name without any manipulation
* Adding `tableData.RawName()`
By doing so, we are able to remove `context` from intermediary functions and simplify the codepaths. This PR will tee us up to remove `context.Context` from our Typing library.
> [Refactor] Adding RawValue functions

- clients/bigquery/bigquery.go
- clients/bigquery/bigquery_suite_test.go
- clients/bigquery/merge.go
- clients/redshift/merge.go
- clients/redshift/redshift.go
- clients/s3/s3.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_alter_delete_test.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_suite_test.go
- lib/destination/types/table_config.go
- lib/optimization/event.go
- lib/optimization/event_test.go
* Refactoring `tableData.ToFqName(...)` to accept another `bigQueryProjectID (if exists)`. Doing this as a pre-cursor to the larger body of work to remove `context` from the typing library.
* Change `ddl.AlterTable` to early exit if there are no columns to alter to improve readability
> Refactoring TableData ToFqName

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
- clients/bigquery/merge.go
- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/staging.go
- clients/s3/s3.go
- clients/snowflake/cast.go
- clients/snowflake/cast_test.go
- clients/snowflake/snowflake_suite_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- clients/utils/utils.go
- lib/cdc/mongo/mongo_suite_test.go
- lib/config/config.go
- lib/optimization/event.go
- lib/optimization/event_test.go
- lib/parquetutil/parse_values.go
- lib/parquetutil/parse_values_test.go
- lib/typing/columns/default.go
- lib/typing/columns/default_test.go
- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/typing.go
- lib/typing/typing_test.go
This is the 3rd PR (should be one more after this) to remove `context` from Artie Transfer's typing library.
This time, we're changing the function signatures of:
* ParseFromInterface
* ParseExtendedDateTime
...to not have `ctx` and take in an array of strings for the `additionalDateFormats`
> [Refactor] Part 3 - Removing `context` from `lib/typing`

- lib/cdc/util/parse.go
- lib/debezium/types.go
- lib/optimization/event_test.go
- lib/typing/ext/time.go
- lib/typing/ext/time_test.go
Bad data can come into Transfer, we should figure out a way to filter them, especially for `time.Time` objects where the year exceeds the YYYY format or in BC. They will get rejected by downstream destinations, so let's filter them out and not hard fail.
> [ExtTime] Enforce YYYY - Take two

- clients/snowflake/snowflake_test.go
- clients/utils/table_config.go
- lib/config/config_test.go
- lib/config/constants/constants.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_test.go
- lib/destination/ddl/errors.go
- lib/destination/dml/merge_parts_test.go
- lib/destination/utils/load.go
- lib/optimization/event_test.go
- lib/typing/columns/wrapper_test.go
- lib/typing/typing.go
We should standardize everything on `snowflake` and not have to chain if statements everywhere
All you'll need to do is update your `outputSource` from `snowflake_stage` to `snowflake`
> [Snowflake] Deprecate `snowflake_stage` constant

- models/event/event.go
We should ensure values that were downcasted are also supported
> [TOASTED hstore] Ensure downcasting works.

- lib/cdc/mysql/debezium_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
This is what it looks like from Debezium:
```json
{
"type": "struct",
"fields": [
{
"type": "struct",
"fields": [
{
"type": "int32",
"optional": false,
"default": 0,
"field": "id"
},
{
"type": "string",
"optional": false,
"field": "first_name"
},
{
"type": "string",
"optional": false,
"field": "last_name"
},
{
"type": "string",
"optional": false,
"field": "email"
},
{
"type": "map",
"keys": {
"type": "string",
"optional": false
},
"values": {
"type": "string",
"optional": true
},
"optional": false,
"field": "custom_fields"
}
],
"optional": true,
"name": "dbserver1.inventory.customers.Value",
"field": "before"
}
]
}
```
> Support Debezium Maps

- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/mongo/mongo_bench_test.go
- lib/cdc/mysql/debezium.go
- lib/cdc/postgres/debezium.go
- lib/cdc/postgres/debezium_test.go
- processes/consumer/process.go
The impl functions are not using `context`, so we can remove it from the impl and interface.
> Removing context from `event.GetPrimaryKey(...)`

- lib/cdc/util/geometry.go
- lib/cdc/util/geometry_test.go
- lib/cdc/util/parse.go
- lib/debezium/schema.go
- lib/debezium/types.go
This is one of the first PRs to support PostGIS data type `Point`. We are then encoding this value into `GeoJSON`.
| Data in Postgres | GeoJSON Representation (in DWH) |
| -------- | -------------- |
| Point(2.2945, 48.8584) |<br>{<br> "type": "Feature",<br> "geometry": {<br> "type": "Point",<br> "coordinates": [2.2945, 48.8584]<br> }<br>}<br> |
> [PostGIS] Supporting Point

- lib/logger/log.go
We were previously using `WARN` which gets spammy. Let's use `ERROR` instead.
> Change Sentry logging to Error

- .github/workflows/gha-go-test.yml
https://github.com/actions/setup-go?tab=readme-ov-file#v4 has caching by default.
> Add Go package caching to GitHub Action

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/staging.go
* Missed `uppercaseEscName`
* Addressing Kafka tombstones for large integers in Redshift
TL;DR --
We rely on `parseField` to look at the CDC schema header and convert FLOATS into INTS if the schema tells us that the column is an integer.
However...
* Kafka tombstones doesn't have any metadata (no schema)
* JSON doesn't have a delineation between FLOATs and INTs, so it casts everything as a FLOAT
* Go's native print functionality will print large floats in scientific notation
> [Redshift] Fix edge cases for Kafka tombstone and number conversion

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/snowflake/cast.go
- clients/snowflake/cast_test.go
Debezium allows you to configure [decimal.handling.mode](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-decimal-handling-mode). Transfer currently supports all 3, but it does not support if you change handling mode during streaming.
Today, there is a breaking change if you go from `precise` to `double` or `string`.  This PR alleviates that by being compatible towards the two other handling modes.
> Address mixed precision handling indigestion

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- lib/typing/values/string.go
- lib/typing/values/string_test.go
Both are using compressed CSVs to upload into their respective destinations. The codepath are basically the same, so this PR is combining the two.
> Combining Redshift and Snowflake's Cast Value

- lib/artie/message.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/mongo/event.go
- lib/cdc/mysql/debezium.go
- lib/cdc/mysql/debezium_test.go
- lib/cdc/postgres/debezium.go
- lib/cdc/postgres/debezium_test.go
- lib/cdc/util/relational_event.go
- processes/consumer/kafka.go
- processes/consumer/process_test.go
Depending on how Debezium is configured - it may emit a Kafka tombstone message upon each delete. Previously Artie Transfer was treating it as a delete event. This is redundant and could cause issues when we want to start emitting the database updated timestamp (since the Kafka message will be `nil`).
Delete a row only when the database says to delete the row. Skip tombstone messages altogether.
> Skipping tombstone messages

- lib/artie/message.go
- processes/consumer/kafka.go
Following this PR: https://github.com/artie-labs/transfer/pull/286
We shouldn't need pointers for `kafka.Message`, so let's remove it.
> Kafka Message Fields - Don't use ptrs

- clients/redshift/merge.go
- clients/snowflake/sweep_test.go
- lib/config/config.go
- lib/config/config_test.go
- lib/config/context.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_parts_test.go
- lib/kafkalib/topic.go
- lib/kafkalib/topic_test.go
- lib/optimization/event.go
- lib/optimization/event_test.go
- main.go
- models/event/event.go
- models/event/event_test.go
- processes/consumer/flush_suite_test.go
- processes/consumer/process.go
- processes/consumer/process_test.go
This PR adds the ability to skip operations other than deletes, such as:
* `r` - replication / backfill
* `u` - update
* `c` - create
* `d` - delete
This can be done by specifying at the `topicConfig` level:
```yaml
kafka:
bootstrapServer: localhost:29092
groupID: transfer4
username: ""
password: ""
enableAWSMKSIAM: false
topicConfigs:
- db: customers
tableName: users_test2
schema: public
skippedOperations: c, r, d
```
This also adds a backwards compatibility port from `skipDelete`.
We now have feature parity with Debezium's [skipped.operations](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-skipped-operations)
> Skipping Operations Improvement

- lib/jitter/sleep.go
`2 ** x` is equivalent to `1 << x`, but doesn't require casting to `float64`. Proof https://go.dev/play/p/u2oW25Xes3Z
> Optimize jitter function

- clients/bigquery/merge.go
- lib/db/db.go
- lib/destination/types/table_config_test.go
- lib/destination/types/types_test.go
- lib/jitter/sleep.go
Also remove hardcoded `maxMs` and require callers to pass one in. This way we can reuse this function in [reader.](https://github.com/artie-labs/reader/)
> Return `Duration` from `Jitter()`

- clients/s3/s3_test.go
- clients/snowflake/snowflake_test.go
- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
- models/event/event_test.go
We were previously doing table name override both in `ToMemoryEvent(...)` and in `NewTableData(...)`
The logic is the same, so let's consolidate.
Where we are doing this in `ToMemoryEvent` in `event.go` https://github.com/artie-labs/transfer/blob/fe8cfd99ebb7f728ef72a9c2c9fd15b0089e455a/models/event/event.go#L47
> Consolidate table name override.

- clients/bigquery/merge.go
- clients/redshift/merge.go
- clients/redshift/staging.go
- clients/s3/s3.go
- clients/snowflake/staging.go
Today, we are only dropping tables and staging files upon a successful merge. This leaves temporary files and tables lingering around. 
Fortunately for temporary tables, we have a `Sweep(...)` process that will garbage collect old tables. 
This PR implements a `defer` such that all temporary tables and files are removed regardless of outcome. We'll still need `Sweep`, but this will reduce our reliance on it.
> Dropping staging files and temporary tables regardless of outcome

- lib/cdc/mongo/debezium_test.go
- lib/cdc/mongo/event.go
Making Payload public so that `Reader` can import from it to construct the right message
> Making MongoDB Payload Public

- clients/redshift/staging.go
Logging copy will leak `credentialsClause`, so let's not. 
Also, changing `fmt.Errorf(...)` to error wrap
> [Redshift] Remove copy statement from error logs.

- lib/destination/types/table_config.go
- lib/optimization/table_data.go
> Use stdlib `maps.Clone`

- clients/redshift/cast.go
- clients/redshift/cast_test.go
We are currently applying the SUPER limitation the same regardless of whether the value is an array, object or string. This is not correct since string's limit is 2^16.
> [Redshift] Addressing SUPER limitation

- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/mongo/event.go
Making these private since `before/after maps` are JSONE representation of the `after` and `before` strings.
As you can see from the event below, `after` is a JSONE string.
```json
{
"schema": {
"type": "",
"fields": null
},
"payload": {
"before": null,
"after": "{\"email\":\"pemett7@oaic.gov.au\",\"_id\":{\"$oid\":\"640127e4beeb1ccfc821c261\"},\"name\":\"Portie Emett\"}",
"BeforeMap": null,
"AfterMap": null,
"source": {
"connector": "",
"ts_ms": 1707868641463,
"db": "myFirstDatabase",
"collection": "customers"
},
"op": "r"
}
}
```
> MongoDB making before/after maps private

- processes/consumer/kafka.go
- processes/consumer/process.go
- processes/consumer/process_test.go
- processes/consumer/pubsub.go
Making this method public is a pre-requisite for having faster snapshots
> Make ProcessMessage public.

- processes/consumer/flush.go
Right now, if a merge fails - we will repeatedly hammer the destination to merge. Sometimes this has caused our destination to go down temporarily due to the DDOS.
This function does not have a concept of attempts, let's add a simple sleep in between merge attempts so we don't DDOS downstream destinations.
> Sleep after a merge failure

- clients/redshift/append.go
- clients/redshift/staging.go
- clients/snowflake/append.go
This will enable History Mode for Redshift Append
1. Apply necessary DDLs to the target table
2. Create staging table
3. Run `ALTER TABLE target APPEND staging` https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE_APPEND.html
> [Redshift] Supporting Append only

- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
- clients/utils/utils.go
Refactor `utils.BackfillColumn` to work with BigQuery as this is a pre-requisite in merge consolidation.
> [BigQuery] Consolidate column backfills

- clients/bigquery/append.go
- clients/bigquery/merge.go
- clients/redshift/append.go
- clients/redshift/redshift.go
- clients/s3/s3.go
- clients/snowflake/append.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- lib/destination/dwh.go
- processes/consumer/flush.go
- processes/consumer/process_test.go
Let's remove `context.Context` from MERGE and APPEND since it's no longer required.
> Removing `context.Context` from MERGE and APPEND

- lib/optimization/table_data.go
If `destCols` is empty, early return
> Address another TODO.

- clients/snowflake/append.go
- clients/snowflake/snowflake.go
Setting the max retries to be 10 for Snowflake MERGE and APPEND upon a retryable auth error.
> [Snowflake] Max Retries for Append and Merge

- lib/kafkalib/topic.go
- lib/kafkalib/topic_test.go
- processes/consumer/process_test.go
Previously, we already introduced `skippedOperations` which enables the ability to skip all operations with a comma separated string.
* This PR removes the old option `skippedDelete`.
* To maintain the ability for `skippedDelete` to work, make sure to set `skippedOperations = d`
> [Topic Config] Remove support for `skippedDelete`

- lib/typing/mssql.go
We didn't include `Float.Kind`, it didn't break anything because the default statement will return `kd.Kind` which is a Float, but this makes it explicit.
> [MSSQL] Typing library adding `typing.Float`

- clients/mssql/values.go
- clients/mssql/values_test.go
1. Adding tests to `parseValue`
2. Ability to cast colVal back into a number if the destination is a number and value provided is in string.
3. Changing everything `parseValue` from `interface{}` -> `any`
> [MSSQL] Increasing the resiliency of INTs and FLOATs

- clients/bigquery/cast.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- lib/array/strings.go
- lib/array/strings_test.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/util/geometry.go
- lib/cdc/util/parse.go
- lib/cdc/util/parse_test.go
- lib/jsonutil/jsonutil.go
- lib/optimization/table_data.go
- lib/size/size_bench_test.go
* Taking over this PR: https://github.com/artie-labs/transfer/pull/354
* `any` is an alias of `interface{}`
> Renaming `interface{}` to `any` Part 1

- lib/config/config_test.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_bigquery_test.go
- lib/destination/dml/merge_test.go
- processes/consumer/process_test.go
Follow up to this PR: https://github.com/artie-labs/transfer/pull/365
* Clean up casing for the default MERGE function
* Fixed tests to use `assert.Contains(...)`
> Clean up casing for MERGE.

- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_test.go
- lib/optimization/table_data.go
Temporary table names to be lowercase by default. This way, we don't need a separate IF statement in `DropTemporaryTable`
> Default to lowercase temp table names

- lib/config/config.go
- lib/kafkalib/topic.go
This is mostly for a QoL improvement for our internal Transfer config generation.
By adding `omitempty`, this will reduce the amount of data from `yaml.Marshal(...)`
> Config - Adding more omitempty

- clients/shared/merge.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_parts_test.go
- processes/consumer/kafka.go
- processes/consumer/process.go
Our merge consolidation a few weeks ago accidentally missed `containsHardDeletes` flag from the Redshift merge: https://github.com/artie-labs/transfer/pull/343/files#diff-87c1374c50373010ae6b2a9951ae46abee85163c403b39b0f1ac32d8bac54c61
This was not caught because the previous flag was a type `bool`. I changed it to a pointer so that we can validate that it has been set.
> Redshift ignoring table deletes

- lib/destination/ddl/ddl.go
This PR: https://github.com/artie-labs/transfer/pull/361 which has not been deployed yet consolidates our sweeping logic.
However, when the sweep query runs, the table names from Snowflake are returned in uppercase format which fails the `strings.Contains(...)` logic and the temporary table does not get deleted.
> [Snowflake] Temporary table fix

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/redshift_bench_test.go
The documentation for Redshift is incorrect regarding JSON objects within a SUPER data type. They are subject to the same character limit as STRINGs.
This PR uses the STRING limit for both STRING and SUPER along with simplifying the current codepath.
> [Redshift] Simplifying casting values

- lib/destination/dml/merge.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
- lib/typing/columns/columns_toast_test.go
1. Adding Microsoft SQL Server tests
2. Renaming `ColumnsUpdateQuery` -> `UpdateQuery` since the pkg name is `columns`
3. Breaking out `struct` and normal TOAST column handling into separate functions
> Improving Columns Update Query

- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
We need to escape the project ID since it could contain special characters.
> [BigQuery] Escape Project ID for fully qualified name

- lib/cdc/util/parse.go
- lib/cdc/util/parse_test.go
- lib/cdc/util/relational_event.go
- lib/debezium/types.go
- lib/typing/ext/time.go
Previously, `parseField` would not emit an error and if the translation failed, it would just return the original value. However, this masked the actual translation error from the caller which makes it hard for other codepaths to reliably call this function.
> [Typing] `parseField` to start emitting an error

- clients/mssql/staging.go
- clients/mssql/values.go
- clients/mssql/values_test.go
Solving for data indigestion.
Because Microsoft SQL Server doesn't support BOOLEANs, some data replication tools will create `BIGINT` as opposed to `BIT` columns.
Transfer then tries to load `boolean` values into a `BIGINT` column which fails the typecheck. We can safely load `boolean` values into a `BIT` column because the underlying Microsoft SQL driver expects and will cast `boolean` values into `BIT` values.
> Fix Microsoft SQL Server booleans

- clients/mssql/values.go
After this PR: https://github.com/artie-labs/transfer/pull/388, `colVal` is already not a boolean, so there's no point in having this check.
`strconv.ParseBool(...)` will handles converting 0/1s into bools.
> [Microsoft SQL Server] Boolean Improvement

- clients/mssql/values.go
- clients/mssql/values_test.go
Imagine a column in Microsoft SQL Server is `VARCHAR(255)`, if the actual value Artie is replicating over is greater than 255 the pipeline would fail.
> [Microsoft SQL Server] Exceeded values guardrail

- lib/jitter/sleep.go
- lib/jitter/sleep_test.go
When `baseMs` and `attempts` are large enough `baseMs * attempts **2` will overflow and become negative, which then causes `rand.Intn` to panic.
> Fix panic when calling `Jitter` with a large number of attempts

- lib/db/errors.go
- lib/db/errors_test.go
We have Datadog logs now, and there are no logs that match the warning.
> Minor TODO.

- processes/consumer/configs.go
- processes/consumer/kafka.go
- processes/consumer/process.go
- processes/consumer/process_test.go
- processes/consumer/pubsub.go
We previously made `ProcessMessage(...)` public for Reader to import this function and directly call it from its codebase. However, this is at the wrong level. Reader would need to add additional overhead of marshaling the raw message into a Kafka message just to unmarshall it back out.
As such, I've changed the function back to private and made it slightly more idiomatic towards Go by having receiver methods.
> Minor code clean up

- go.mod
- go.sum
Version `0.27.0` has a [change for unwrapping errors](https://github.com/getsentry/sentry-go/pull/792) so hopefully this improves error grouping in Sentry.
> Bump sentry to `v0.27.0`

- clients/bigquery/bigquery.go
- clients/mssql/staging.go
- clients/redshift/staging.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- lib/destination/dwh.go
Instead of doing a check to see which mode it is to determine whether or not to create a temporary table, we can just have the caller specify it.
* When you run MERGE, you'll want a temporary table.
* When you run APPEND, you don't want a temporary table.[1]
[1] Exception here is Redshift, where you don't want to append directly to the table, you'll want to create a temporary table and then run `ALTER TABLE APPEND` which does a zero copy clone.
By doing this, it allows Reader to call Append for backfills.
> Explicitly pass in create temporary table flag

- lib/cdc/mongo/debezium_test.go
- lib/cdc/util/parse_test.go
- lib/debezium/schema.go
So that we can reference them in reader.
> [debezium] Add constants for `Field.Type`

- lib/cdc/util/parse_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/debezium/types.go
Adds a handful of `SupportedDebeziumType` constants currently used by reader. Also changes `Field.DebeziumType` to be of type `SupportedDebeziumType`.
> [debezium] Add more `SupportedDebeziumType` constants

- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/debezium/types.go
Also renamed `TimeMicro` to `MicroTime` for consistency.
> [debezium] Add `io.debezium.time.MicroDuration` type

- lib/cdc/util/parse.go
- lib/cdc/util/parse_test.go
- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
- lib/debezium/types.go
- lib/debezium/types_bench_test.go
- lib/debezium/types_test.go
- Support decoding decimals that are either `string` or `[]byte`
- Pull out the logic from `Field.DecodeDecimal` to a new function in `lib/debezium/decimal`
- Add `EncodeDecimal` [from reader](https://github.com/artie-labs/reader/blob/529d2f3181db4586c97be641ad3f520a0ed9ea27/lib/debezium/converters/decimal.go#L11) so that `reader` can just import it and the encoder can live next to the decoder
> [debezium] Support decoding decimals from `[]byte`

- lib/cdc/util/parse.go
- lib/debezium/types.go
Added all the types from `typesThatRequireTypeCasting` to the `default` case in `parseField` so that `typesThatRequireTypeCasting` is no longer needed.
> Simplify `parseField`

- lib/debezium/types.go
- lib/debezium/types_test.go
This way we won't have to marshal and unmarshal rows to/from JSON in order for transfer to be able to handle rows from reader.
> [debezium] Support parsing integer types for integer fields

- lib/jitter/sleep.go
- lib/jitter/sleep_test.go
This way we can test the upper bound values before they pass through `rand.Intn`.
> Pull out jitter upper bounds computation

- lib/jitter/sleep.go
- lib/jitter/sleep_test.go
Inspired by https://github.com/artie-labs/transfer/pull/397, adds a function to safely compute a power of two.
> Clean up `computeJitterUpperBoundMs`

- clients/redshift/redshift.go
- lib/destination/ddl/expiry.go
The current sweep query picks up sequences from the primary key for the temporary table. This PR makes it so that we filter on `relkind`.
Also changing `Failed to parse unix string` to log an error so that we can see it in Sentry.
> [Redshift] Improve Sweep query

- lib/debezium/types.go
- lib/debezium/types_test.go
We've been running https://github.com/artie-labs/transfer/pull/434 for a day with no errors logged, so the old parsing code seems safe to remove.
> [debezium] Use `toInt64` to parse time values

- lib/cdc/postgres/debezium.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_test.go
Today, for our deletes - we do not pass the `before` object through. Which has worked fine, for hard deletes - we only need the primary keys and an indicator on whether the row has been deleted anyways.
However, if we want to use merge predicates which can speed up [merges](https://select.dev/posts/snowflake-merges#:~:text=This%20is%20known%20as%20dynamic%20pruning%2C%20because%20Snowflake%20is%20determining%20which%20micro%2Dpartitions%20to%20prune%20(avoid%20scanning)%20while%20during%20the%20query%20execution%20after%20it%20has%20read%20the%20values%20in%20the%20source%20table.), we'll need to be able to join on non-primary key values such as `created_at`.
This PR opens up the ability to pass through the before state for relational sources. Once this works well, we'll also add this for …
> [Relational Data] Include the Before object

- clients/bigquery/bigquery.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/snowflake/snowflake.go
- lib/destination/dwh.go
That way we can use it to generate a temporary table name for Redshift dedupes.
> Pass `TableIdentifier` to `DataWarehouse.Dedupe`

- clients/bigquery/append.go
- clients/bigquery/bigquery.go
- clients/bigquery/bigquery_test.go
- clients/mssql/store.go
- clients/mssql/store_test.go
- clients/redshift/redshift.go
- clients/redshift/redshift_test.go
- clients/redshift/writes.go
- clients/s3/s3.go
- clients/s3/s3_test.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/temp_table.go
- clients/shared/temp_table_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/writes.go
- lib/destination/dwh.go
Basically just reverts #444. Instead of having a shared `TableIdentifier` struct we'll have a per-data-warehouse struct. This is a prerequisite in order to make that possible.
> Pass `TableData` to `ToFullyQualifiedName` and `Dedupe`

- clients/bigquery/tableid.go
- clients/bigquery/tableid_test.go
- clients/mssql/tableid.go
- clients/mssql/tableid_test.go
- clients/redshift/tableid.go
- clients/redshift/tableid_test.go
- clients/s3/tableid.go
- clients/s3/tableid_test.go
- clients/shared/table_config_test.go
- clients/snowflake/tableid.go
- clients/snowflake/tableid_test.go
- lib/destination/types/types.go
The idea being that we can use these methods to change just the table of an identifier while preserving the schema/database/dataset/project. This will be used for the function that creates temporary table names so that it can return a `TableIdentifier` rather than a fully qualified table name string.
> Add `WithTable` methods to `TableIdentifier`s

- clients/bigquery/append.go
- clients/bigquery/bigquery.go
- clients/bigquery/bigquery_test.go
- clients/bigquery/tableid.go
- clients/bigquery/tableid_test.go
- clients/mssql/store.go
- clients/mssql/store_test.go
- clients/mssql/tableid.go
- clients/mssql/tableid_test.go
- clients/redshift/redshift.go
- clients/redshift/redshift_test.go
- clients/redshift/tableid.go
- clients/redshift/tableid_test.go
- clients/redshift/writes.go
- clients/s3/s3.go
- clients/s3/tableid.go
- clients/s3/tableid_test.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/table_config.go
- clients/shared/table_config_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/tableid.go
- clients/snowflake/tableid_test.go
- clients/snowflake/writes.go
- lib/destination/ddl/ddl_alter_delete_test.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/types/types.go
Instead we'll always attempt to escape table names.
> Remove `escape` argument from `FullyQualifiedName`

- clients/bigquery/tableid.go
- clients/mssql/tableid.go
- clients/redshift/tableid.go
- clients/shared/merge.go
- clients/shared/utils.go
- clients/snowflake/staging.go
- clients/snowflake/tableid.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_parts_test.go
- lib/destination/dml/merge_test.go
- lib/sql/escape.go
- lib/sql/escape_test.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
- lib/typing/columns/wrapper_test.go
`Escape` is always true for non-test code and only ever false in test code.
> [sql] Kill `NameArgs.Escape`

- clients/mssql/store_test.go
- clients/mssql/tableid.go
- clients/mssql/tableid_test.go
- lib/sql/escape.go
When you create a table or column in MS SQL, and do not quote the identifier, the database uses the exact casing that the identifier was supplied in.
```
CREATE SCHEMA teST
CREATE TABLE teST.UPPER (lower INT NOT NULL, UPPER INT NOT NULL, MiXeD INT NOT NULL)
CREATE TABLE teST.lower (lower INT NOT NULL, UPPER INT NOT NULL, MiXeD INT NOT NULL)
CREATE TABLE teST.mIxEd (lower INT NOT NULL, UPPER INT NOT NULL, MiXeD INT NOT NULL)
CREATE TABLE teST.MiXeD1 (lower INT NOT NULL, UPPER INT NOT NULL, MiXeD INT NOT NULL)
```
Result:
```
table    column
-----    ------
UPPER    lower
UPPER    MiXeD
UPPER    UPPER
lower    lower
lower    MiXeD                                                                                                                           
lower    UPPER …
```
> [mssql] Always escape table names

- clients/snowflake/ddl_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/staging_test.go
- clients/snowflake/tableid.go
- clients/snowflake/tableid_test.go
- clients/snowflake/util_test.go
- lib/destination/ddl/ddl_create_table_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/ddl/ddl_temp_test.go
Note that column names will still be uppercased if and only if `SharedDestinationConfig.UppercaseEscapedNames` is set to `true`.
> [snowflake] Always uppercase escaped table names

- clients/redshift/redshift.go
- clients/redshift/tableid.go
- clients/redshift/tableid_test.go
Note that column names will still be uppercased if and only if `SharedDestinationConfig.UppercaseEscapedNames` is set to true.
> [redshift] Don't uppercase escaped table names

- clients/redshift/redshift.go
- lib/config/config.go
- lib/config/config_validate_test.go
Redshift lowercase tables and column names so this setting was misleading.
> [redshift] Remove `uppercaseEscapedNames` support

- clients/bigquery/bigquery.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/shared/table_config_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_dedupe_test.go
- lib/destination/dwh.go
Improving our Snowflake dedupe process which will minimize data movement from the target table, which will execute faster and more reliably.
> Improve Snowflake Dedupe.

- clients/snowflake/snowflake.go
Right now, for history mode / appends, it is susceptible to duplicates when there's a process restart.
The flow goes like this right now:
1. Create local stage and upload data to Snowflake
2. Load data into the target table via COPY INTO
3. Commit Kafka offset
However, if there's a process restart while we're in the midst of step 2, the connection will disconnect, but they query will still keep executing.
When the process then restarts, it will then fetch from the previous offset and keep going. This will result in duplicates.
We're enabling [ABORT_DETACHED_QUERY](https://docs.snowflake.com/en/sql-reference/parameters#abort-detached-query) which should help reduce the amount of duplicates that arise from process restarts.
> [Snowflake] Use Abort Detached Queries.

- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_dedupe_test.go
1. We should use the fully qualified name so we don't need to explicitly call `USE DATABASE`
2. We had an extra `by` within CREATE TABLE
> Snowflake - Fix Dedupe Query

- clients/bigquery/merge_test.go
- lib/destination/ddl/ddl_alter_delete_test.go
- lib/destination/ddl/ddl_create_table_test.go
- lib/destination/ddl/ddl_temp_test.go
- lib/destination/dml/merge_bigquery_test.go
- lib/sql/escape.go
- lib/sql/escape_test.go
- lib/typing/columns/columns_test.go
- lib/typing/columns/wrapper_test.go
Since [BigQuery does not change the case of identifiers when they are not quoted](https://github.com/artie-labs/transfer/pull/489) we should be able to always quote column identifiers. This is based on https://github.com/artie-labs/transfer/pull/501 but BigQuery instead of MS SQL.
> [bigquery] Escape all columns that do not start with "__artie"

- clients/shared/append.go
- clients/shared/merge.go
- lib/optimization/event_update_test.go
- lib/optimization/table_data.go
- lib/typing/bigquery_test.go
- lib/typing/redshift.go
- lib/typing/snowflake_test.go
- lib/typing/typing.go
If we fail to understand the data type from source or destination, we are marking the column as `Invalid` and we do not copy the data over to the destination. This is a silent failure, and this PR makes that an explicit failure so we can be better at data type mapping.
1. We are now going to error out if we fail to map a data type to a data type in the destination
2. We are going to error out if we are unable to understand the data type from the destination after we run describe table
> Standing up guardrails for Invalid Cols

- lib/cdc/postgres/debezium_test.go
- lib/typing/columns/default_test.go
- lib/typing/ext/variables.go
The ISO8601 format we were using did not include ms precision. This PR adds `ms` precision. This will be particularly helpful in history mode, where there may be more than one update within a second for the same row.
> [go] Include MS for ISO8601.

- clients/bigquery/bigquery.go
- clients/bigquery/bigquery_dedupe_test.go
- clients/snowflake/snowflake.go
Improving the way we handle deduping in BigQuery.
This way, we'll create a staging table that has all the duplicate rows.
* It stores the `latest` row in the staging table 
* We then delete all the duplicate rows from the target table
* We then copy the data from staging -> target
* Drop staging table
> Refactoring BigQuery Dedupe

- clients/bigquery/bigquery.go
- clients/mssql/staging.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/redshift/staging.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/table_config_test.go
- clients/snowflake/snowflake.go
- clients/snowflake/staging.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_alter_delete_test.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_create_table_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/ddl/ddl_temp_test.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_bigquery_test.go
- lib/destination/dml/merge_mssql_test.go
- lib/destination/dml/merge_parts_test.go
- lib/destination/dml/merge_test.go
- lib/destination/dml/merge_valid_test.go
- lib/destination/dwh.go
Kill `ShouldUppercaseEscapedNames()` too.
> Remove ` UppercaseEscNames` from `MergeArgument` and `AlterTableArgs`

- clients/mssql/store.go
- clients/mssql/tableid.go
- lib/destination/dml/merge_mssql_test.go
- lib/destination/dml/merge_parts_test.go
- lib/sql/dialect.go
- lib/sql/dialect_test.go
`DefaultDialect` is only used by MS SQL so might as well make it specific.
> [mssql] Rename `DefaultDialect` to `MSSQLDialect`

- clients/snowflake/snowflake.go
- clients/snowflake/tableid.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_test.go
- lib/destination/dml/merge_valid_test.go
- lib/sql/dialect.go
- lib/sql/dialect_test.go
- lib/sql/escape.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
- lib/typing/columns/default_test.go
- lib/typing/columns/wrapper_test.go
Adds a new flag `LegacyMode` to `SnowflakeDialect`. In legacy mode reserved column identifiers are lowercased and non-reserved column identifiers are uppercased. In regular mode all column identifiers are uppercased.
> [snowflake] Always escape column identifiers

- clients/shared/utils.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/dml/merge.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
I'm working on removing `Column.Name` entirely, but I figured this would be a good first step to make the following PRs easier to reason about.
> [typing] Rename `Column.Name`

- lib/destination/dml/columns.go
- lib/destination/dml/columns_test.go
- lib/destination/dml/merge.go
Instead of passing `skipDeleteCol` to `buildColumnsUpdateFragment`, we'll just pass a slice of columns that already has the delete column marker removed.
> [dml] Remove `buildColumnsUpdateFragment` argument

- lib/destination/dml/columns.go
- lib/destination/dml/columns_test.go
- lib/destination/dml/merge.go
- lib/destination/dml/merge_test.go
Just moving things around, no code changes.
> [dml] Move `removeDeleteColumnMarker`

- lib/destination/dml/merge.go
- lib/destination/dml/merge_parts_test.go
- lib/destination/dml/merge_test.go
> [dml] Capitalize keywords in Redshift merge queries

- go.mod
- go.sum
- lib/typing/mongo/bson.go
We are currently on a version from July 2023. 
Reading through the release notes, there should not be any breaking changes. However, they did deprecate certain methods that we relied on, particularly in `bson.go`. 
I followed the examples from this PR, which introduces the deprecation warnings: https://github.com/mongodb/mongo-go-driver/pull/1251
> Upgrading MongoDB Dependency

- lib/config/config.go
- lib/config/config_test.go
- lib/config/constants/constants.go
This PR adds a new queue kind - `reader` which symbolizes our snapshot mechanism of Reader directly importing and running Transfer without Kafka.
This queue kind is necessary as Reader's validation is reliant on Transfer's validate. Transfer's validation currently checks for the presence of Kafka bootstrap server and group id.
> New Queue Kind.

- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
This PR mainly adds guardrails for handling binary data for MongoDB. We will now inspect the `subType` and decide whether it's an UUID or not before parsing.
If it's not a UUID, we will then leave the data in JSON extended format so we don't have any precision loss.
☝️ In addition to this, we are doing the same for RegularExpression and Javascript data types.
> Ensure we support every MongoDB data type

- clients/bigquery/bigquery.go
- clients/mssql/staging.go
- clients/redshift/staging.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/snowflake/staging.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_alter_delete_test.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_create_table_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/ddl/ddl_temp_test.go
Since the  Store/DataWarehouse is now only needed to execute the queries we'll pass it in the `AlterTable` method call.
> [ddl] Pass `Dialect` in `AlterTableArgs`

- go.mod
- go.sum
Seems pretty safe https://github.com/segmentio/kafka-go/releases/tag/v0.4.39
> Bump `kafka-go` to `v0.4.39`

- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/config/constants/constants.go
Following the same pattern that we implemented for Postgres https://github.com/artie-labs/transfer/pull/431, but this time for MongoDB
> Passing along the MongoDB before object

- clients/redshift/dialect/dialect.go
We have pretty thorough tests for Redshift merge queries so this change is fairly safe.
> [redshift] Use table alias constants for merge queries

- go.mod
- go.sum
- https://github.com/segmentio/kafka-go/releases/tag/v0.4.41
- https://github.com/segmentio/kafka-go/releases/tag/v0.4.42
- https://github.com/segmentio/kafka-go/releases/tag/v0.4.43
> Upgrade `kafka-go` to `v0.4.43`

- clients/shared/append.go
- lib/destination/types/types.go
This PR removes all traces of Reader logic and keeps Append simple.
> Simplifying APPEND

- clients/bigquery/merge.go
- clients/bigquery/merge_test.go
- lib/kafkalib/partition/settings.go
- lib/kafkalib/partition/settings_test.go
> [BigQuery] Missed one spot for aliasing

- lib/stringutil/strings.go
- lib/stringutil/strings_test.go
- models/event/event.go
`stringutil.Override` is [equivalent](https://go.dev/play/p/TmpKBQAQjKS) to calling `cmp.Or` with the order of values reversed.
> Replace `stringutil.Override` with `cmp.Or`

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/mongo/mongo_suite_test.go
This is needed because Postgres and MongoDB return JSON objects differently.
* Mongo returns it with the native type e.g.: `map[string]any{}`
* Postgres and others has already JSON marshalled the data by the time we receive it
As a result, `castColVal(...)` must handle structs that have been marshalled already and ones that have not.
> Improve BigQuery `castColVal`

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
We were converting most values to a string and letting the BigQuery API deal with all the type conversions.
This PR makes it so that we stop doing that for ints, floats and booleans. In addition, I also rewrote the tests to be more succinct
> [BigQuery] Improve castColVal function

- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
The way we currently handle parsing MongoDB results has slight inefficiencies and causes us to not be able to delineate between floats and ints.
The current way is:
1. Take JSON extended string
2. Parse that into BSON
3. Run our types registry to convert BSON objects into regular values
4. JSON marshal into `map[string]any`
By running JSON marshal, we are losing the ability to delineate between floats and ints.
This PR directly takes the BSON object and converts it into `map[string]any` natively, without JSON marshal.
This change reduces the time it takes for us to parse by 27% (see below)
```bash
BenchmarkJSONEToMap-12    	  122318	    199390 ns/op
```
```bash
BenchmarkJSONEToMap-12    	  166398	    145455 ns/op
```
> [Typing] Improve the way we parse MongoDB

- clients/redshift/staging.go
By not specifying the columns to load, Redshift is using the order of which columns appear in Redshift.
This PR adds the ability to specify and brings it to parity with Snowflake: https://github.com/artie-labs/transfer/blob/05b6fedcb7677a134fa293361253440c80f618f8/clients/snowflake/staging.go#L98C1-L99C1
> [Redshift] Copy Into to specify column ordering

- clients/bigquery/bigquery.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/shared/merge.go
- clients/shared/sweep.go
- clients/snowflake/snowflake.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_test.go
- lib/kafkalib/topic.go
- lib/kafkalib/topic_test.go
1. Removing DatabaseSchemaPair and standardize on TopicConfig
2. Changed the function to be O(n) and guarantee ordering
3. `DropTemporaryTable` now takes a `TableIdentifier` vs `tableName`
> `DropTemporaryTable` to take a `TableIdentifier`

- lib/debezium/types.go
- lib/debezium/types_test.go
- lib/typing/parse.go
There's an edge case right now with DateTimeWithTimeZone
Consider this, when Debezium gives us the field, it'll look like this:
```json
{
"type": "string",
"optional": false,
"name": "io.debezium.time.ZonedTimestamp",
"version": 1,
"field": "due_date"
}
```
As a result, the string can look something like this: 
```
+275760-09-13T00:00:00.000000Z
```
This will fail the Go `time.Time` parsing logic. However, this is technically a validate datetime in Postgres.
> [DateTime] Solve Edge Case

- clients/redshift/staging.go
- lib/destination/ddl/ddl.go
- models/event/event.go
- models/event/event_test.go
This PR addresses a bug where if we have a mixed case primary key column such as `fooBar`, we will end up with 2 columns: `foobar` and `fooBar`
> ToMemoryEvent - Edge case w/ primary keys

- clients/redshift/cast.go
- clients/redshift/cast_test.go
By default, Redshift strings and super data types have a precision limit of 2^16.
However, a customer can optionally specify this such as `status character varying(765)`. This PR adds the ability for us to respect the optional string precision
> Improve Redshift casting

- clients/bigquery/bigquery.go
Instead of calling `tableData.ReadOnlyInMemoryCols()` (which creates a copy of the columns) once per row we can just call it once per batch of rows. We can also use `tableData.ReadOnlyInMemoryCols().ValidColumns()` which is logically the same as `tableData.ReadOnlyInMemoryCols().GetColumnsToUpdate()` except that it returns a `Column` instead of the column name as a string, which avoids the need for the subsequent call to `tableData.ReadOnlyInMemoryCols().GetColumn(col)`.
> [bigquery] Improve `PrepareTemporaryTable` performance 

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/redshift.go
- clients/redshift/redshift_suite_test.go
- lib/config/config.go
- lib/debezium/types.go
- lib/debezium/types_test.go
1. Removing `skipLgCols` and default it to true, as this should not be an optional setting and we have hardcoded this to be true from our dashboard
2. Addressing TODO as we have not seen any Sentry errors
> Minor clean up

- clients/bigquery/bigquery.go
The rows that the Storage Write API use will need to be different from the rows we're currently building.
> [bigquery] Split out legacy API row building

- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
If a decimal's precision or scale [exceeds BigQuery's limits](https://github.com/artie-labs/transfer/blob/7caa28799a6ce49316d1ea4e96adc96421e67490/lib/typing/decimal/decimal.go#L86-L94), we will cast the column as a string.
However, the BigQuery API does not like it when we pass in a custom type `*decimal.Decimal` into a column that is a string.
Instead, we should return the string value.
> [BigQuery] Edge case with our decimal types

- processes/consumer/flush.go
This accounts for ~ 12% of our log usage for Transfer in Datadog.
This is also not particularly useful, let's change this to be `Debug` instead
> Log this as debug.

- clients/bigquery/bigquery.go
- clients/bigquery/cast.go
- clients/bigquery/cast_test.go
- go.mod
- go.sum
- lib/config/bigquery.go
Breaking out some parts of the Storage Write API PR I'm working out.
> [bigquery] Add scaffolding for the Storage Write API

- clients/bigquery/bigquery.go
- clients/bigquery/dialect/dialect.go
- clients/bigquery/merge.go
- clients/mssql/dialect/dialect.go
- clients/redshift/dialect/dialect.go
- clients/shared/merge.go
- clients/snowflake/dialect/dialect.go
- lib/config/bigquery.go
- lib/sql/dialect.go
The BigQuery streaming API (InsertAll or Storage Write) do not guarantee exactly once semantics. This means that we'll need to de-duplicate the staging tables before we merge them into the target table.
This PR does exactly that.
> [BigQuery] Use StorageWrite API + Dedupe

- clients/bigquery/bigquery.go
- clients/bigquery/bigquery_dedupe_test.go
- clients/bigquery/bigquery_test.go
- clients/mssql/store_test.go
- clients/redshift/redshift.go
- clients/redshift/redshift_dedupe_test.go
- clients/redshift/redshift_test.go
- clients/shared/merge.go
- clients/shared/temp_table.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_dedupe_test.go
- clients/snowflake/snowflake_test.go
Renames `TempTableID` to `TempTableIDWithSuffix` and adds a new `TempTableID` function that does not take a `suffix` argument.
> Add `TempTableIDWithSuffix` function

- lib/destination/ddl/ddl.go
Snowflake tables come back as upper case, the previous PR that refactored this codepath didn't take into account lowercasing the table names.
https://github.com/artie-labs/transfer/commit/d6146a6f3fe4a360b39f0f9265a2aaaec07fd437#diff-a50f63a1ea9f7fdae96c789d0ed7e697b165abbc8acf7912f0a89cd2d67bf2f4
> [ddl] Drop Temp Table fix.

- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
Our previous library was susceptible to precision loss when converting from a `big.Float` into a `big.Int`. Repro: https://go.dev/play/p/qg8NODRlxi5
> [Decimal] Fix Encoding Problem

- clients/bigquery/bigquery.go
If we don't specify column names, it'll use the natural order which may not be consistent between staging and target.
> [BigQuery] Specify column names for Append

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/shared/merge.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
Transfer leverages an in-memory database that is key-value based.
The key being the primary key(s) of the table and the value is the latest row as we leverage Kafka for ordering guarantee.
The problem is that if there are 2 events within one flush cycle say:
- t0, event was created for id = 1
- t1, event was deleted for id = 1
When we flush, we'll only have the latest deleted row. Our merge logic for handling soft deletes was incorrect as it wrongfully assumed that the row should be in the target table.
```sql
MERGE INTO foo.public."bar" tgt USING ( foo.public."bar" ) AS stg ON tgt."id" = stg."id" AND tgt."user_id" = stg."user_id"
WHEN MATCHED THEN UPDATE SET "id"=stg."id","user_id"=stg."user_id","__ARTIE_DELETE"=stg."__ARTIE_DELETE","__ARTIE_UPDATED_AT"=stg."__ARTIE_UPDATED_AT"
WHEN NOT …
```
> Soft Delete bug

- clients/bigquery/bigquery.go
- lib/config/bigquery.go
> [bigquery] Increase Storage Write API max request size

- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
I'm working on removing `GetColumnsToUpdate` since it returns similar data to `ValidColumns`.
> Add `ColumnNames` function

- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
> Use uint16 for `EncodeDecimal`

- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
When encoding a negative decimal number we have to convert the bytes into two's complement. In two's complement the first bit is reserved for the sign, however for certain numbers the sign is already a positive, so in that case we need to pad the output by one empty byte so that the first bit can safely be set to 0 without changing the value. Specifically we were encoding values `-65,281` through `-65,535` incorrectly.
> [go] Fix bug with encoding negative decimal numbers

- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
Fixes `unable to use "0.000022998904125" as a floating-point number`.
> [debezium] Fix bug in `EncodeDecimal`

- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
- Use `big.Float.Int()` when `big.Float.IsInt()` is true
- Improve error message in the case that `big.Int.SetString()` fails
> [debezium] Optimize `EncodeDecimal`

- go.mod
- go.sum
- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
While doing some testing I discovered that if we encode and decode `-9063701308.217222135` with `EncodeDecimal`/`DecodeDecimal` the result comes back as `-9063701308.217222134`. In order to fix this and mitigate other potential issues with decimals this switches us to use https://github.com/cockroachdb/apd for decimals.
> [debezium] Fix bug with `EncodeDecimal`

- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
`EncodeDecimal` is only called by Reader in two places, and in one of those places we already have code to determine the scale, which is something we can simplify if we have a `apd.Decimal`, so rather than depend on Transfer to parse strings into encoded `org.apache.kafka.connect.data.Decimal`s we'll let Reader handle the parsing to `apd.Decimal` and just let Transfer handle the encoding.
> [debezium] Change function signature of `EncodeDecimal`

- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
Step 1 of not clearing out the values of a row when it's soft deleted.
If a row is updated and then deleted before the next flush, we have its previous values in memory so we can use those and just add the deleted flag.
> When soft deleting, preserve previous values if we have them in memory

- lib/cdc/util/optional_schema_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/optimization/event_update_test.go
- lib/parquetutil/parse_values_test.go
- lib/typing/decimal/base.go
- lib/typing/decimal/decimal.go
- lib/typing/decimal/details.go
- lib/typing/decimal/details_test.go
- lib/typing/numeric.go
- lib/typing/parse.go
- lib/typing/typing.go
This way `decimal.Decimal` is just used for storing decimal values and not details about numeric columns.
> [typing] Split out `DecimalDetails`

- clients/bigquery/dialect/dialect_test.go
- clients/mssql/dialect/dialect_test.go
- clients/redshift/dialect/dialect_test.go
- clients/snowflake/dialect/dialect_test.go
- lib/cdc/util/optional_schema_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/optimization/event_update_test.go
- lib/parquetutil/parse_values_test.go
- lib/typing/decimal/base.go
- lib/typing/decimal/decimal.go
- lib/typing/decimal/decimal_test.go
- lib/typing/decimal/details.go
- lib/typing/decimal/details_test.go
- lib/typing/numeric.go
- lib/typing/numeric_test.go
- lib/typing/parquet.go
Instead of having two ways to indicate no precision set (`nil` and `-1`) we'll use `-1`.
> [typing] Remove pointer for `DecimalDetails` precision

- clients/bigquery/bigquery.go
Sometimes 50 kb isn't enough.
I tried 150 kb, still got paged. Increasing it to 250.
> [BigQuery] 250 kb instead of 50kb.

- lib/cdc/util/optional_schema_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/optimization/event_update_test.go
- lib/parquetutil/parse_values_test.go
- lib/typing/decimal/base.go
- lib/typing/decimal/decimal.go
- lib/typing/decimal/decimal_test.go
- lib/typing/decimal/details.go
- lib/typing/decimal/details_test.go
- lib/typing/numeric.go
- lib/typing/typing.go
1. Renaming DecimalDetails -> Details
2. Removing pointers since it's unnecessary
> Decimal clean up.

- clients/shared/merge.go
- clients/snowflake/snowflake_test.go
The problem is that `PrepareTemporaryTable` may actually end up creating a temporary table and fail to load the data in.
If it fails to load data into it, it will then immediately return and the temporary table will not get dropped until much later
> Moving defer dropping temporary table up

- lib/kafkalib/connection.go
- lib/kafkalib/connection_test.go
- processes/consumer/kafka.go
This PR creates a `Connection` struct that can be turned into a Dialer and Writer. 
This will remove the boilerplate in our dashboard and Reader.
> [Kafka] Refactor the way we handle Kafka connections

- lib/kafkalib/connection.go
Don't use `context.Background()`, just have it passed in instead.
> [Kafka] Pass Context in

- lib/kafkalib/connection.go
So we can do things like this
```go
cfg, err := awsCfg.LoadDefaultConfig(ctx, awsCfg.WithRegion("us-west-2"))
```
> [Kafka] Adding `awsOptsFn`

- lib/config/config_test.go
- lib/typing/parse.go
- lib/typing/parse_test.go
- lib/typing/typing.go
If the schema is available, let's return the type even if the value is null. This is the more desirable behavior and we have been setting this to true on our managed deployments for some time now.
> Deprecate `createAllColumnsIfAvailable` setting

- clients/snowflake/dialect/dialect_test.go
Following https://github.com/artie-labs/transfer/pull/792, this removes the subquery from the other snowflake test cases that used one.
I also added a helper function to build the columns in a deterministic order so each test case doesn't have to implement that separately.
> Clean up more snowflake dialect tests

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- clients/snowflake/snowflake_test.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_test.go
- lib/config/constants/constants.go
- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
- lib/sql/columns.go
- lib/typing/columns/columns.go
- lib/typing/columns/diff.go
- models/event/event.go
- models/event/event_test.go
- processes/consumer/flush_test.go
When a row is soft-deleted, now we'll preserve the previous values of all the columns (other than the `__artie_delete` column) instead of overwriting them all to be empty.
- Added a temporary column marker to indicate if a row should have only its `__artie_delete` column updated
- Made snowflake's merge function check that value to decide how to merge
- Made all dialects filter out this temporary column before merging so it doesn't end up in the destination
As a followup, I'll make the other dialects use the new marker when merging.
> Snowflake: don't null out column values when soft-deleting

- clients/bigquery/dialect/dialect.go
- clients/mssql/dialect/dialect.go
- clients/redshift/dialect/dialect.go
- clients/snowflake/dialect/dialect.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
In all the places these are called, if the column wasn't present then the caller returns an error. Instead, these two util functions can just build the error themselves.
> Make RemoveDeleteColumnMarker and RemoveOnlySetDeletedColumnMarker return error instead of bool

- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
In the same vein as #796 and #800.
^ row 1028 was deleted before these changes, so the other values were nulled out. Rows 1029-1031 were deleted with these changes, so the previous values were preserved. For rows 1030 & 1031, I included multiple operations in a single flush (c + u + d, u + d) to verify that the latest in-memory values were preserved.
> Update redshift merge logic to not null out values when soft-deleting

- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
MS SQL [doesn't allow](https://learn.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver16#when-matched-then-merge_matched) multiple `WHEN MATCHED THEN UPDATE` clauses, so in https://github.com/artie-labs/transfer/pull/804 I converted it to use insert + update statements instead. This PRs adds an extra update statement to handle only updating the `__artie_delete` field if we're soft-deleting a row and don't have the previous values in memory.
> Update ms sql merge logic to not null out values when soft-deleting

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
- clients/shared/merge.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- lib/sql/dialect.go
Step 1 of removing support for `idempotentKey`
> Remove idempotentKey from BuildMergeQueries()

- clients/bigquery/bigquery.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/shared/table_config.go
- clients/shared/table_config_test.go
- clients/snowflake/snowflake.go
As part of simplifying the way we retrieve table config, this PR removes the need to specify what an "empty" comment looks like by having better parsing.
> [Table Config] Removing empty comment as a struct

- lib/debezium/converters/time.go
We should not be returning `ext.ExtendedTime` here since if it returned nil, it would hinder the actual nil check of the caller if the caller expected the value type to be `any`.
https://go.dev/play/p/YCcxbjF5ne3
> [Time] Addressing type safety

- processes/consumer/kafka.go
- processes/consumer/pubsub.go
While reading through our consumer logic, I noticed that we would skip a message if we encountered a payload that we are unable to process. Skipping rows may result in data loss. 
Instead, we should be panicking which will block our consumer from advancing automatically.
> Panic if failed to process message

- lib/destination/dwh.go
We can simplify this interface by embedding `Baseline` into `DataWarehouse`
> Simplify interface

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/staging.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- lib/optimization/event_update_test.go
- lib/typing/values/string.go
- lib/typing/values/string_test.go
1. Adding more tests and refactoring existing ones
2. `colKind` was actually just the `columns.Column` object before. We are now passing the actual `KindDetails` struct instead.
> Tightening variable + tests

- lib/mocks/generate.go
- models/event/event_test.go
- models/event/events_suite_test.go
Removing the need to hardcode a fake event that matches the `cdc.Event` interface. Standardizing this on counterfeiter mocks instead
> Removing fake event

- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
As part of validating MongoDB streaming, I noticed we weren't handling `CodeWithScope` and also we were wrongfully assuming that BinData will be only 16 bytes. 
In MongoDB, you can create a BinData with any arbitrary value and assign whichever subtype you want.
> MongoDB clean up

- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/relational/debezium.go
- lib/cdc/relational/debezium_test.go
- processes/consumer/process.go
As part of our MongoDB streaming validation, I noticed that we were calling `typing.ParseValue` with the purpose of checking if the field is a struct or not. 
Instead, we can just call rely on reflect and remove the need to call `ParseValue`, which also simplifies the signature.
> [MongoDB] Remove calling `typing.ParseValue`

- .github/workflows/gha-go-test.yml
https://github.com/dominikh/go-tools/releases/tag/2024.1
> Bump staticcheck to `2024.1`

- clients/bigquery/storagewrite.go
- lib/typing/assert.go
- lib/typing/assert_test.go
It's currently a private function here: https://github.com/artie-labs/reader/blob/86be21ae801eef22cfa4af4dd3a8e19abcf0cf29/lib/s3lib/dynamodb_export.go#L10
Bringing it to Transfer so all of our codebases can use it
> [Typing] Bring assert into Transfer

- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/relational/debezium_test.go
- lib/cdc/util/relational_event.go
- lib/typing/ext/variables.go
Right now, we're returning `updated_at` back as a string. This then leads us to do additional parsing downstream
> [DateTime] Return `ext.ExtendedTime` as opposed to `string`

- lib/destination/ddl/expiry.go
- lib/destination/ddl/expiry_test.go
Similar logic to https://github.com/artie-labs/transfer/blob/060ed44aa26a31af73c38a0b55e29a74626d4eef/lib/destination/ddl/ddl.go#L22
> More guardrails around `ShouldDeleteFromName`

- lib/retry/retry.go
- processes/consumer/flush.go
Simplifying our flush function to do the following:
1. Get rid of the concept of "retryable errors", this approach doesn't scale (There are far too many errors, and we'd be spending most of our time trying to chase down edge cases)
2. Split Flush into two separate function and implement the Retryable framework
The intended outcome of this PR is to have the ability to retry a few times (with some jitter) after we first fail to merge or append. The previous approach would wait until the next flush cycle to retry, rather than retry right away.
By doing this, this should help alleviate intermittent errors and make our monitor less flakey.
> Simplifying Flush

- lib/debezium/decimal.go
- lib/debezium/decimal_test.go
Moving this [to reader](https://github.com/artie-labs/reader/pull/476).
> Remove `debezium.EncodeDecimalWithScale`

- .goreleaser.yaml
Fixes: 
> DEPRECATED:  snapshot.name_template  should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info
> Change deprecated goreleaser property

- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
Refactoring `ParseFromInterface` by expecting the value to be either `*ExtendedTime` or `string` type.
The overall goal of this is to clean up how we call `ParseExtendedDateTime`
> Refactoring `ParseFromInterface`

- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/mongo/mongo_bench_test.go
- lib/cdc/relational/debezium.go
- lib/cdc/relational/debezium_test.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_decimal_test.go
- lib/cdc/util/relational_event_test.go
- models/event/event.go
- models/event/event_save_test.go
- models/event/event_test.go
- processes/consumer/configs.go
- processes/consumer/flush_test.go
- processes/consumer/kafka.go
- processes/consumer/process_test.go
- processes/consumer/pubsub.go
We don't need it to be a pointer, so let's remove it and simplify
> Removing `kafkalib.TopicConfig` as a pointer

- clients/shared/default_value.go
- lib/debezium/converters/string.go
- lib/debezium/converters/string_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
UUIDs are passed in as strings, this is a passthrough converter.
> [Debezium] Adding String / UUID passthrough converter

- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
Instead of returning the string value in which we then try to parse to get `ext.ExtendedTime` type in `parseValue`, we can just natively return this.
This way, `parseValue` can take this directly and skip the inference.
> [MongoDB] BSON parse to return `*ext.ExtendedTime` rather than string

- lib/debezium/schema.go
We should be able to natively handle every single Debezium or native type. This log will help us identify any unhandled types (if any).
> Add warning for unhandled field / debezium type.

- lib/debezium/types.go
We were not logging the data type or value before, this PR adds that as log fields.
> Adding logging default value + type.

- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/debezium/types.go
Debezium passes LTree value as a string.
> [Debezium] Adding LTree support.

- lib/cdc/mongo/debezium_test.go
- lib/typing/parse.go
- lib/typing/parse_test.go
- models/event/event_save_test.go
All date, time, datetime and timestamp values are natively handled in the BSON and Debezium converters.
There is no need to do this anymore.
> [Typing] Stop implicit references of datetime in ParseValue

- clients/snowflake/snowflake_test.go
- lib/cdc/relational/debezium_test.go
- lib/typing/parse.go
- lib/typing/parse_test.go
- lib/typing/typing_bench_test.go
- models/event/event.go
> [Typing] Remove passing in `typing.Settings` to `ParseValue`

- lib/debezium/types.go
We were only accounting for a zero value of `time.Time`. We were not counting for zero value of unix time.
> [Debezium] Improve Default Values

- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/relational/debezium_test.go
- lib/cdc/util/optional_schema.go
- lib/cdc/util/optional_schema_test.go
- lib/cdc/util/relational_event_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- models/event/event.go
Addressing the TODO by returning an error along with `typing.Invalid` when parsing fails.
> [Debezium] Converters clean up

- clients/bigquery/dialect/dialect_test.go
- clients/snowflake/dialect/dialect_test.go
- lib/optimization/table_data.go
- lib/sql/util.go
- lib/typing/numeric.go
- lib/typing/numeric_test.go
We have been treating `NUMERIC(p, 0)` as an integer. However, we can actually just parse it as `NUMERIC(p, 0)` instead.
This will allow us to simplify our column merging logic.
> Better handling of `NUMERIC(p, 0)`

- lib/typing/decimal/decimal.go
- lib/typing/decimal/decimal_test.go
- lib/typing/ext/time.go
- lib/typing/ext/time_test.go
- lib/typing/values/string.go
- lib/typing/values/string_test.go
Our custom data types (Decimal and ExtTime) previously did not implement JSON marshal. 
This caused issues as we can have nested objects in MongoDB that had these custom data types. When we then ran `JSON.marshal(...)`, these types would then provide a zero value.
> Adding JSON marshal to custom types

- clients/shared/default_value.go
- clients/shared/default_value_test.go
With this PR: https://github.com/artie-labs/transfer/pull/893, we now treat columns that are `NUMERIC(p, 0)` which are integer columns as `ExtendedDecimal` type with scale of 0.
This means that we can have default values that are integers. This PR adds handling for that.
> [Typing] Default Value

- lib/kafkalib/connection.go
- lib/kafkalib/connection_test.go
If IAM is enabled while username and password are set, let's defer to IAM.
> Patch Kafka connection mechanism

- clients/bigquery/storagewrite.go
- clients/mssql/values.go
- clients/shared/default_value.go
- clients/shared/default_value_test.go
- lib/optimization/table_data.go
- lib/parquetutil/parse_values.go
- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/typing.go
- lib/typing/values/string.go
- lib/typing/values/string_test.go
In this PR, we are refactoring `ParseFromInterface` to take `ExtendedTimeKindType` so we know what we need to be parsing against.
This way, for `DateTime` types, we don't need to try and parse layouts that are targeted for `DATE` and `TIME`.
> [Typing] ParseFromInterface to take ExtendedTimeKindType

- lib/config/snowflake.go
- lib/cryptography/cryptography.go
- lib/cryptography/cryptography_test.go
Adding a hashing function so we can support column level hashing
Benchmark results:
```
goos: darwin
goarch: arm64
pkg: github.com/artie-labs/transfer/lib/cryptography
cpu: Apple M2 Max
BenchmarkHashValue
BenchmarkHashValue-12    	 3264477	       360.5 ns/op
PASS
```
> Adding a Hashing function

- lib/typing/ext/parse_test.go
- lib/typing/ext/variables.go
After this PR: https://github.com/artie-labs/transfer/pull/896, we are now strict about time parsing.
As such, this PR adds support for [UTC layout](https://www.utctime.net/z-time-now)
> Adding an additional timestamp layout.

- lib/optimization/table_data.go
- lib/optimization/table_data_merge_columns_test.go
- lib/typing/ext/time.go
We have not see the warning "Skipping columns" in our logs, so we should be safe to simplify the logic.
In doing so, I also refactored some of our tests.
> Simplifying Merge Columns

- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
- lib/debezium/schema.go
- lib/debezium/schema_test.go
- lib/debezium/types.go
Renaming the variable to be what Debezium calls it (`io.debezium.time.ZonedTimestamp`)
> Renaming DateTimeWithTimezone -> ZonedTimestamp

- lib/kafkalib/partition/settings_test.go
- lib/parquetutil/parse_values_test.go
> Rewrite tests.

- models/event/event.go
- models/event/event_test.go
Returning an error instead of a boolean so it's more descriptive
> Refactor validating event

- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
- lib/optimization/table_data.go
- lib/typing/typing.go
This PR adds the ability for us to better infer different integer types within Redshift. Today, we are treating all integer kinds as `typing.Integer` and creating `INT8` columns for them.
This PR will add the ability for us to better detect `INT2` and `INT4` data types.
> [Typing] Support different Redshift Integers

- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- processes/consumer/process_test.go
1. We don't see anything in our logs in the past 15d. 
2. I've also tested this and it works as expected.
To be extra safe, let's have it return an error if the primary key doesn't exist or there's a value mismatch in the payload. After some time, we can then remove it.
> [MongoDB] Return error instead of logging a warning on primary key presence in `retData`

- lib/config/constants/constants.go
- lib/config/destination_types.go
- lib/config/destinations.go
- lib/config/destinations_test.go
- lib/config/types.go
- lib/db/db.go
The goal of these PRs is to add Databricks as a supported destination. The main working PR can be found here https://github.com/artie-labs/transfer/pull/937
This PR adds the basic Databricks config and tests.
> Supporting Databricks - Part one

- lib/typing/decimal/details.go
TEXT doesn't exist, we should use VARCHAR(MAX)
> [Typing] MSSQL - Use `VARCHAR(MAX)` instead of `TEXT` for decimals that have exceeded precision

- .github/workflows/gha-go-test.yml
`make race` already runs tests, so we don't need to run tests a second time.
> github: run tests just once

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/staging.go
- lib/config/types.go
This is the first PR to enable automatic string precision for Redshift. 
This PR adds the config flag to opt-in, as well as refactoring the helper methods to emit a new length (if deemed necessary).
Once this is done, we'll then need to update the columns and build the necessary dialects.
> [Redshift] Increase string precision - part one

- clients/bigquery/bigquery.go
- clients/bigquery/merge.go
- clients/databricks/store.go
- clients/mssql/staging.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/redshift/staging.go
- clients/s3/s3.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
- clients/snowflake/writes.go
- lib/destination/dwh.go
- processes/consumer/flush.go
Remove the need to have adhoc `context.Background` and start passing `context.Context` through from the main functions.
Once this PR lands, we will only initialize context in `main.go`.
> Pass `context.Context` through for `MERGE` and `APPEND`

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/databricks/dialect/typing.go
- clients/mssql/dialect/dialect.go
- clients/redshift/dialect/dialect.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- lib/typing/numeric.go
- lib/typing/numeric_test.go
Have `ParseNumeric` return `typing.Invalid` along with an error rather than just that the column is invalid, so we can be more explicit.
> Addressing TODO

- clients/bigquery/bigquery.go
Had a failing `AppendRow` request where we were off by 27kb. Bumped from 250 kb to 400 kb so we have a healthy buffer, so we don't have to keep tweaking this.
> Tweak `maxRequestByteSize` for BigQuery

- clients/shared/merge.go
- lib/typing/columns/columns.go
- lib/typing/columns/columns_test.go
- models/event/event.go
Adding this in so we can have an extra guardrail to address https://github.com/artie-labs/transfer/pull/955#discussion_r1802191197
> Update UpsertColumn to include an error response

- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
We were relying on the presence of the `after` object instead of the `operation`.
This caused a bug with one of our deployments where the operation is deleted and the after map contains the primary key of the row.
> Fix MongoDB bug

- clients/shared/default_value_test.go
- clients/snowflake/dialect/dialect_test.go
- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
- lib/debezium/schema_test.go
- lib/optimization/table_data_merge_columns_test.go
- lib/optimization/table_data_test.go
- lib/parquetutil/parse_values_test.go
- lib/typing/ext/parse.go
- lib/typing/ext/time.go
- lib/typing/ext/time_test.go
- lib/typing/mongo/bson_test.go
* Addressing PR comments
* Adding the concept of default layout
* Removing NestedKind variables (that were seldomly used)
> [ExtendedTime] More clean up

- clients/snowflake/snowflake_test.go
- lib/cdc/relational/debezium_test.go
- lib/typing/parse.go
- lib/typing/parse_test.go
- lib/typing/typing_bench_test.go
- models/event/event.go
Instead of returning `Invalid`, in which we then just ignore - let's explicitly return an error so we can ensure that all values flowing through Transfer are being correctly typed and captured.
> [Typing] Return error if it's an unexpected type

- clients/databricks/dialect/dialect_test.go
- clients/snowflake/dialect/dialect_test.go
- lib/destination/types/table_config_test.go
- lib/optimization/table_data_test.go
- models/event/event.go
Since Go 1.22 `sort.Strings` [just calls](https://github.com/golang/go/blob/ad7f736d8f51ea03166b698256385c869968ae3e/src/sort/sort.go#L178) `slices.Sort`.
> Replace `sort.Strings` with `slices.Sort`

- clients/bigquery/storagewrite.go
- clients/mssql/values.go
- clients/shared/default_value.go
- clients/shared/default_value_test.go
- lib/optimization/table_data.go
- lib/parquetutil/parse_values.go
- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/values/string.go
- lib/typing/values/string_test.go
As the title states. The goal is to eventually get rid of `ExtendedTime` altogether.
> Use `time.Time` in more places

- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/ext/variables.go
Addressing the TODO that stemmed from: https://github.com/artie-labs/transfer/pull/976
Also, renaming `parseDateTime` to `parseTimestampTZ`
> [time] Supporting `TIMESTAMP_NTZ`

- lib/debezium/converters/date.go
- lib/debezium/converters/date_test.go
- lib/debezium/converters/time_test.go
- lib/debezium/converters/timestamp_test.go
- lib/debezium/schema_test.go
- lib/debezium/types_test.go
- lib/typing/mongo/bson_test.go
- lib/typing/values/string_test.go
1. Specifying layout for Date
2. Updating all the places we used to call `ExtendedTime.String()` to go through `GetTime()`
> More refactor around extended time

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/bigquery/storagewrite_test.go
- clients/databricks/dialect/typing.go
- clients/databricks/dialect/typing_test.go
- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/redshift/dialect/typing.go
- clients/redshift/dialect/typing_test.go
- clients/snowflake/ddl_test.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- clients/snowflake/snowflake_test.go
- lib/debezium/converters/date.go
- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
- lib/debezium/converters/timestamp.go
- lib/debezium/converters/timestamp_test.go
- lib/debezium/schema_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/optimization/table_data_merge_columns_test.go
- lib/optimization/table_data_test.go
- lib/typing/columns/diff_test.go
- lib/typing/typing.go
So we can standardize on the new method in which it will set a default layout if one is not provided.
Once this is merged, the only places where we will be calling `OldNewExtendedTimeDetails` is in the Debezium converters and that will be cleaned up in a separate PR.
> [ExtendedTime] Remove references for `OldNewExtendedTimeDetails`

- clients/bigquery/converters/converters.go
- clients/bigquery/converters/converters_test.go
- clients/bigquery/storagewrite.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- lib/optimization/table_data.go
- lib/optimization/table_data_merge_columns_test.go
- lib/typing/ext/time.go
- lib/typing/typing.go
- lib/typing/values/string_test.go
More changes, including removing the `.String()` method. 
I added comments to every major change in the PR.
> More refactor around `ExtendedTime`

- clients/bigquery/storagewrite.go
- clients/bigquery/storagewrite_test.go
As per title.
This including the encoding algo for DATETIME
> [BigQuery] Supporting TIMESTAMP_NTZ

- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
- lib/debezium/schema_test.go
- lib/typing/ext/parse_test.go
- lib/typing/ext/variables.go
Going through the code and cleaning up Extended time, I found a bug where we are not preserving the timezone from the value.
This PR fixes that and also added a test case to prevent regression.
> [Extended Time] Preserve timezone (if exists)

- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/typing/ext/time.go
- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
- lib/typing/parse.go
- lib/typing/values/string.go
Refactoring MongoDB to use `time.Time` instead of `ExtendedTime`
> [MongoDB] To not use Extended Time

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/bigquery/storagewrite.go
- clients/bigquery/storagewrite_test.go
- clients/databricks/dialect/typing.go
- clients/databricks/dialect/typing_test.go
- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/redshift/dialect/typing.go
- clients/redshift/dialect/typing_test.go
- clients/shared/default_value.go
- clients/shared/default_value_test.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- lib/debezium/converters/date.go
- lib/debezium/converters/date_test.go
- lib/debezium/schema_test.go
- lib/optimization/table_data.go
- lib/optimization/table_data_merge_columns_test.go
- lib/optimization/table_data_test.go
- lib/parquetutil/parse_values.go
- lib/parquetutil/parse_values_test.go
- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/ext/time.go
- lib/typing/parquet.go
- lib/typing/typing.go
As the title suggests, we're now pulling `DATE` out of `ExtendedTime`. 
Once merged, we'll pull `TIME`, with the goal of completely deprecating `ExtendedTime`
> Pulling `DATE` out of `ExtendedTime` and into a separate data type

- lib/debezium/types.go
- lib/debezium/types_test.go
Now that we are passing in native `time.Time`, our default logic should check for that as well.
> Consider `time.Time` as a default value

- clients/bigquery/converters/converters.go
- clients/bigquery/converters/converters_test.go
Adding support for `DATE` and `TIMESTAMP_NTZ` when the column type is a `STRING` in BigQuery
> [Extended Time] Additional follow up

- clients/bigquery/storagewrite.go
- clients/mssql/values.go
- clients/shared/default_value.go
- lib/optimization/table_data.go
- lib/parquetutil/parse_values.go
- lib/typing/ext/parse.go
- lib/typing/ext/parse_test.go
- lib/typing/values/string.go
`ParseXFromInterface()`-> `ParseXFromAny()`
> Rename parse functions

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/databricks/dialect/typing.go
- clients/mssql/dialect/dialect.go
- clients/redshift/dialect/typing.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
We were being inconsistent in mapping data types that we get from the destination
> `KindForDataType` should return error if unable to map data types

- clients/bigquery/bigquery.go
- lib/batch/batch.go
- lib/batch/batch_test.go
* Right now, BySize will hard fail if a single row exceeds `maxSizeBytes`. 
* Added a flag called `failIfRowExceedsMaxSizeBytes` which will be set to `false` by Reader so that we can log the problematic row and keep going
* Added a method to check if the item contains a function called `Key()` so we can log the problematic row out if it exists.
> Refactor BySize

- clients/databricks/dialect/dialect_test.go
- clients/redshift/dialect/dialect_test.go
- clients/snowflake/dialect/dialect_test.go
- lib/typing/parquet.go
- lib/typing/parquet_test.go
- lib/typing/typing.go
Missed adding TimestampTZ and TimestampNTZ when they got pulled out into separate data types.
Additional changes
1. Removed `typing.ETime`
2. Added tests
> Adding missing types to Parquet

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/redshift_bench_test.go
- lib/typing/ptr.go
- lib/typing/ptr_test.go
We can actually store rows up to 16mb in size into a Redshift SUPER column if the value is a JSON object or an array.
If we are storing other data types (such as string) into a SUPER column, then the native DDL limits will apply. In this case, if we stored a string value into a SUPER data type, we need to adhere to the 2^16 limit rather than the 16 mb limit.
> [Redshift] Better handling of `SUPER` data types

- lib/typing/typing.go
- lib/typing/typing_test.go
There's a `json.Valid` function, let's use it.
It's also more performant.
```
goos: darwin
goarch: arm64
pkg: github.com/artie-labs/transfer/lib/typing
cpu: Apple M2 Max
BenchmarkIsJSON
BenchmarkIsJSON/OldMethod
BenchmarkIsJSON/OldMethod-12         	 1365619	       863.3 ns/op
BenchmarkIsJSON/NewMethod
BenchmarkIsJSON/NewMethod-12         	 2903380	       416.9 ns/op
PASS
```
> [Typing] Improving our `IsJSON` function

- lib/cryptography/cryptography.go
- main.go
This is to prevent a thundering herd problem on our Kafka cluster where a large amount of consumer restarts at the same time and cause our Kafka brokers to rebalance based on new connections.
> Prevent thundering herd

- clients/bigquery/converters/converters.go
- clients/bigquery/converters/converters_test.go
- lib/typing/values/string.go
Addressing the TODO from #1024, which is to consolidate how we are casting `value any` into a `string`.
> Address TODO

- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_temp_test.go
- lib/destination/ddl/ddl_test.go
- lib/typing/columns/columns.go
Standing up a function for determining whether we should be creating primary keys or not.
> [DDL] Cleaning up primary key creation

- clients/bigquery/bigquery.go
We should not hard fail on large rows as this causes a pipeline blockage for a deterministic failure case.
Instead, we should skip the row and log
> [BigQuery] Skip large rows

- clients/bigquery/bigquery.go
- clients/bigquery/partition_test.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_test.go
Standing up `BuildCreateTableSQL` so it's more modular
* Easier to test
* No massive struct
* Ability to import `BuildCreateTableSQL` into Reader
> [DDL] Standing up `BuildCreateTableSQL`

- clients/databricks/store.go
- clients/mssql/staging.go
- clients/redshift/staging.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
Following the same idea as https://github.com/artie-labs/transfer/pull/1033
> Call create table in more places.

- clients/databricks/file.go
- lib/maputil/map.go
- lib/maputil/map_test.go
This way, we can handle generic types and use it more broadly across our codebase.
> Adding `GetTypeFromMap` to `maputil`

- lib/typing/columns/diff.go
I'm trying to limit the usage of `columns.Columns` and deprecate it as the struct is unnecessarily complicated
> Don't use `columns.Columns`

- clients/bigquery/dialect/ddl.go
- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/databricks/dialect/ddl.go
- clients/databricks/dialect/dialect.go
- clients/databricks/dialect/dialect_test.go
- clients/mssql/dialect/ddl.go
- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/redshift/dialect/ddl.go
- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
- clients/snowflake/dialect/ddl.go
- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- lib/destination/ddl/ddl.go
- lib/sql/dialect.go
1. Adding two functions `BuildAddColumnQuery` and `BuildDropColumnQuery`
2. Creating a file called `ddl.go`
Once this is merged, the eventual goals are:
1. Remove the need to have `constants.ColumnOperation`
2. Remove `buildAlterColumnQuery`
3. Move all DDL related functions to `ddl.go`
4. Get rid of `IsColumnAlreadyExistsErr()`
> [DDL] Refactor adding and dropping columns

- clients/bigquery/bigquery.go
- clients/bigquery/dialect/typing.go
- clients/bigquery/dialect/typing_test.go
- clients/bigquery/merge.go
- clients/databricks/dialect/typing.go
- clients/databricks/dialect/typing_test.go
- clients/databricks/store.go
- clients/mssql/dialect/typing.go
- clients/mssql/dialect/typing_test.go
- clients/mssql/staging.go
- clients/redshift/dialect/typing.go
- clients/redshift/dialect/typing_test.go
- clients/redshift/staging.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/table.go
- clients/snowflake/dialect/typing.go
- clients/snowflake/dialect/typing_test.go
- clients/snowflake/staging.go
- lib/config/types.go
- lib/destination/ddl/ddl.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/ddl/ddl_temp_test.go
- lib/destination/ddl/ddl_test.go
- lib/destination/types/types.go
- lib/sql/dialect.go
- lib/typing/decimal/details.go
- lib/typing/decimal/details_test.go
By default, if the data type is a variable numeric at the source, we'll create it as `STRING`.
If this is enabled, we'll create it as NUMERIC.
> [BigQuery] Create numeric data type for variable numerics

- clients/redshift/dialect/ddl.go
- clients/redshift/dialect/dialect_test.go
- lib/destination/ddl/ddl_test.go
Implementing adding and dropping columns directly in the function.
> [Redshift] Remove `buildAlterColumnQuery`

- clients/bigquery/bigquery.go
- clients/databricks/store.go
- clients/mssql/staging.go
- clients/redshift/staging.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/table.go
- clients/snowflake/staging.go
We need to pass in an explicit set of columns to create a table with, rather than deriving it from `tableData`
This is because in `Append` and `Merge`, we are filtering out columns that we are using as metadata: https://github.com/artie-labs/transfer/blob/fa08f22cecce6e201d573882b4ecc1f5c7e61ac3/clients/shared/merge.go#L46
> [DDL] Create table pass in columns

- clients/s3/s3.go
- clients/s3/s3_test.go
- lib/parquetutil/generate_schema.go
- lib/parquetutil/parse_values.go
- lib/parquetutil/parse_values_test.go
- lib/typing/parquet.go
- lib/typing/parquet_test.go
Improving the way we write Parquet files, I've added comments to all the changes directly.
> Improve Parquet

- clients/shared/merge.go
- clients/shared/table.go
- lib/destination/ddl/ddl.go
We only filtered on `AlterTableAddColumns`, we need to do it for `CreateTable` as well.
> [DDL] Filter for valid columns on `CreateTable`

- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- clients/snowflake/staging.go
If we fail a COPY INTO for a non-temp table, we need to remove the staging files so that we can try again.
> [Snowflake] Clean up staging files after a failed `COPY INTO`

- clients/bigquery/storagewrite.go
- lib/debezium/converters/basic.go
- lib/debezium/converters/basic_test.go
- lib/debezium/schema.go
- lib/debezium/types_test.go
Debezium will emit
```json
{
"type": "array",
"items": {
"type": "string",
"optional": true,
"name": "io.debezium.data.Json",
"version": 1
},
"optional": true,
"field": "attributes"
}
``` 
As the field object if the value contains an array of JSON objects. We were previously not doing anything with this information.
As such, we were mainly returning an array of JSON strings (which is what Debezium emits). This PR adds the ability for us to check the `items.name` and if it's JSON, we'll add an additional step to parse the JSON string into an object.
> [Debezium] Better support around JSON arrays

- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/shared/merge.go
- clients/snowflake/dialect/dialect_test.go
Same rationale as https://github.com/artie-labs/transfer/pull/1078 and https://github.com/artie-labs/transfer/pull/1077.
Matching TOASTED placeholders using LIKE
> [MSSQL] TOAST

- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
- lib/sql/tests/columns_test.go
Same thing as https://github.com/artie-labs/transfer/pull/1079, https://github.com/artie-labs/transfer/pull/1078, https://github.com/artie-labs/transfer/pull/1077
> [Redshift] Better handling around TOAST columns

- lib/debezium/converters/basic.go
- lib/debezium/converters/basic_test.go
Items in a JSON array should all be strings, if it's not - let's explicitly fail here.
> [Debezium] Array item type safety

- clients/databricks/dialect/dialect.go
- clients/databricks/dialect/dialect_test.go
- clients/databricks/store.go
Same rationale as https://github.com/artie-labs/transfer/pull/1078
> [Databricks] Better handling of TOAST columns

- lib/cdc/util/relational_event.go
For completeness, so that Reader can now emit and publish to this field when using GTID.
> [Debezium] Include GTID in the Source payload

- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
- lib/sql/tests/columns_test.go
Accounting for the fact that we may not be able to run `JSON_SERIALIZE` on a SUPER data type if the resulting value will exceed the DDL limit for a VARCHAR column.
> [Redshift] Fix TOAST

- clients/bigquery/bigquery.go
- lib/db/db.go
If `BQ_AUDIT_ROWS` is enabled, we will perform an additional check to make sure the staging table has more rows than the number of rows in our in-memory database.
> [BigQuery] Additional guardrails

- clients/bigquery/bigquery.go
Instead of calling `.Rows()` which will iterate over the in-memory database and append rows for which we just call `len()` on, we can call `NumberOfRows` which will return us the number of rows and skip the intermediary object.
Code ref: https://github.com/artie-labs/transfer/blob/91fa45294ebcd918eaa14e95fd76eace7c0db653/lib/optimization/table_data.go#L168-L193
> Small BQ audit optimization

- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
To prevent sql injection so this is safe to be used on user-supplied values.
> Remove any double quotes from the string in `SnowflakeDialect.QuoteIdentifier()`

- clients/bigquery/dialect/dialect.go
- clients/bigquery/dialect/dialect_test.go
- clients/databricks/dialect/dialect.go
- clients/databricks/dialect/dialect_test.go
- clients/mssql/dialect/dialect.go
- clients/mssql/dialect/dialect_test.go
- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
Same as https://github.com/artie-labs/transfer/pull/1103, for the rest of the dialects.
> Remove quotes when quoting identifiers for remaining dialects

- lib/typing/mongo/bson.go
- lib/typing/mongo/bson_test.go
Making our MongoDB parser more resilient to invalid years
> Improve MongoDB datetime / timestamp parser

- clients/bigquery/bigquery.go
- clients/databricks/store.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/snowflake/ddl_test.go
- clients/snowflake/snowflake.go
- lib/destination/dwh.go
This PR removes the need for us to pass a global object `tableData` for retrieving the table config. Instead, we can just pass the tableID and whether we should drop deleted columns or not.
This PR will simplify the work needed to support multi-step merge.
> Simplifying `GetTableConfig`

- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/table.go
We don't need to pass `tableData`, we just care about the mode.
> Slight improvement around create table

- clients/bigquery/storagewrite.go
If casting failed, we'll know which column was problematic.
> [BigQuery] Wrapping error

- clients/bigquery/bigquery.go
- clients/databricks/store.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/snowflake/snowflake.go
- lib/destination/dwh.go
The intent of this PR is to reduce the main PR https://github.com/artie-labs/transfer/pull/1108 into PRs that are easier to review.
This PR is adding a scaffold for `DropTable`
> Adding `DropTable` scaffold

- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
Following #1119
The intent of this PR is to reduce the main PR https://github.com/artie-labs/transfer/pull/1108 into PRs that are easier to review.
This PR is coming up with a MSM query that:
1. Does not strip any Artie generated columns since this is used for staging -> msm staging table
2. Does not delete any rows from `msm staging table`
> [Snowflake] Implementing MSM Query

- clients/bigquery/merge.go
- clients/databricks/store.go
- clients/mssql/store.go
- clients/redshift/redshift.go
- clients/s3/s3.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/writes.go
- lib/destination/dwh.go
- processes/consumer/flush.go
This PR does 2 things.
1. Changes the signature of merge by adding a flag on whether we should commit the transaction or not
2. Commit the transaction based on ^
Committing the transaction means that we'll commit our Kafka offset and clear our in-memory data.
> Extending merge to inform whether we should commit tx or not

- models/event/event.go
- models/event/event_save_test.go
- models/event/event_test.go
- processes/consumer/flush_test.go
This PR removes the need for us to store `pkMap`, which is storing both the primary key(s) and their value(s), which is separate from event data.
Instead, we can store just the list of primary keys and defer the primary key values to be whatever is in the event data.
> Refactor Event Primary Keys

- clients/iceberg/dialect/data_types.go
- clients/iceberg/dialect/dialect.go
- clients/iceberg/dialect/tableid.go
This series of PRs is aimed to support Apache Iceberg as a destination. The main PR can be found here: https://github.com/artie-labs/transfer/pull/1133
This particular PR is adding the basic:
1. `TableIdentifier`
2. Parts of the `Dialect` implemented, with the rest left as a scaffold.
> Supporting Iceberg - Part 1

- clients/bigquery/bigquery.go
- clients/bigquery/bigquery_suite_test.go
- lib/destination/ddl/ddl_suite_test.go
- lib/destination/utils/load.go
- main.go
- processes/consumer/flush_suite_test.go
As the PR title suggests. This will reduce usage of `context.Background()`
> Threading context to `LoadStore`

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
- clients/redshift/staging.go
Use a constant instead of hardcoding `\N` and `\\N` and having to worry about escaping.
> [Redshift] Simplify nulls

- lib/typing/converters/string_converter.go
- lib/typing/converters/string_converter_test.go
- lib/typing/values/string.go
This block has been here long enough and we have not had any encounters. As such, this PR removes the TODO and having it explicitly return an error if data type mapping fails.
> Removing TODO

- clients/redshift/cast.go
- clients/redshift/staging.go
- lib/typing/converters/string_converter.go
- lib/typing/converters/string_converter_test.go
- lib/typing/ext/variables.go
- lib/typing/values/string.go
- lib/typing/values/string_test.go
* TIMESTAMP and TIMESTAMP_NTZ only allow up to microsecond precision
* We are sometimes running into an issue where we emit nanosecond values
> [Redshift] Fixes around `TIMESTAMP`, `TIMESTAMP_NTZ`

- clients/bigquery/merge_test.go
- clients/shared/default_value.go
- clients/snowflake/staging_test.go
There may be a SQL ambiguous error if the table and column names are the same
> Tweak default value update

- models/event/event.go
- models/event/event_test.go
This function was susceptible to two errors:
1. It did not escape column names, even though it should since it gets escaped during `event.Save()`
2. If the primary key value didn't exist in the payload, it wouldn't error.
> Refactor Event `PrimaryKeyValue`

- clients/snowflake/dialect/dialect_test.go
- clients/snowflake/dialect/tableid.go
- clients/snowflake/dialect/tableid_test.go
- clients/snowflake/snowflake_dedupe_test.go
- clients/snowflake/snowflake_test.go
- clients/snowflake/staging_test.go
- clients/snowflake/util_test.go
- lib/destination/ddl/ddl_sflk_test.go
- lib/destination/ddl/ddl_temp_test.go
We were previously not escaping schema or database names. This PR adds that capability.
> [Snowflake] Escape schema and database for `FullyQualifiedName`

- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/mongo/debezium_test.go
- lib/cdc/relational/debezium_test.go
- lib/cdc/util/relational_event.go
- lib/cdc/util/relational_event_decimal_test.go
- lib/cdc/util/relational_event_test.go
- models/event/event.go
We shouldn't need to pass in `pkMap` into `GetData` and try to inject it. And with this PR being applied: https://github.com/artie-labs/transfer/pull/1167, Transfer will throw an error if the primary key doesn't exist in the event data.
> Simplify `GetData`

- clients/redshift/redshift.go
- clients/redshift/redshift_suite_test.go
- clients/redshift/staging.go
- lib/config/destination_types.go
- lib/destination/ddl/ddl_suite_test.go
- lib/destination/utils/load.go
If role arn is passed in, we'll generate temporary credentials and inject it into Redshift's credentials clause.
> Allow RS credentials override

- clients/bigquery/bigquery.go
- lib/batch/batch.go
- lib/batch/batch_test.go
This way, we can choose to take either the encoded bytes and/or the rows that have been validated against the payload size.
This will be helpful for Reader to reduce a layer of marshal. We are currently encoding in `BySize` and then running an unmarshal to get the parent object to convert into a Kafka message.
> Refactor `batch.BySize` to yield both the casted rows and encoded bytes.

- clients/redshift/dialect/default.go
- clients/redshift/dialect/default_test.go
- clients/shared/default_value.go
Redshift UPDATE does not support table aliasing nor do we need it. Redshift will not throw an ambiguous error if the table and column name are the same.
> [Redshift] Tweak default value query

- clients/iceberg/store.go
- lib/config/destination_types.go
Moving the ApacheLivyConfig to `S3Tables`. This way, we can reuse the same configurations for the rest of our services.
> [Iceberg] Moving config to S3Tables

- clients/shared/default_value.go
- clients/shared/default_value_test.go
This PR is widening our default value parser to be more resilient around decimal types.
The following scenario may happen if the target table has a NUMERIC column (without precision and scale specified) and incoming data is an integer.
> [Decimal] Refactor Default Value + Add Test

- clients/bigquery/dialect/typing.go
- clients/bigquery/dialect/typing_test.go
- clients/bigquery/storagewrite.go
- clients/shared/default_value.go
- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
- lib/typing/typing.go
If the target data type is a variable numeric or big numeric, we are returning it as a `EDecimal` without any precision or scale defined. As such, we should be handling the NPE that may arise when `ExtendedDecimalDetails` is nil.
This also fixes https://github.com/artie-labs/transfer/issues/1054
> [BigQuery] Handle extended decimals

- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
Having `writeTemporaryTableFile` output a File object which contains both the file path and name values. 
We will be using the file name as part of the COPY INTO command to ensure that the file we just uploaded is being processed.
> [Snowflake] `writeTemporaryTableFile` to output file path and name

- clients/databricks/dialect/dialect.go
- clients/databricks/dialect/dialect_test.go
I'm a bit surprised this is default to false. But this will tell Databricks that a row may be multiple lines and to follow the escape rune and delimiter.
> [Databricks] Include multiLine option

- lib/typing/values/string.go
- lib/typing/values/string_test.go
We will now include the converter type if the conversion failed. This will help us with debugging by quickly narrowing in on the problematic converter.
> Improve converter errors

- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
Adding improvements around Snowflake PUT & COPY INTO commands:
1. Adding single quotes around the filename for PUT
2. Specifying the file to copy for Snowflake. [1]
[1] - This process was susceptible to silent failures. We noticed that the older versions of Snowflake's SDK could have PUT silently fail but still return a success. We would then issue a COPY INTO from a stage to a table and given that there are no files in the stage, the COPY INTO would then also succeed. This could then lead to us to have inconsistent or missing data if PUT failed.
By specifying the file name as part of COPY INTO, Snowflake will throw an error if the remote file does not exist.
> [Snowflake] Improving PUT & COPY INTO

- clients/snowflake/dialect/dialect.go
- clients/snowflake/dialect/dialect_test.go
- clients/snowflake/staging.go
- clients/snowflake/util.go
- clients/snowflake/util_test.go
1. Moving the escape function into the Snowflake dialect pkg
2. Passing around columns instead of `*columns.Columns`
3. Filtering of invalid columns is done upstream via `.ValidColumns()`
By doing this, we are one step closer to moving the COPY command into the dialect pkg and having robust tests around it.
> [Snowflake] Moving the Escape function

- clients/s3/s3.go
- clients/s3/tableid.go
- clients/s3/tableid_test.go
- lib/config/destination_types.go
By default, we'll use `.`
But you can now pass in a custom separator string and we'll use that instead.
Using `/` delimiter allows us organize data better:
> Adding S3 Filename separator

- clients/databricks/file.go
- clients/databricks/file_test.go
- clients/databricks/store.go
After running the Databricks integration tests, I've observed that by using the same delta file for COPY INTO in Databricks, it will result in subsequent COPY INTOs having no-ops.
My guess is that there's heavy caching on Databricks end to not process that particular COPY INTO. By using a different name, we're able to bypass this problem.
> [Databricks] Fixes around COPY INTO

- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
We should update, insert then delete.
By doing insert then update, we're updating rows that were just recently inserted.
> [Redshift] Tweak MERGE statement order

- lib/parquetutil/parse_values.go
- lib/parquetutil/parse_values_test.go
- lib/typing/decimal/details.go
- lib/typing/parquet.go
1. Our previous way of handling decimal was brittle and required special parsing from our customers. Instead of storing the string value, we should be storing the two's complement value (which the library we are using supports).
2. We were using `BYTE_ARRAY` instead of `FIXED_LEN_BYTE_ARRAY`, which clients like `pyarrow` expects decimals to be stored either in Parquet floats, INT32/INT64 or `FIXED_LEN_BYTE_ARRAY`
> Improved Parquet handling for DECIMAL

- clients/bigquery/bigquery.go
- clients/bigquery/bigquery_test.go
- clients/databricks/store.go
- clients/iceberg/store.go
- clients/mssql/store.go
- clients/mssql/store_test.go
- clients/redshift/redshift.go
- clients/redshift/redshift_test.go
- clients/s3/s3.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/multi_step_merge.go
- clients/shared/sweep.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- integration_tests/shared/framework.go
- lib/destination/ddl/ddl_alter_delete_test.go
- lib/destination/ddl/ddl_bq_test.go
- lib/destination/ddl/ddl_temp_test.go
- lib/destination/destination.go
- lib/kafkalib/topic.go
- lib/kafkalib/topic_test.go
There are 3 changes here.
1. Introducing a slim data structure called `DatabaseAndSchemaPair` which is similar to `TableID` and using this instead of `kafkalib.TopicConfig`
2. Refactoring `GetUniqueDatabaseAndSchemaPairs` to be more clear
3. Refactoring `Sweep`
> Minor refactors

- clients/bigquery/bigquery.go
- clients/bigquery/merge.go
We were previously using the default stream for BigQuery which provides at-least-once semantics and we would then dedupe the rows prior to merging.
However, this hinders our ability to truly audit the number of rows in the staging table and whether they fully made it to the staging table or not.
This PR is moving us to the committed stream which will allow us to get exactly-once semantics and an exact rows written count to the staging table, thus providing more reliability and assurances around data consistency.
> [BigQuery] Update StorageWriter to be exactly once

- clients/bigquery/bigquery.go
- clients/bigquery/dialect/typing.go
If we don't have precision or scale, we are returning NUMERIC. However, we should take into account if BIGNUMERIC is enabled.
We should also log some row errors out so we can action on the actual error.
> [BigQuery] Returning `row_errors` if present + numeric refactor

- clients/bigquery/dialect/typing.go
- clients/bigquery/dialect/typing_test.go
- lib/optimization/table_data.go
If they aren't passed in, we should be setting to what the true precision and scale values should be. This way, we don't overwrite the decimal kind details when we merge the columns.
> [BigQuery] Updating NUMERIC and BIGNUMERIC defaults

- clients/bigquery/dialect/typing.go
- lib/config/types.go
- lib/destination/ddl/ddl.go
- lib/typing/decimal/base_test.go
- lib/typing/decimal/details.go
- lib/typing/decimal/details_test.go
We previously would create a TEXT (or equivalent) column for a variable numeric data type. However, we have found that most users want it to be an actual numeric or big numeric column in BigQuery so they can query it easier.
As such, I've renamed this variable to be `UseBigNumericForVariableNumeric` and we are now defaulting to create a `NUMERIC` data type for a variable numeric data type. And if ☝️ is enabled, we'll create the data type as `BIGNUMERIC`.
> [BigQuery] Refactor BIGNUMERIC and NUMERIC

- clients/redshift/cast.go
- clients/redshift/cast_test.go
Postgres allows storage of strings in JSONB columns, for which we are creating SUPER in Redshift.
However, Redshift SUPER has a DDL limit of 2^16 if the actual value is a string. We needed to escape the string with quotes for it to be valid
> Fixing Redshift Edge Case

- clients/snowflake/snowflake_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
This PR is standardizing the usage of `writeTemporaryTableFileGZIP`, while this is enabled - we can remove the `AUTO_COMPRESS` flag in `PUT`
> Addressing Snowflake TODO

- lib/apachelivy/client.go
- lib/apachelivy/types.go
If there are too many sessions being created at the same time, let's handle the error, throttle sleep and then retry.
> [Livy] Adding throttling

- lib/array/strings.go
- lib/array/strings_test.go
If the value is already a string, we don't need to run this through JSON parse again. 
By going through the parsing function again, we're double escaping the value
> [BigQuery] Fix nested JSON arrays

- clients/iceberg/staging.go
- clients/iceberg/staging_test.go
We should be running our column names through our dialect identifier function to normalize the column names. This primarily impacts our reader as we're already calling `column.EscapeName` during normal replication.
> [Iceberg] Lowercasing the column names

- clients/bigquery/storagewrite.go
- lib/debezium/converters/basic.go
- lib/debezium/converters/basic_test.go
- lib/debezium/types_test.go
- lib/jsonutil/jsonutil.go
- lib/jsonutil/jsonutil_test.go
We were previously sanitizing incoming JSON values by running this through a JSON parser and then stringifying the results to get rid of duplicate keys.
Given that the value is escaped, if we run `JSON.Marshal()` again, it will try to escape the results again. This is then further exacerbated if the column type is an array and inner fields are JSON. This then leaves us with a Frankenstein value where it's an array of JSON strings (instead of JSON objects).
If we then try to marshal the array, it will lead inner values getting double escaped.
> Refactor `SanitizePayload` to be `ParsePayload`

- lib/parquetutil/parse_values.go
- lib/parquetutil/parse_values_test.go
- lib/typing/parquet.go
- lib/typing/parquet_test.go
This PR adds additional handling around Parquet logical types such as:
1. DATE
2. TIME
3. TIMESTAMP
This will make it easier for Parquet consumers to be able to read and interpret our delta files.
> [Parquet] Better handling around logical types

- lib/debezium/types.go
- lib/debezium/types_test.go
Seeing this type pop up in our warning logs, so we're adding explicit handling for this type. There should be no functional difference with this PR other than less warnings.
> Add handling for `map[string]any`

- clients/shared/temp_table.go
- clients/shared/temp_table_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
We are doing a lot of the same boilerplate code for all destinations. This PR starts a shared function that we can extend and reuse for other destinations, starting with Snowflake.
Once this is all linked in here, we can then play around with adding randomness to the file name so that we don't run into a race condition when trying to parallelize our table loading (as the file names may collide with eachother)
> Moving `WriteTemporaryTableFile` to be shared

- clients/redshift/dialect/typing.go
- clients/redshift/dialect/typing_test.go
We're supporting `character` for Redshift.
> [Redshift] Adding `CHARACTER` to our typing library

- clients/redshift/cast.go
- clients/redshift/cast_test.go
- clients/redshift/staging.go
- clients/shared/temp_table.go
- clients/shared/temp_table_test.go
- clients/snowflake/staging.go
- clients/snowflake/staging_test.go
Pre-requisite: https://github.com/artie-labs/transfer/pull/1279
This PR moves Redshift to be using the same shared utility.
> More usage of `WriteTemporaryTableFile`

- lib/debezium/types.go
- lib/debezium/types_test.go
Updating this function to support `int8` which will unblock Reader's snapshot process
> Support `int8`

- lib/apachelivy/client.go
- lib/apachelivy/types.go
We should have more resiliency around sessions. Right now, we are coupling all statements to a particular session. If the session dies,  we will immediately fail the entire call stack. 
That doesn't need to happen as sessions do not need to be treated as atomic. If statements in a session succeeded prior to the session dying, then we don't need to retry the statements again.
* Adding retries around ExecContext and QueryContext by reusing our Retry framework
* Consolidating the way we retrieve sessions back from Livy
> [Livy] Session resiliency

- lib/debezium/types.go
- lib/debezium/types_test.go
Same rationale as https://github.com/artie-labs/transfer/pull/1285, but this time it's for `[]any`
> [Default Value] Add another case to consider

- clients/databricks/store.go
- clients/redshift/staging.go
- clients/shared/temp_table.go
- clients/shared/temp_table_test.go
- clients/snowflake/staging.go
Standing this up and decoupling how file names get generated. I did this so that we have Databricks share the same implementation (`WriteTemporaryDataFile`)
> Standing up `TemporaryDataFile`

- clients/redshift/dialect/dialect.go
- clients/redshift/dialect/dialect_test.go
Redshift's `TRUNCATE TABLE` does not support `TRUNCATE TABLE IF EXISTS`, so we'll need to swallow the table does not exist error.
> [Redshift] Implement `IsTableDoesNotExistErr`

- clients/redshift/cast.go
- clients/shared/temp_table.go
- lib/typing/converters/string_converter.go
- lib/typing/converters/string_converter_test.go
[Source](https://docs.aws.amazon.com/redshift/latest/dg/ingest-super.html#:~:text=Copying%20data%20from%20text%20and%20CSV)
We need to be wrapping literal strings in double quotes when the Redshift data type is SUPER
> [Redshift] Tweaking Redshift SUPER.

- lib/config/config.go
- lib/config/config_test.go
- processes/consumer/kafka.go
We should randomize the bootstrap server addresses before we send it to our Kafka SDK as it's not deterministically shuffling (https://github.com/segmentio/kafka-go/blob/755cac09a1e2d850da573c72f7ccdeeefbb3bbf5/transport.go#L1152-L1160)
Our Kafka library (kafka-segment-io) only randomizes bootstrap server as part of the transport protocol. By randomizing here, we'll have a better client connection distribution and avoid hot brokers.
* https://github.com/segmentio/kafka-go/blob/755cac09a1e2d850da573c72f7ccdeeefbb3bbf5/consumergroup.go#L878
* https://github.com/segmentio/kafka-go/blob/755cac09a1e2d850da573c72f7ccdeeefbb3bbf5/consumergroup.go#L898-L921
* ☝️ is iterating over to find the first successful broker, instead of first shuffling.
> Kafka Randomize

- clients/iceberg/store.go
- lib/apachelivy/client.go
- lib/apachelivy/types.go
- lib/config/destination_types.go
* Adding a mutex lock on Livy client
There's a race condition where if multiple codepaths are calling Livy client at the same time, ensure session will be invoked. As such, Livy will try to create a bunch of clients and leaving the previous orphaned and taking up compute resources.
This code makes it so that there will only be one session shared per Transfer pod.
* Adding the ability to specify K8 request for memory for driver and executor
Once this is in, we'll also want to add this to our dashboard so we can specify how much memory we want to give each Livy client for a particular deployment.
> Improving Livy

- clients/iceberg/staging.go
- clients/iceberg/store.go
- clients/s3/s3.go
- clients/s3/s3_test.go
- lib/awslib/s3.go
- lib/destination/utils/load.go
Standing up a S3 Client so that we can use this to upload files to S3 instead of calling `UploadLocalFileToS3`. This will make it easier for us to support more functionality with S3.
With this PR, I started to move Iceberg and S3 to start using this function.
> Standing up a S3 Client

- lib/apachelivy/schema.go
- lib/typing/assert.go
- lib/typing/assert_test.go
Some values may be optional, which will return `nil`.
I added a helper function in our typing library to return the zero value of that type if the value is nil.
> Better typing support around describe table

- clients/databricks/dialect/dialect.go
- clients/databricks/dialect/dialect_test.go
- clients/iceberg/dialect/dialect.go
- clients/iceberg/dialect/dialect_test.go
- clients/shared/temp_table.go
- lib/config/destination_types.go
- lib/config/destinations.go
* Spark's CSV defaults are not RFC 4180 compliant, which is why we need to specify escape and multi-line. We also need to specify the line separator as the defaults are `\r`, `\r\n` and `\n`. When it really should just be `\n`.
Further sleuthing last night also revealed this: https://issues.apache.org/jira/browse/SPARK-22236
^ This is why we were getting the column out of bound error yesterday. Further, we would want to specify `\r\n`. If we enabled `UseCRLF` (carriage return, line feed) on our CSV writer, which we are not.
https://pkg.go.dev/encoding/csv#Writer
This is a bug with Databricks and iceberg, which both use Spark plugins.
---
I've also added a role to our Snowflake config for when we want to support Snowflake roles in the future!
> Misc Improvements

- lib/awslib/sts.go
- lib/awslib/sts_test.go
Adding a mutex here so we don't run into a scenario where simultaneous call paths are trying to call `BuildCredentials`, realizing that it expired and overriding one another.
> [AWS STS] Adding mutex

- clients/iceberg/store.go
- clients/redshift/redshift.go
- clients/redshift/staging.go
- lib/awslib/config.go
Adding helper functions into our awslib to make it easier for our codepaths to migrate to the new S3 client object.
This PR then moves Redshift to start using it.
> More refactor around S3 Client

- clients/bigquery/dialect/typing.go
- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
- lib/typing/decimal/details.go
- lib/typing/decimal/details_test.go
- lib/typing/typing.go
When we create a variable numeric column, we're creating it with the decimal details set such that precision is not specified and default scale.
Our merge columns logic did not have this understanding and as such, there was no merge column of taking the higher precision from the destination to update the in-memory column.
> Update copying decimal details over

- clients/shared/default_value.go
- clients/shared/default_value_test.go
- lib/debezium/converters/basic.go
We need to marshal the incoming default value since we are unmarshaling the JSON value upstream.
I've also added some guardrails to the current default value converter to make it less brittle.
> Update default value.

- clients/iceberg/staging.go
- lib/config/types.go
- lib/typing/converters/string_converter.go
- lib/typing/converters/string_converter_test.go
We are writing TSV GZIPPED delta files while loading into the destination. As such, we already have logic that will take the destination data type and build converters that will convert incoming data to match the destination data type in string (since we're loading through TSV).
The problem is that in our string data type converter, the incoming value could be boolean, integers, floats, etc and we should try to convert them into string without sacrificing readability or precision. Our current method which has been renamed to be `convertOld` does some of that, however the string escape is non-optimal and the way we inspect data type is not great either.
This PR is coming up with a different approach, one where we're doing a switch case on the actual data type and in the String converter, …
> New String Converter

- lib/destination/ddl/expiry.go
- lib/destination/ddl/expiry_test.go
Should be using `strings.EqualFold` since identifiers are uppercased in Snowflake.
> Better handling of `msm` tables

- Makefile
- clients/s3/s3.go
- integration_tests/parquet/main.go
- integration_tests/parquet/verify_parquet.py
- lib/config/types.go
- lib/parquetutil/generate_schema.go
- lib/parquetutil/parse_values.go
- lib/parquetutil/parse_values_test.go
- lib/typing/parquet.go
- lib/typing/parquet_test.go
This PR adds the ability to specify a location in Parquet.
By doing this, we'll convert the incoming data to be in the specified location.
> Parquet to allow location 

- clients/iceberg/table.go
- clients/s3/s3.go
- integration_tests/shared/framework.go
- lib/destination/destination.go
Moving this from the `Destination` interface to the `Baseline` interface
To make this possible, I've also done the following:
* Stub out the S3 implementation
* Rename Iceberg's `DeleteTable` to `DropTable`
> Moving `DropTable` to the `Baseline` interface

- lib/kafkalib/topic.go
- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
- models/event/event.go
With https://github.com/artie-labs/transfer/pull/1332, we now have an extensible way to filter Artie columns by configs.
This PR adds the ability to specify whether you want Artie to include the Artie operation column in your destination.
> Adding the ability to Include Artie Operation column

- clients/redshift/dialect/ddl.go
- clients/redshift/dialect/typing.go
- clients/redshift/dialect/typing_test.go
Right now, we have a special handling on string precision for Redshift and MSSQL where it's being retrieved from a separate column.
This adds a weird bloat to the dialect's `KindForDataType` signature and also makes it so that we are unable to use this translation logic in the rest of our services.
> Include string precision into Redshift typing

- Makefile
- clients/redshift/dialect/ddl.go
- clients/redshift/dialect/typing.go
- integration_tests/destination_types/main.go
- integration_tests/shared/destination_types.go
We have been relying on a hybrid approach to retrieve the string precision for some time now. This PR fully deprecates the old method and I've also added an integration test to make sure the transition is safe.
> Refactoring Redshift to not use the string precision argument

- clients/mssql/dialect/typing.go
- clients/mssql/dialect/typing_test.go
- clients/redshift/dialect/typing.go
- clients/redshift/dialect/typing_test.go
- lib/typing/errors.go
- lib/typing/errors_test.go
So we can start having better error detection for libraries that are dependent on Transfer's typing, starting with MSSQL and Redshift.
> Adding UnsupportedDataTypeError

- clients/bigquery/bigquery.go
- clients/redshift/redshift.go
- clients/shared/merge.go
- clients/shared/multi_step_merge.go
- clients/snowflake/snowflake.go
- clients/snowflake/snowflake_test.go
- lib/destination/destination.go
This is similar to the assertion checks we added to staging tables. With this, we'll have a higher guarantee that the rows were written to the target table via merge.
> Adding merge assertion checks

- lib/cdc/event.go
- lib/cdc/mongo/debezium.go
- lib/cdc/util/relational_event.go
- lib/config/constants/constants.go
- lib/kafkalib/topic.go
- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
- lib/typing/columns/diff_test.go
- models/event/event.go
Re-introducing the initial version of https://github.com/artie-labs/transfer/pull/1356 so it's possible to use the source table name as part of a compound key in the destination table, for tables that are fanned in across schemas.
> Add a setting for including full source table name as a column

- models/event/event.go
To resolve this Sentry:
> failed to parse value: unknown type: constants.Operation, value: u
> Missed one spot to escape operation

- lib/config/config.go
Using `cmp.Or` and inlining more to be consistent with the rest of our codebase.
> Minor refactor around config

- clients/shared/temp_table.go
- lib/debezium/converters/date.go
- lib/debezium/converters/date_test.go
- processes/consumer/flush.go
If the year of the date exceeds YYYY, let's have it handled at the Debezium level.
> [date] Edge case handling

- clients/bigquery/bigquery.go
- clients/databricks/store.go
- clients/mssql/store.go
- clients/postgres/postgres.go
- clients/redshift/redshift.go
- clients/shared/append.go
- clients/shared/merge.go
- clients/shared/multi_step_merge.go
- clients/shared/table_config.go
- clients/shared/table_config_test.go
- clients/snowflake/ddl_test.go
- clients/snowflake/snowflake.go
- integration_tests/destination_append/main.go
- integration_tests/destination_merge/main.go
- integration_tests/shared/baseline.go
- integration_tests/shared/destination.go
- integration_tests/shared/framework.go
- lib/db/db.go
- lib/destination/destination.go
As per title, we don't need to have both - we also prefer query context anyways, so this PR removes `Query`.
> Remove `Query` and standardize on `QueryContext`

- clients/bigquery/bigquery.go
- lib/bigquerylib/bigquery.go
Doing this so that we can import this functionality into different parts of our app without having to import the whole BigQuery destination. This PR makes it a lot more portable.
I also renamed this function to be closer aligned with the docs
> [bigquery] Moving this function into a library rather on the BigQuery destination interface

- .github/workflows/go-checks.yml
Potential fix for [https://github.com/artie-labs/transfer/security/code-scanning/2](https://github.com/artie-labs/transfer/security/code-scanning/2)
To fix the problem, you should add a `permissions` block to the workflow to restrict the GITHUB_TOKEN to the least privilege required. In this case, the workflow only needs to read repository contents, so you should set `contents: read`. This can be done either at the root of the workflow (to apply to all jobs) or at the job level. The best practice is to add it at the root level, just below the `name` and before the `on` key, so that all jobs inherit these permissions unless overridden. No additional imports or definitions are needed; this is a YAML configuration change.
---
_Suggested fixes powered by Copilot Autofix. Review carefully …
> Potential fix for code scanning alert no. 2: Workflow does not contain permissions

- lib/optimization/table_data.go
- lib/optimization/table_data_test.go
If we receive a delete payload and the previous row value exists, we are taking every value from that previous row. This assumption is mostly correct, with the exception of system (Artie) generated columns.
The problem with this assumption for system level columns is that we will end up with a row in the target (if soft delete + include operation column is enabled) to be `deleted = true, operation ='u'`
Instead, we should iterate over all the keys from the previous row and if the value is present in the current row, we should not overwrite. 
With the only exception to Artie `only set deleted column` where we should always be taking that from the previous row for correctness.
> Fix previous row bug

- models/event/event.go
- models/event/event_save_test.go
- models/memory.go
- models/memory_test.go
- processes/consumer/flush.go
- processes/consumer/flush_test.go
- processes/consumer/process.go
- processes/consumer/process_test.go
This PR refactors how we are flushing specific tables to be topics based.
For the most part, topic to table is 1:1 and flushing based on specific tables is fine. However, this is not great for fan-in and could cause possible issues downstream.
By moving to be topic specific:
1. Changes nothing for normal 1:1 tables.
2. For fan-in tables, this means that we will flush every table from the unified topic. This is desired because we are committing offsets at the end.
> Refactor flush to be topic specific

- clients/bigquery/bigquery.go
We've had to change this offset a few times, this change makes this configurable so we can configure it per deployment without having to ship a new code change.
> [BigQuery] Allow configurable max request offset kb

- lib/kafkalib/topic.go
- models/event/event.go
This PR supports specifying additional primary keys to the particular table. 
This setting is useful for workloads where we are fanning source tables into one target table and if the source table's primary key is not unique across the different tables.
With this feature, customers can add the full source table name as an additional primary key column
> Supporting additional primary keys

- clients/shared/table.go
Certain destinations like BigQuery have a DDL quota. We should be jittering and adding retries when we hit a quota limit.
> Support retries for adding columns

- e2e_tests/postgres/docker-compose.yaml
looks like the container pulls Kafka 3.9.0
https://quay.io/repository/debezium/kafka/manifest/sha256:e734fed2d2e546b2389460888f37759f42499c7eb47ba7bf8d7187941874b64b
https://quay.io/repository/debezium/kafka/manifest/sha256:d8c48852ac7b5826964bfa79b9f12a5105a3b43c511f33f907abd76bc395aecb
> Use Kafka broker version 3.9.0 in E2E tests
